import { AssumeRoleCommand,GetCallerIdentityCommand,type STSClient } from '@aws-sdk/client-sts';
import { describe,expect,it,vi } from 'vitest';
import { developmentAccounts,developmentUsers,identityDomain } from '../identity-domain.service.js';
import { AwsConnectionBroker,buildAssumeRoleInput,buildRoleArn,sanitiseAwsConnectionError,sanitiseSessionTag,sanitiseSourceIdentity } from './connection-broker.service.js';

function actor(){const user=developmentUsers.find(item=>item.id==='user_org_admin_dev')!;const result=identityDomain.sessionUser(user,'development');result.activeTenantId=user.memberships[0]!.tenantId;result.activeAccountId=developmentAccounts[0]!.id;return result}

describe('cross-account connection broker',()=>{
 it('constructs role ARNs with optional paths',()=>{expect(buildRoleArn('123456789012','PermissionHubReadRole')).toBe('arn:aws:iam::123456789012:role/PermissionHubReadRole');expect(buildRoleArn('123456789012','Read','platform/security')).toBe('arn:aws:iam::123456789012:role/platform/security/Read')});
 it('sanitises source identity and session tags',()=>{expect(sanitiseSourceIdentity('request id / secret')).toBe('request-id---secret');expect(sanitiseSessionTag('tenant\nvalue')).toBe('tenant-value')});
 it('builds bounded AssumeRole input without email addresses',()=>{const context=developmentAccounts[0]!,input=buildAssumeRoleInput(context,'READ',actor(),'external-id','PR-101',1);expect(input.RoleArn).toBe(context.readRoleArn);expect(input.ExternalId).toBe('external-id');expect(input.SourceIdentity).toBe('PR-101');expect(input.RoleSessionName).toMatch(/^PermissionHub-PR-101-/);expect(input.Tags).toEqual(expect.arrayContaining([{Key:'PermissionHubMode',Value:'READ'}]))});
 it('rejects a returned account mismatch and never exposes credential values',async()=>{const send=vi.fn(async(command:unknown)=>{if(command instanceof AssumeRoleCommand)return {Credentials:{AccessKeyId:'temporary-key',SecretAccessKey:'temporary-secret',SessionToken:'temporary-token',Expiration:new Date(Date.now()+900_000)}};if(command instanceof GetCallerIdentityCommand)return {Account:'999999999999',Arn:'arn:aws:sts::999999999999:assumed-role/PermissionHubReadRole/test',UserId:'id'};throw new Error('unexpected')});const broker=new AwsConnectionBroker({stsFactory:()=>({send} as unknown as STSClient),secretResolver:{getSecret:async()=> 'external-id'}});await expect(broker.validateAccountConnection(actor(),developmentAccounts[0]!.id,'READ')).rejects.toMatchObject({code:'AWS_ACCOUNT_MISMATCH'});expect(JSON.stringify((await import('../security-audit.service.js')).securityAudit.events)).not.toContain('temporary-secret')});
 it('caches a read assumption but continues validating identity',async()=>{let assumes=0;const account=developmentAccounts[0]!;const send=vi.fn(async(command:unknown)=>{if(command instanceof AssumeRoleCommand){assumes++;return {Credentials:{AccessKeyId:'key',SecretAccessKey:'secret',SessionToken:'token',Expiration:new Date(Date.now()+900_000)}}}if(command instanceof GetCallerIdentityCommand)return {Account:account.accountId,Arn:`arn:aws:sts::${account.accountId}:assumed-role/PermissionHubReadRole/test`,UserId:'id'};throw new Error('unexpected')});const broker=new AwsConnectionBroker({stsFactory:()=>({send} as unknown as STSClient)});await broker.validateAccountConnection(actor(),account.id,'READ');await broker.validateAccountConnection(actor(),account.id,'READ');expect(assumes).toBe(1)});
 it('blocks provision role assumption while the server feature flag is disabled',async()=>{await expect(new AwsConnectionBroker().getProvisionCredentials(actor(),'PR-100',developmentAccounts[0]!.id)).rejects.toMatchObject({code:'CROSS_ACCOUNT_PROVISIONING_DISABLED'})});
 it('sanitises common AWS connection errors',()=>{expect(sanitiseAwsConnectionError({name:'AccessDenied',message:'secret trust detail'})).toMatchObject({code:'AccessDenied',message:expect.not.stringContaining('secret trust detail')})});
});
