import { DescribeOrganizationCommand,ListAccountsCommand,ListOrganizationalUnitsForParentCommand,ListParentsCommand,ListRootsCommand,type Account,type Root } from '@aws-sdk/client-organizations';
import type { AwsAccountContext } from '../../types.js';
import { cache } from '../cache.service.js';
import { awsConnectionBroker } from './connection-broker.service.js';

export class AwsOrganizationsService {
 async discover(context:AwsAccountContext,force=false){const key=`organisations:${context.accountId}`;if(!force){const hit=cache.get<any>(key);if(hit)return {...hit,cacheStatus:'HIT'}}const client=awsConnectionBroker.getOrganisationClient(context);const organisation=(await client.send(new DescribeOrganizationCommand({}))).Organization;const roots=(await this.paginate<Root>(token=>client.send(new ListRootsCommand({NextToken:token})),result=>result.Roots??[])).items;const ous:any[]=[];for(const root of roots)await this.walkOus(client,root.Id!,undefined,`/${root.Name??'Root'}`,ous);const accounts=(await this.paginate<Account>(token=>client.send(new ListAccountsCommand({NextToken:token})),result=>result.Accounts??[])).items;const placements:Record<string,string|undefined>={};for(const account of accounts){const parents=await client.send(new ListParentsCommand({ChildId:account.Id}));placements[account.Id!]=parents.Parents?.[0]?.Id}const result={organisation:{id:organisation?.Id,arn:organisation?.Arn,featureSet:organisation?.FeatureSet,managementAccountId:organisation?.MasterAccountId},roots,organisationalUnits:ous,accounts:accounts.map(account=>this.account(account,placements[account.Id!])),lastSynchronisedAt:new Date().toISOString(),cacheStatus:'MISS'};cache.set(key,result,5*60_000);return result}
 private async walkOus(client:ReturnType<typeof awsConnectionBroker.getOrganisationClient>,parentId:string,parentOuId:string|undefined,path:string,output:any[]){let token:undefined|string;do{const result=await client.send(new ListOrganizationalUnitsForParentCommand({ParentId:parentId,NextToken:token}));for(const ou of result.OrganizationalUnits??[]){const entry={ouId:ou.Id,name:ou.Name,parentOuId,fullPath:`${path}/${ou.Name}`};output.push(entry);await this.walkOus(client,ou.Id!,ou.Id,entry.fullPath,output)}token=result.NextToken}while(token)}
 private async paginate<T>(load:(token?:string)=>Promise<{NextToken?:string}>,items:(result:any)=>T[]){const output:T[]=[];let token:undefined|string;do{const result=await load(token);output.push(...items(result));token=result.NextToken}while(token);return {items:output}}
 private account(account:Account,parentId?:string){return {accountId:account.Id,name:account.Name,email:account.Email,status:account.Status,parentId}}
}
