import { PrismaClient,Priority,RequestStatus,UserRole,UserStatus,type Organization } from '@prisma/client';
import bcrypt from 'bcryptjs';
const prisma=new PrismaClient();
const people=['Maya Chen','Daniel Okafor','Priya Nair','Liam Wilson','Sophia Martinez','Noah Williams','Amara Ndlovu','Owen Hughes','Ava Robinson','Ethan Brown'];
const departments=['Platform Engineering','Finance Technology','Data & Analytics','Security','Cloud Operations'];
const defs=[['S3','Bucket','finance-reports'],['EC2','Instance','payments-api'],['RDS','Database','customer-ledger'],['Lambda','Function','invoice-processor'],['IAM','Role','analytics-reader'],['CloudWatch','Log group','production-api'],['WAF','Web ACL','public-edge'],['VPC','VPC','core-network'],['CloudFront','Distribution','customer-portal'],['Route53','Hosted zone','acme.io'],['EKS','Cluster','platform-prod'],['ECS','Service','billing-worker'],['Secrets Manager','Secret','stripe-api-key'],['KMS','Key','finance-master'],['SNS','Topic','security-alerts'],['SQS','Queue','order-events'],['API Gateway','API','partner-api']] as const;
async function main(){
 await prisma.notification.deleteMany();await prisma.auditLog.deleteMany();await prisma.provisioningJob.deleteMany();await prisma.approval.deleteMany();await prisma.requestResource.deleteMany();await prisma.policy.deleteMany();await prisma.accessRequest.deleteMany();await prisma.resource.deleteMany();await prisma.awsAccount.deleteMany();await prisma.user.deleteMany();await prisma.approvalChain.deleteMany();await prisma.organization.deleteMany();
 const orgDefs=[['Acme Financial Group','acme','Enterprise','Global'],['Northstar Health','northstar','Enterprise','United States'],['Meridian Retail','meridian','Business','Europe']] as const;
 const orgs:Organization[]=[];for(const o of orgDefs)orgs.push(await prisma.organization.create({data:{name:o[0],slug:o[1],plan:o[2],region:o[3],settings:{provisioningEnabled:false,autoExpiration:true}}}));
 const passwordHash=await bcrypt.hash('permissionhub',12),allUsers=[];for(let i=0;i<50;i++){const org=orgs[i<35?0:i<44?1:2]!;const user=await prisma.user.create({data:{organizationId:org.id,name:people[i%people.length]!,email:`user${i+1}@${org.slug}.example`,passwordHash,role:[UserRole.ENGINEER,UserRole.MANAGER,UserRole.ADMINISTRATOR,UserRole.AUDITOR,UserRole.VIEWER][i%5]!,department:departments[i%departments.length]!,status:i%17===0?UserStatus.INVITED:UserStatus.ACTIVE,lastActiveAt:new Date(Date.now()-i*60000)}});allUsers.push(user)}
 const accounts=[];for(let oi=0;oi<orgs.length;oi++)for(let i=0;i<3;i++)accounts.push(await prisma.awsAccount.create({data:{organizationId:orgs[oi]!.id,accountId:`82910463${oi}${i}1`,name:['Production','Shared Services','Development'][i]!,environment:['Production','Shared','Development'][i]!,regions:['us-east-1','us-west-2','eu-west-1','af-south-1'],lastSyncAt:new Date()}}));
 const acmeAccounts=accounts.filter(x=>x.organizationId===orgs[0]!.id),resources=[];for(let i=0;i<500;i++){const d=defs[i%defs.length]!,region=['us-east-1','us-west-2','eu-west-1','af-south-1'][i%4]!,account=acmeAccounts[i%3]!;resources.push(await prisma.resource.create({data:{organizationId:orgs[0]!.id,awsAccountId:account.id,service:d[0],resourceType:d[1],name:`${d[2]}-${i+1}`,arn:`arn:aws:${d[0].toLowerCase().replace(' ','-')}:${region}:${account.accountId}:${d[1].toLowerCase().replace(' ','-')}/${d[2]}-${i+1}`,region,status:i%19===0?'Stopped':'Active',environment:account.environment,risk:i%11===0?'HIGH':i%4===0?'MEDIUM':'LOW',tags:{Owner:departments[i%departments.length],CostCenter:`CC-${1200+i%40}`,DataClass:i%7===0?'Restricted':'Internal'}}}))}
 const acmeUsers=allUsers.filter(x=>x.organizationId===orgs[0]!.id),requests=[];for(let i=0;i<100;i++){const requester=acmeUsers[i%acmeUsers.length]!,manager=acmeUsers.find((x,j)=>x.role===UserRole.MANAGER&&j>=i%10)??acmeUsers[1]!,resource=resources[(i*3)%resources.length]!;const request=await prisma.accessRequest.create({data:{displayId:`AR-2026-${String(1842-i).padStart(5,'0')}`,organizationId:orgs[0]!.id,requesterId:requester.id,managerId:manager.id,awsAccountId:resource.awsAccountId,title:['Read access to Finance Reports','Production database diagnostics','Invoke invoice processor','Assume analytics reader role'][i%4]!,justification:'Approved operational work requires temporary, least-privilege access to this cloud resource.',durationMinutes:[480,10080,43200,129600][i%4]!,priority:[Priority.LOW,Priority.MEDIUM,Priority.HIGH,Priority.CRITICAL][i%4]!,status:[RequestStatus.PENDING,RequestStatus.APPROVED,RequestStatus.REJECTED,RequestStatus.PROVISIONED,RequestStatus.MORE_INFO][i%5]!,ticketNumber:`JIRA-${8200+i}`,requestedPermissions:{bundle:i%3===0?'Read only':'Operator'},submittedAt:new Date(Date.now()-i*3600000),resources:{create:{resourceId:resource.id,permissions:i%3===0?['Read only']:['Operator']}}}});requests.push(request);await prisma.approval.create({data:{requestId:request.id,approverId:manager.id,step:1,decision:request.status===RequestStatus.PENDING?'PENDING':request.status===RequestStatus.REJECTED?'REJECTED':'APPROVED',comment:'Reviewed against least-privilege policy.',decidedAt:request.status===RequestStatus.PENDING?null:new Date()}})}
 for(let i=0;i<200;i++)await prisma.auditLog.create({data:{organizationId:orgs[0]!.id,userId:acmeUsers[i%acmeUsers.length]!.id,action:['ACCESS_REQUEST_SUBMITTED','REQUEST_APPROVED','POLICY_GENERATED','ACCESS_PROVISIONED','USER_ROLE_UPDATED','RESOURCE_DISCOVERED'][i%6]!,entityType:i%2?'AccessRequest':'Resource',entityId:i%2?requests[i%requests.length]!.id:resources[i%resources.length]!.id,ipAddress:`10.42.${i%8}.${14+i}`,outcome:i%19===0?'WARNING':'SUCCESS',oldValue:i%5===0?{status:'PENDING'}:undefined,newValue:{status:'APPROVED'},createdAt:new Date(Date.now()-i*1200000)}});
 for(const org of orgs)await prisma.approvalChain.create({data:{organizationId:org.id,name:'Standard cloud access',description:'Manager approval with security escalation for high-risk access.',conditions:{priority:['LOW','MEDIUM','HIGH']},steps:[{step:1,role:'MANAGER'},{step:2,role:'ADMINISTRATOR',when:'riskScore >= 70'}]}});
 console.log(`Seeded ${orgs.length} organizations, ${allUsers.length} users, ${resources.length} AWS resources, ${requests.length} requests, and 200 audit events.`)
}
main().catch(e=>{console.error(e);process.exit(1)}).finally(()=>prisma.$disconnect());
