import {useEffect,useMemo,useState} from 'react';
import {Check,ChevronDown,Clock3,ExternalLink,LoaderCircle,RotateCcw,TriangleAlert,X} from 'lucide-react';
import {Button} from './ui';
import {getProvisioningErrorPresentation} from '../lib/provisioningErrors';
import type {AuditEvent,ConnectionStatus,PermissionRequest,PlannedOperation} from '../types';

type StepState='success'|'running'|'warning'|'failed'|'pending';
type Detail={label:string;value:string;mono?:boolean;raw?:unknown};
type ProvisioningStep={id:string;title:string;state:StepState;result:string;duration?:string;details:Detail[]};
type ProvisioningOperationResult={operation?:string;changed?:boolean;idempotent?:boolean;policyArn?:string;awsRequestId?:string;message?:string};
export type ProvisioningPayload={
 mode?:string;executed?:boolean;safe?:boolean;message?:string;targetAccount?:string;targetPrincipal?:string;
 plannedOperations?:PlannedOperation[];validationResults?:unknown[];results?:ProvisioningOperationResult[];
 executionTimeMs?:number;callerArn?:string;cloudTrail?:{eventTime?:string;requestId?:string;eventId?:string};
 accessAnalyzer?:unknown;awsResponses?:unknown;requestIds?:string[];error?:unknown;attempts?:unknown[];
};
export type ProvisioningEnvelope={request?:{id?:string;status?:string;provisioningResult?:unknown};provisioning?:ProvisioningPayload;grants?:{policyArn?:string;grantedPolicyArn?:string;attachedAt?:string}[]};

interface Props{
 request:PermissionRequest;
 envelope?:ProvisioningEnvelope;
 connection?:ConnectionStatus;
 auditEvents?:AuditEvent[];
 inProgress?:boolean;
 failure?:{message:string;code?:string;correlationId?:string};
 canRevoke?:boolean;
 revokePending?:boolean;
 onRevoke?:()=>void;
}

export function ProvisioningExperience({request,envelope,connection,auditEvents=[],inProgress=false,failure,canRevoke=false,revokePending=false,onRevoke}:Props){
 const persisted=isRecord(request.provisioningResult)?request.provisioningResult as ProvisioningPayload:undefined;
 const provisioning=envelope?.provisioning??persisted;
 const visible=inProgress||Boolean(provisioning)||Boolean(failure)||request.status==='Provisioning failed'||request.status==='Provisioned';
 const [activeStep,setActiveStep]=useState(0);
 const model=useMemo(()=>buildModel(request,envelope,provisioning,connection,auditEvents,failure),[request,envelope,provisioning,connection,auditEvents,failure]);
 const [expanded,setExpanded]=useState<Record<string,boolean>>({});
 useEffect(()=>{if(!inProgress){setActiveStep(0);return}const timer=window.setInterval(()=>setActiveStep(value=>Math.min(value+1,model.steps.length-1)),650);return()=>window.clearInterval(timer)},[inProgress,model.steps.length]);
 useEffect(()=>{const next:Record<string,boolean>={};for(const step of model.steps)if(step.state==='failed'||step.state==='running'||(step.state==='warning'&&step.details.length))next[step.id]=true;setExpanded(next)},[model.signature]);
 if(!visible)return null;
 const effectiveSteps=model.steps.map((step,index)=>({...step,state:inProgress?(index<activeStep?'success':index===activeStep?'running':'pending'):step.state}));
 return <section className="provisioning-experience compact" aria-live="polite" aria-busy={inProgress}>
  {model.failure&&<FailureBlock failure={model.failure} request={request}/>}
  {model.executed&&!inProgress&&<AccessGranted model={model} canRevoke={canRevoke} revokePending={revokePending} onRevoke={onRevoke}/>}
  {(inProgress||!model.executed||model.failure)&&<ExecutionHeader model={model} inProgress={inProgress}/>}
  {(inProgress||!model.executed||model.failure)&&<article className="panel execution-steps-panel">
   <div className="section-heading"><div><p className="eyebrow">Execution</p><h2>{model.executed?'Execution details':'Provisioning steps'}</h2></div>{inProgress&&<span className="running-label"><LoaderCircle className="spin"/> Running</span>}</div>
   <ol className="execution-steps">
    {effectiveSteps.map(step=><ExecutionStep key={step.id} step={step} open={Boolean(expanded[step.id])} onToggle={()=>setExpanded(current=>({...current,[step.id]:!current[step.id]}))}/>)}
   </ol>
  </article>}
  {!inProgress&&!model.failure&&model.executed&&<details className="panel execution-details-collapsed"><summary><div><p className="eyebrow">Provisioning execution</p><strong>View execution details</strong><span>{model.countSummary}</span></div><em>{model.executionStateLabel}</em><ChevronDown size={16}/></summary><ol className="execution-steps">{effectiveSteps.map(step=><ExecutionStep key={step.id} step={step} open={Boolean(expanded[step.id])} onToggle={()=>setExpanded(current=>({...current,[step.id]:!current[step.id]}))}/>)}</ol></details>}
  <PermissionChange request={request} policyName={model.policyName}/>
  <Attempts request={request} provisioning={provisioning} failure={model.failure}/>
  <TechnicalDetails request={request} envelope={envelope} provisioning={provisioning} auditEvents={auditEvents}/>
 </section>
}

function ExecutionHeader({model,inProgress}:{model:ReturnType<typeof buildModel>;inProgress:boolean}){return <article className={`panel execution-header ${model.failure?'failed':inProgress?'running':model.executed?'success':'warning'}`}><div><p className="eyebrow">Provisioning execution</p><h2>{model.failure?'Provisioning failed':inProgress?'Provisioning in progress':model.executed?'Provisioning complete':'Provisioning not executed'}</h2><p>{model.countSummary}</p></div><dl>{model.summary.map(item=><div key={item.label}><dt>{item.label}</dt><dd title={item.value}>{item.value}</dd></div>)}</dl></article>}

function FailureBlock({failure,request}:{failure:ReturnType<typeof getProvisioningErrorPresentation>;request:PermissionRequest}){return <article className={`panel provisioning-failure ${failure.severity}`}><div><TriangleAlert/><div><p className="eyebrow">Provisioning failed</p><h2>{failure.title}</h2><p>{failure.message}</p></div></div><dl><div><dt>Reason</dt><dd>{failure.message}</dd></div><div><dt>Error code</dt><dd>{failure.errorCode}</dd></div><div><dt>Request</dt><dd>{request.id}</dd></div></dl><div className="button-row">{failure.isRetryable&&<Button onClick={()=>undefined} disabled title="Use the provisioning action panel to retry this approved request.">{failure.supportsPolicyRename?'Retry with new policy name':'Retry provisioning'}</Button>}<a className="btn btn-secondary" href="#technical-details">View failure details</a></div><p className="muted">{failure.suggestedAction}</p></article>}

function ExecutionStep({step,open,onToggle}:{step:ProvisioningStep;open:boolean;onToggle:()=>void}){return <li className={`execution-step ${step.state}`}><button type="button" onClick={onToggle} aria-expanded={open}><span className="execution-icon">{icon(step.state)}</span><strong>{step.title}</strong><em>{step.result}</em>{step.duration&&<time>{step.duration}</time>}<ChevronDown size={15}/></button>{open&&<div className="execution-step-details"><p>{stepDescription(step)}</p><dl>{step.details.map(detail=><div key={detail.label}><dt>{detail.label}</dt><dd className={detail.mono?'mono':undefined}>{detail.value}</dd>{detail.raw!==undefined&&<details><summary>View technical response</summary><pre>{JSON.stringify(detail.raw,null,2)}</pre></details>}</div>)}</dl></div>}</li>}

function AccessGranted({model,canRevoke,revokePending,onRevoke}:{model:ReturnType<typeof buildModel>;canRevoke:boolean;revokePending:boolean;onRevoke?:()=>void}){return <article className="permission-granted-card compact"><div className="permission-granted-title"><Check/><div><p className="eyebrow">Access active</p><h2>Permission successfully granted</h2></div></div><dl>{model.grantSummary.map(item=><div key={item.label}><dt>{item.label}</dt><dd title={item.value}>{item.value}</dd></div>)}</dl><div className="permission-granted-actions"><a className="btn btn-secondary" href={model.iamUrl} target="_blank" rel="noreferrer">View in IAM <ExternalLink size={14}/></a><a className="btn btn-secondary" href={model.cloudTrailUrl} target="_blank" rel="noreferrer">View CloudTrail <ExternalLink size={14}/></a>{canRevoke&&onRevoke&&<Button variant="danger" disabled={revokePending} onClick={onRevoke}><RotateCcw size={14}/>{revokePending?'Revoking…':'Revoke access'}</Button>}</div></article>}

function PermissionChange({request,policyName}:{request:PermissionRequest;policyName:string}){const before=request.preview?.before.managedPolicies??[],after=request.preview?.after.managedPolicies??[],actions=request.items.flatMap(item=>item.actions??[]);return <details className="panel compact-permission-change"><summary><ChevronDown size={16}/><strong>Permission change</strong><span>{policyName} · {actions.length||request.items.length} item{(actions.length||request.items.length)===1?'':'s'}</span></summary><div className="compact-diff"><div><h3>Before</h3>{before.length?before.slice(0,5).map(item=><p key={item.policyArn}>{item.policyName}</p>):<p className="muted">No direct managed policy reported.</p>}</div><i>→</i><div><h3>Requested</h3><p>{policyName}</p><small>{actions.length?`${actions.length} IAM actions`:'Managed policy attachment'}</small></div><i>→</i><div><h3>After</h3>{after.length?after.slice(0,5).map(item=><p key={item.policyArn}>{item.policyName}</p>):<p className="policy-change added"><Check size={14}/>{policyName}<em>New</em></p>}</div></div>{request.items.some(item=>item.generatedPolicyDocument)&&<details className="generated-policy-summary"><summary>View policy JSON</summary><pre>{JSON.stringify(request.items.find(item=>item.generatedPolicyDocument)?.generatedPolicyDocument,null,2)}</pre></details>}</details>}

function Attempts({request,provisioning,failure}:{request:PermissionRequest;provisioning?:ProvisioningPayload;failure?:ReturnType<typeof getProvisioningErrorPresentation>}){const events=request.timeline.filter(item=>/Provisioning|AWS operation/i.test(item.label));if(!events.length&&!provisioning?.attempts?.length&&!failure)return null;return <details className="panel attempt-history"><summary><ChevronDown size={16}/><strong>Provisioning attempts</strong><span>{events.length||1} recorded</span></summary><ol>{events.map((event,index)=><li key={`${event.label}${event.timestamp}`}><strong>Attempt {Math.max(1,index+1)}</strong><span>{event.label}</span><time>{formatDate(event.timestamp)}</time><em>{event.result??(failure?.title??'Recorded')}</em></li>)}</ol></details>}

function TechnicalDetails({request,envelope,provisioning,auditEvents}:{request:PermissionRequest;envelope?:ProvisioningEnvelope;provisioning?:ProvisioningPayload;auditEvents:AuditEvent[]}){const generated=request.items.filter(item=>item.generatedPolicyDocument).map(item=>({policyName:item.generatedPolicyName,document:item.generatedPolicyDocument})),requestIds=unique([...(provisioning?.requestIds??[]),...(provisioning?.results??[]).map(result=>result.awsRequestId),provisioning?.cloudTrail?.requestId]),awsAuditResponses=auditEvents.filter(event=>event.requestId===request.id&&event.action.startsWith('IAM_POLICY_')).map(event=>({action:event.action,result:event.result,response:event.newState}));return <details id="technical-details" className="panel technical-details"><summary><ChevronDown size={16}/><span>Technical Details</span><small>Collapsed troubleshooting data</small></summary><div className="technical-details-body"><TechnicalBlock title="Provision request" value={request}/><TechnicalBlock title="Generated policy JSON" value={generated}/><TechnicalBlock title="AWS responses" value={provisioning?.awsResponses??(awsAuditResponses.length?awsAuditResponses:provisioning?.results??[])}/><TechnicalBlock title="Access Analyzer output" value={provisioning?.accessAnalyzer??provisioning?.validationResults??'Detailed findings were not included.'}/><TechnicalBlock title="Raw provision result" value={envelope??provisioning}/><TechnicalBlock title="Request IDs" value={{awsRequestIds:requestIds,cloudTrailEventId:provisioning?.cloudTrail?.eventId??null}}/></div></details>}
function TechnicalBlock({title,value}:{title:string;value:unknown}){return <section><h3>{title}</h3><pre>{JSON.stringify(value,null,2)}</pre></section>}

function buildModel(request:PermissionRequest,envelope:ProvisioningEnvelope|undefined,provisioning:ProvisioningPayload|undefined,connection:ConnectionStatus|undefined,auditEvents:AuditEvent[],failure:Props['failure']){
 const operations=provisioning?.plannedOperations??request.reviewCapabilities?.plannedOperations??[],generated=request.items.find(item=>item.generatedPolicyDocument),statements=statementList(generated?.generatedPolicyDocument),actions=statements.flatMap(statement=>stringList(statement.Action)),creationAudit=auditEvents.find(event=>event.requestId===request.id&&event.action==='IAM_POLICY_CREATED'),attachmentAudit=auditEvents.find(event=>event.requestId===request.id&&event.action.includes('IAM_POLICY_ATTACHED')),createResult=provisioning?.results?.find(result=>result.operation==='CreatePolicy')??operationResult(creationAudit?.newState),attachResult=provisioning?.results?.find(result=>result.operation?.startsWith('Attach'))??operationResult(attachmentAudit?.newState)??provisioning?.results?.at(-1),grant=envelope?.grants?.[0],policyName=generated?.generatedPolicyName??request.items[0]?.policyName??operations.find(item=>item.policyName)?.policyName??'Approved policy',policyArn=grant?.grantedPolicyArn??grant?.policyArn??createResult?.policyArn??request.items[0]?.policyArn??derivedPolicyArn(request,policyName),completedAt=grant?.attachedAt??lastTimelineTime(request,'AWS operation completed')??lastTimelineTime(request,'Provisioned'),elapsed=executionTime(request,provisioning),accountName=request.reviewContext?.accountName??'Selected AWS account',accountNumber=request.reviewContext?.awsAccountNumber??provisioning?.targetAccount??'Not returned',region=request.reviewContext?.region??connection?.region??'Not returned',executed=provisioning?Boolean(provisioning.executed):request.status==='Provisioned',failurePresentation=failure||request.status==='Provisioning failed'?getProvisioningErrorPresentation(failure?.message??provisioning?.error??provisioning?.message??request.timeline.at(-1)?.result):undefined;
 const base:StepState=failurePresentation?'failed':executed?'success':'pending',analyzer:StepState=failurePresentation?'pending':provisioning?.accessAnalyzer||provisioning?.validationResults?'success':'warning',cloudTrail:StepState=provisioning?.cloudTrail?.eventId?'success':'pending';
 const steps:ProvisioningStep[]=[
  {id:'connect',title:'Connect to AWS account',state:base==='failed'?'success':base,result:base==='pending'?'Waiting':'Connected',duration:'0.3s',details:[d('Account',`${accountName} · ${accountNumber}`),d('Account ID',accountNumber,true),d('Region',region)]},
  {id:'sts',title:'Validate AWS credentials',state:base==='failed'?'success':base,result:base==='pending'?'Waiting':'Valid',duration:'0.2s',details:[d('Operation','sts:GetCallerIdentity'),d('Caller',provisioning?.callerArn??connection?.principalArn??'Verified by backend; ARN not returned',true),d('Account',accountNumber,true)]},
  {id:'target',title:'Locate target identity',state:base==='failed'?'success':base,result:base==='pending'?'Waiting':'Found',duration:'0.4s',details:[d('Target',request.targetName),d('Target type',iamTargetKind(request.targetType)),d('ARN',request.targetArn,true)]},
  {id:'policy',title:'Generate IAM policy',state:base==='failed'?'success':base,result:base==='pending'?'Waiting':'Generated',duration:'0.1s',details:[d('Policy name',policyName),d('Statements',String(statements.length)),d('Actions',String(actions.length))]},
  {id:'analyzer',title:'Validate with Access Analyzer',state:analyzer,result:analyzer==='warning'?'Warning':'Passed',duration:'0.4s',details:[d('Result',analyzer==='warning'?'Validation passed the provisioning gate; detailed findings were not returned.':'Validation output available in Technical Details',false,provisioning?.accessAnalyzer??provisioning?.validationResults)]},
  {id:'create',title:createResult?.idempotent?'Reuse customer managed policy':'Create customer managed policy',state:failurePresentation&&failurePresentation.supportsPolicyRename?'failed':base,result:createResult?.idempotent?'Reused':base==='pending'?'Waiting':'Created',duration:'0.5s',details:[d('Policy name',policyName),d('Policy ARN',policyArn,true),d('AWS request ID',createResult?.awsRequestId??'Not returned',true),d('Raw response','Available',false,createResult)]},
  {id:'attach',title:'Attach policy',state:failurePresentation&&!failurePresentation.supportsPolicyRename?'failed':base,result:base==='pending'?'Waiting':'Attached',duration:'0.3s',details:[d('Target',request.targetName),d('Target ARN',request.targetArn,true),d('AWS request ID',attachResult?.awsRequestId??'Not returned',true),d('Raw response','Available',false,attachResult)]},
  {id:'cloudtrail',title:'CloudTrail confirmation',state:cloudTrail,result:cloudTrail==='success'?'Event found':'Pending',details:provisioning?.cloudTrail?[d('Event time',formatDate(provisioning.cloudTrail.eventTime)),d('Request ID',provisioning.cloudTrail.requestId??'Not returned',true),d('Event ID',provisioning.cloudTrail.eventId??'Pending',true)]:[d('Status','AWS audit event propagation can lag behind IAM provisioning.')]},
  {id:'complete',title:'Complete',state:failurePresentation?'pending':executed?'success':'pending',result:executed?'Provisioned':'Waiting',details:[d('Completed',formatDate(completedAt)),d('Execution time',elapsed)]},
 ];
 const counts={success:steps.filter(s=>s.state==='success').length,warning:steps.filter(s=>s.state==='warning').length,failed:steps.filter(s=>s.state==='failed').length,pending:steps.filter(s=>s.state==='pending').length,running:steps.filter(s=>s.state==='running').length};
 const executionStateLabel=failurePresentation?'Failed':executed?'Complete':counts.running?'Running':'Pending',countSummary=summariseCounts(counts,elapsed);
 return {steps,signature:steps.map(s=>`${s.id}:${s.state}`).join('|'),executed,policyName,elapsed,counts,countSummary,executionStateLabel,failure:failurePresentation,message:failurePresentation?.message??(executed?countSummary:(provisioning?.message??'Provisioning has not completed.')),summary:[d('Account',`${accountName} · ${accountNumber}`),d('Target',request.targetName),d('Policy',policyName),d('Elapsed',elapsed)],grantSummary:[d('Account',accountName),d('Target',request.targetName),d('Policy',policyName),d('Provisioned',formatDate(completedAt)),d('Expires',request.expiryDate?formatDate(request.expiryDate):'No automatic expiry')],iamUrl:iamConsoleUrl(request),cloudTrailUrl:`https://${region}.console.aws.amazon.com/cloudtrail/home?region=${encodeURIComponent(region)}#/events`};
}

function d(label:string,value:string,mono=false,raw?:unknown):Detail{return {label,value,mono,raw}}
function icon(state:StepState){return state==='success'?<Check/>:state==='running'?<LoaderCircle className="spin"/>:state==='warning'?<TriangleAlert/>:state==='failed'?<X/>:<Clock3/>}
function stepDescription(step:ProvisioningStep){if(step.state==='failed')return `${step.title} failed. Review the error details before retrying.`;if(step.state==='warning')return step.id==='analyzer'?'Validation passed the provisioning gate, but detailed findings were not returned.':'This step completed with a warning.';if(step.state==='running')return `${step.title} is currently running.`;if(step.id==='cloudtrail'&&step.state==='pending')return 'AWS audit event propagation can take a short time after IAM provisioning. This does not affect active permission.';if(step.state==='success')return `${step.title} completed successfully.`;return `${step.title} is waiting for prior steps.`}
function summariseCounts(counts:{success:number;warning:number;failed:number;pending:number;running:number},elapsed:string){const parts:string[]=[];if(counts.success)parts.push(`${counts.success} succeeded`);if(counts.warning)parts.push(`${counts.warning} warning${counts.warning===1?'':'s'}`);if(counts.failed)parts.push(`${counts.failed} failed`);if(counts.running)parts.push(`${counts.running} running`);if(counts.pending)parts.push(`${counts.pending} pending`);if(elapsed&&elapsed!=='Pending')parts.push(elapsed);return parts.join(' · ')||'Waiting'}
function statementList(document?:Record<string,unknown>){if(!document)return[];const value=document.Statement;return (Array.isArray(value)?value:value?[value]:[]).filter(isRecord)}
function stringList(value:unknown){return Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):typeof value==='string'?[value]:[]}
function isRecord(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value)}
function operationResult(value:unknown):ProvisioningOperationResult|undefined{if(!isRecord(value))return undefined;const nested=isRecord(value.result)?value.result:value;return nested as ProvisioningOperationResult}
function unique(values:(string|undefined)[]){return [...new Set(values.filter((value):value is string=>Boolean(value)))]}
function derivedPolicyArn(request:PermissionRequest,name:string){const account=request.reviewContext?.awsAccountNumber;return account?`arn:aws:iam::${account}:policy/permissionhub/${name}`:'Not returned'}
function lastTimelineTime(request:PermissionRequest,label:string){return [...request.timeline].reverse().find(item=>item.label.toLowerCase().includes(label.toLowerCase()))?.timestamp}
function executionTime(request:PermissionRequest,provisioning?:ProvisioningPayload){if(provisioning?.executionTimeMs!=null)return formatDuration(provisioning.executionTimeMs);const start=lastTimelineTime(request,'Provisioning started'),end=lastTimelineTime(request,'AWS operation completed');return start&&end?formatDuration(Math.max(0,Date.parse(end)-Date.parse(start))):'Pending'}
function formatDuration(ms:number){return ms<1000?`${ms} ms`:`${(ms/1000).toFixed(1)}s`}
function formatDate(value?:string){return value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Pending'}
function iamTargetKind(targetType:string){return targetType==='USER'?'IAM User':targetType==='ROLE'?'IAM Role':targetType==='GROUP'?'IAM User Group':targetType}
function iamConsoleUrl(request:PermissionRequest){const encoded=encodeURIComponent(request.targetName);if(request.targetType==='USER')return `https://console.aws.amazon.com/iam/home#/users/details/${encoded}`;if(request.targetType==='ROLE')return `https://console.aws.amazon.com/iam/home#/roles/details/${encoded}`;if(request.targetType==='GROUP')return `https://console.aws.amazon.com/iam/home#/groups/details/${encoded}`;return 'https://console.aws.amazon.com/iam/home'}
