import {renderToStaticMarkup} from 'react-dom/server';
import {describe,expect,it} from 'vitest';
import {ProvisioningExperience,type ProvisioningEnvelope} from './ProvisioningExperience';
import type {PermissionRequest} from '../types';

const request:PermissionRequest={
 id:'PR-1009',title:'Read finance exports',requester:'Engineer',approver:'Security reviewer',targetType:'USER',targetName:'Yagi-test-ui',targetArn:'arn:aws:iam::143671530412:user/Yagi-test-ui',
 items:[{mode:'SPECIFIC_ACTIONS',generatedPolicyName:'PH-PR-1009-1',actions:['s3:ListBucket'],generatedPolicyDocument:{Version:'2012-10-17',Statement:[{Effect:'Allow',Action:['s3:ListBucket'],Resource:'*'}]}}],scope:{type:'ALL',resources:[]},duration:'1 day',startDate:'2026-08-04T13:37:00.000Z',expiryDate:'2026-08-05T13:37:00.000Z',priority:'Normal',justification:'Validate the provisioning experience.',status:'Provisioned',createdAt:'2026-08-04T13:30:00.000Z',submittedAt:'2026-08-04T13:31:00.000Z',timeline:[{label:'Provisioning started',timestamp:'2026-08-04T13:37:00.000Z'},{label:'AWS operation completed',timestamp:'2026-08-04T13:37:01.800Z'}],
 reviewContext:{accountName:'Disraptor Production',awsAccountNumber:'143671530412',accountType:'PRODUCTION',region:'af-south-1',connectionStatus:'CONNECTED',provisionRoleConfigured:false},preview:{estimate:true,before:{managedPolicies:[{policyName:'CloudWatchReadOnly',policyArn:'arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess'}],inlinePolicies:[],effectiveActions:'Estimated'},change:{policiesToAttach:[{policyName:'PH-PR-1009-1',actions:['s3:ListBucket']}],policiesToDetach:[],resourceScope:{type:'ALL',resources:[]}},after:{managedPolicies:[{policyName:'CloudWatchReadOnly',policyArn:'arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess'}],newlyAllowedActions:['s3:ListBucket'],riskFlags:[]},awsOperation:'CreatePolicy → AttachUserPolicy'}
};

const envelope:ProvisioningEnvelope={provisioning:{mode:'local',executed:true,plannedOperations:[{service:'iam',operation:'CreatePolicy',executed:false,policyName:'PH-PR-1009-1'},{service:'iam',operation:'AttachUserPolicy',executed:false,targetName:'Yagi-test-ui'}],results:[{operation:'AttachUserPolicy',changed:true,awsRequestId:'aws-request-123'}]},grants:[{policyArn:'arn:aws:iam::143671530412:policy/permissionhub/PH-PR-1009-1',attachedAt:'2026-08-04T13:37:01.800Z'}]};

describe('ProvisioningExperience',()=>{
 it('renders a successful timeline, permission diff and collapsed raw technical details',()=>{const html=renderToStaticMarkup(<ProvisioningExperience request={request} envelope={envelope}/>);expect(html).toContain('Provisioning Successful');expect(html).toContain('Validated AWS Credentials');expect(html).toContain('Attached Policy');expect(html).toContain('Permission Successfully Granted');expect(html).toContain('PH-PR-1009-1');expect(html).toContain('1.8 seconds');expect(html).toContain('<details class="panel technical-details">');expect(html).toContain('Raw Provision Result');expect(html).toContain('aws-request-123');expect(html).not.toContain('<details class="panel technical-details" open="">')});
 it('labels an idempotently reused policy from the response',()=>{const reused={...envelope,provisioning:{...envelope.provisioning,results:[{operation:'CreatePolicy',changed:false,idempotent:true,policyArn:'arn:aws:iam::143671530412:policy/permissionhub/PH-PR-1009-1'},{operation:'AttachUserPolicy',changed:false,idempotent:true}]}};const html=renderToStaticMarkup(<ProvisioningExperience request={request} envelope={reused}/>);expect(html).toContain('Existing policy reused');expect(html).toContain('no duplicate attachment was made')});
 it('renders running steps without claiming final success',()=>{const html=renderToStaticMarkup(<ProvisioningExperience request={{...request,status:'Pending approval',provisioningResult:undefined}} inProgress/>);expect(html).toContain('Provisioning in progress');expect(html).toContain('aria-busy="true"');expect(html).not.toContain('Permission Successfully Granted')});
 it('does not claim access was granted for a dry-run',()=>{const html=renderToStaticMarkup(<ProvisioningExperience request={request} envelope={{provisioning:{mode:'dry-run',executed:false,message:'No AWS changes were made.'}}}/>);expect(html).toContain('Provisioning Dry-run Complete');expect(html).toContain('Provisioning Not Executed');expect(html).not.toContain('Permission Successfully Granted')});
});
