import { describe,expect,it,vi } from 'vitest';
import { AwsAccountRepository,mapAwsAccount } from './aws-account.repository.js';

const row=(overrides:any={})=>({id:'account-1',tenantId:'tenant-1',accountId:'143671530412',accountName:'Existing account',accountType:'SANDBOX',environment:'sandbox',riskTier:'LOW',region:'af-south-1',connectionType:'LOCAL_DEFAULT_CREDENTIALS',connectionStatus:'PENDING',sourceType:'MANUAL',isDemo:false,readRoleArn:null,provisionRoleArn:null,externalIdSecretReference:null,connection:{id:'connection-1',connectionType:'LOCAL_DEFAULT_CREDENTIALS',connectionSource:'MANUAL',connectionStatus:'PENDING',defaultRegion:'af-south-1',provisioningStatus:'DISABLED',provisioningEnabled:false},...overrides});

describe('AWS account repository recovery queries',()=>{
 it('shows pending manual accounts on the connection page',async()=>{const findMany=vi.fn().mockResolvedValue([row()]),repo=new AwsAccountRepository({awsAccount:{findMany}});const accounts=await repo.getManualAccountsForConnectionPage('tenant-1');expect(accounts[0]).toMatchObject({connectionStatus:'PENDING',hasConnection:true});expect(findMany).toHaveBeenCalledWith(expect.objectContaining({where:{tenantId:'tenant-1',sourceType:'MANUAL',isDemo:false}}))});
 it('does not expose pending accounts to AWS operations',async()=>{const repo=new AwsAccountRepository({awsAccount:{findMany:vi.fn().mockResolvedValue([row()])}});expect(await repo.getUsableConnectedAccountsForAwsOperations('tenant-1')).toEqual([])});
 it('exposes connected manual accounts to AWS operations',async()=>{const repo=new AwsAccountRepository({awsAccount:{findMany:vi.fn().mockResolvedValue([row({connection:{...row().connection,connectionStatus:'CONNECTED'}})])}});expect(await repo.getUsableConnectedAccountsForAwsOperations('tenant-1')).toHaveLength(1)});
 it('scopes duplicate lookup to the active tenant and AWS number',async()=>{const findUnique=vi.fn().mockResolvedValue(row()),repo=new AwsAccountRepository({awsAccount:{findUnique}});await repo.findExistingForTenant('tenant-1','143671530412');expect(findUnique).toHaveBeenCalledWith(expect.objectContaining({where:{tenantId_accountId:{tenantId:'tenant-1',accountId:'143671530412'}}}))});
 it('identifies demo and legacy collisions without treating them as manual',()=>{expect(mapAwsAccount(row({sourceType:'DEMO_SEED',isDemo:true}))).toMatchObject({sourceType:'DEMO_SEED',isDemo:true})});
 it('repairs a missing connection without changing the account',async()=>{const original=row({connection:null}),create=vi.fn().mockResolvedValue({}),findFirst=vi.fn().mockResolvedValue(original),findUniqueOrThrow=vi.fn().mockResolvedValue({...original,connection:row().connection}),db:any={awsAccount:{findFirst,findUniqueOrThrow},awsAccountConnection:{create}};db.$transaction=(callback:any)=>callback(db);const repo=new AwsAccountRepository(db),repaired=await repo.repairMissingConnection('tenant-1','account-1');expect(create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({awsAccountId:'account-1',connectionSource:'MANUAL',connectionStatus:'PENDING'})}));expect(repaired.hasConnection).toBe(true)});
 it('returns an existing connected account idempotently',async()=>{const db:any={awsAccount:{findUnique:vi.fn().mockResolvedValue(row({connection:{...row().connection,connectionStatus:'CONNECTED'}}))}};db.$transaction=(callback:any)=>callback(db);const result=await new AwsAccountRepository(db).onboardManualAccount('tenant-1',{accountName:'Disraptor',awsAccountNumber:'143671530412',accountType:'PRODUCTION',defaultRegion:'af-south-1',connectionType:'LOCAL_DEFAULT_CREDENTIALS'});expect(result).toMatchObject({outcome:'EXISTING',account:{accountRecordId:'account-1',awsAccountNumber:'143671530412',connectionStatus:'CONNECTED'}})});
 it('recovers an account missing its connection in the onboarding transaction',async()=>{const missing=row({connection:null}),create=vi.fn(),findUnique=vi.fn().mockResolvedValue(missing),findUniqueOrThrow=vi.fn().mockResolvedValue({...missing,connection:row().connection}),db:any={awsAccount:{findUnique,findUniqueOrThrow},awsAccountConnection:{create}};db.$transaction=(callback:any)=>callback(db);const result=await new AwsAccountRepository(db).onboardManualAccount('tenant-1',{accountName:'Disraptor',awsAccountNumber:'143671530412',accountType:'PRODUCTION',defaultRegion:'af-south-1',connectionType:'LOCAL_DEFAULT_CREDENTIALS'});expect(result.outcome).toBe('REPAIRED');expect(create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({tenantId:'tenant-1',awsAccountId:'account-1',connectionStatus:'PENDING'})}))});
 it('re-queries and returns the winner after a Prisma P2002 race',async()=>{const db:any={awsAccount:{findUnique:vi.fn().mockResolvedValue(row())}};db.$transaction=vi.fn().mockRejectedValueOnce(Object.assign(new Error('unique'),{code:'P2002'})).mockImplementationOnce((callback:any)=>callback(db));const result=await new AwsAccountRepository(db).onboardManualAccount('tenant-1',{accountName:'Disraptor',awsAccountNumber:'143671530412',accountType:'PRODUCTION',defaultRegion:'af-south-1',connectionType:'LOCAL_DEFAULT_CREDENTIALS'});expect(result).toMatchObject({outcome:'EXISTING',prismaConflictRecovered:true,account:{accountRecordId:'account-1'}})});
});
