import { prisma } from '../config/database.js';
import { logger } from '../config/logger.js';
import { env } from '../config/env.js';
import type { AwsAccountContext,SessionUser } from '../types.js';
import { identityDomain } from './identity-domain.service.js';

export function mapAwsAccount(row:any):AwsAccountContext{
 const connection=row.connection;
 return {id:row.id,tenantId:row.tenantId,accountId:row.accountId,accountName:row.accountName,accountType:row.accountType,environment:row.environment,riskTier:row.riskTier,region:row.region,connectionType:connection?.connectionType??row.connectionType,connectionStatus:connection?.connectionStatus??'PENDING',sourceType:row.sourceType,isDemo:row.isDemo,connectionSource:connection?.connectionSource,hasConnection:Boolean(connection),readRoleArn:connection?.readRoleArn??row.readRoleArn,provisionRoleArn:connection?.provisionRoleArn??row.provisionRoleArn,externalIdSecretReference:connection?.externalIdSecretReference??row.externalIdSecretReference,provisioningStatus:connection?.provisioningStatus??'DISABLED',provisioningEnabled:connection?.provisioningEnabled??false,lastValidatedAt:connection?.lastValidatedAt?.toISOString(),lastSuccessfulReadAt:connection?.lastSuccessfulReadAt?.toISOString(),lastSuccessfulProvisionAt:connection?.lastSuccessfulProvisionAt?.toISOString(),lastErrorCode:connection?.lastErrorCode,lastErrorMessage:connection?.lastErrorMessage};
}

export class AwsAccountRepository{
 constructor(private db:any=prisma){}
 private memory(tenantId:string){return identityDomain.allAccounts().filter(account=>account.tenantId===tenantId&&account.sourceType==='MANUAL'&&!account.isDemo)}
 async getManualAccountsForConnectionPage(tenantId:string):Promise<AwsAccountContext[]>{
  if(env.NODE_ENV==='test'&&this.db===prisma)return this.memory(tenantId);
  try{const rows:any[]=await this.db.awsAccount.findMany({where:{tenantId,sourceType:'MANUAL',isDemo:false},include:{connection:true},orderBy:{accountName:'asc'}}),accounts:AwsAccountContext[]=rows.map(mapAwsAccount);identityDomain.replaceManualAccounts(tenantId,accounts);return accounts}
  catch(error){logger.debug({tenantId,error:error instanceof Error?error.message:'Database unavailable'},'Using current manual account registry');return this.memory(tenantId)}
 }
 async refreshManualAccounts(tenantId:string):Promise<AwsAccountContext[]>{return this.getManualAccountsForConnectionPage(tenantId)}
 async getManualAccountsForTenant(tenantId:string):Promise<AwsAccountContext[]>{return this.getManualAccountsForConnectionPage(tenantId)}
 async getUsableConnectedAccountsForAwsOperations(tenantId:string,user?:SessionUser):Promise<AwsAccountContext[]>{const accounts=(await this.getManualAccountsForConnectionPage(tenantId)).filter(account=>account.hasConnection&&account.connectionSource==='MANUAL'&&account.connectionStatus==='CONNECTED');return user?accounts.filter(account=>identityDomain.account(user,account.id)!==undefined):accounts}
 async getConnectedAccountsForTenant(tenantId:string){return this.getUsableConnectedAccountsForAwsOperations(tenantId)}
 async getAuthorisedAccountsForUser(user:SessionUser,tenantId:string):Promise<AwsAccountContext[]>{if(user.activeTenantId!==tenantId)return [];return this.getUsableConnectedAccountsForAwsOperations(tenantId,user)}
 async getAccountConnection(tenantId:string,accountId:string){return (await this.getManualAccountsForConnectionPage(tenantId)).find(account=>account.id===accountId||account.accountId===accountId)}
 async findExistingForTenant(tenantId:string,accountId:string){try{const row=await this.db.awsAccount.findFirst({where:{tenantId,accountId},include:{connection:true}});return row?mapAwsAccount(row):undefined}catch{return identityDomain.allAccounts().find(account=>account.tenantId===tenantId&&account.accountId===accountId)}}
 async repairMissingConnection(tenantId:string,accountId:string){const row=await this.db.awsAccount.findFirst({where:{tenantId,OR:[{id:accountId},{accountId}]},include:{connection:true}});if(!row)throw new Error('ACCOUNT_NOT_FOUND');if(row.sourceType!=='MANUAL'||row.isDemo)throw new Error('CONVERSION_REQUIRED');if(row.connection)return mapAwsAccount(row);await this.db.awsAccountConnection.create({data:{tenantId,awsAccountId:row.id,connectionType:row.connectionType==='ASSUME_ROLE'?'ASSUME_ROLE':'LOCAL_DEFAULT_CREDENTIALS',connectionSource:'MANUAL',readRoleArn:row.readRoleArn,provisionRoleArn:row.provisionRoleArn,externalIdSecretReference:row.externalIdSecretReference,defaultRegion:row.region,connectionStatus:'PENDING',provisioningStatus:'DISABLED',provisioningEnabled:false}});return mapAwsAccount(await this.db.awsAccount.findUnique({where:{id:row.id},include:{connection:true}}))}
 async convertToManual(tenantId:string,accountId:string){const row=await this.db.awsAccount.findFirst({where:{tenantId,OR:[{id:accountId},{accountId}]},include:{connection:true}});if(!row)throw new Error('ACCOUNT_NOT_FOUND');await this.db.$transaction([this.db.awsAccount.update({where:{id:row.id},data:{sourceType:'MANUAL',isDemo:false,manuallyCreatedAt:new Date(),connectionStatus:'PENDING'}}),this.db.awsAccountConnection.upsert({where:{awsAccountId:row.id},create:{tenantId,awsAccountId:row.id,connectionType:row.connection?.connectionType??(row.connectionType==='ASSUME_ROLE'?'ASSUME_ROLE':'LOCAL_DEFAULT_CREDENTIALS'),connectionSource:'MANUAL',readRoleArn:row.connection?.readRoleArn??row.readRoleArn,provisionRoleArn:row.connection?.provisionRoleArn??row.provisionRoleArn,externalIdSecretReference:row.connection?.externalIdSecretReference??row.externalIdSecretReference,defaultRegion:row.connection?.defaultRegion??row.region,connectionStatus:'PENDING',provisioningStatus:'DISABLED',provisioningEnabled:false},update:{connectionSource:'MANUAL',connectionStatus:'PENDING',lastErrorCode:null,lastErrorMessage:null}})]);return mapAwsAccount(await this.db.awsAccount.findUnique({where:{id:row.id},include:{connection:true}}))}
}
export const awsAccountRepository=new AwsAccountRepository();
