import type { Request } from 'express';
export type AppRole='REQUESTER'|'ACCOUNT_APPROVER'|'OU_ADMIN'|'SECURITY_REVIEWER'|'PROVISIONER'|'ORGANISATION_ADMIN'|'PLATFORM_ADMIN';
export type ScopeType='TENANT'|'AWS_ORGANISATION'|'ORGANISATIONAL_UNIT'|'AWS_ACCOUNT';
export type AccountType='MANAGEMENT'|'SECURITY'|'LOG_ARCHIVE'|'SHARED_SERVICES'|'NETWORK'|'PRODUCTION'|'STAGING'|'DEVELOPMENT'|'SANDBOX'|'EXTERNAL';
export interface AdminScope {scopeType:ScopeType;scopeId:string;includeDescendants:boolean;canView:boolean;canRequest:boolean;canApprove:boolean;canProvision:boolean;canRevoke:boolean;canManageConfiguration:boolean}
export interface TenantMembership {id:string;tenantId:string;tenantName:string;tenantSlug:string;role:AppRole;status:'ACTIVE'|'INVITED'|'SUSPENDED';scopes:AdminScope[]}
export interface ScopedRoleAssignment {id:string;tenantId:string;awsAccountId:string;role:AppRole}
export interface SessionUser {id:string;email:string;displayName:string;provider:string;providerSubject:string;activeTenantId?:string;activeAwsAccountRecordId?:string;/** @deprecated compatibility with older sessions */activeAccountId?:string;permissions:string[];memberships:TenantMembership[];roleAssignments?:ScopedRoleAssignment[]}
export interface AuthClaims { sub:string; organizationId:string; role:AppRole; email:string; name:string }
export interface AuthenticatedRequest extends Request { auth?:AuthClaims; sessionUser?:SessionUser; tenantId?:string; awsAccountContext?:AwsAccountContext; correlationId?:string }
export type AwsConnectionType='ORGANISATION_MEMBER'|'STANDALONE'|'EXTERNAL_CUSTOMER'|'LOCAL_DEVELOPMENT'|'LOCAL_DEFAULT_CREDENTIALS'|'ACCESS_KEYS'|'DEFAULT_CHAIN'|'ASSUME_ROLE'|'EXTERNAL_ROLE';
export type AwsAccountSource='MANUAL'|'ORGANISATION_DISCOVERY'|'DEMO_SEED'|'MIGRATION'|'LEGACY';
export type AwsConnectionStatus='PENDING'|'CONNECTED'|'DEGRADED'|'ERROR'|'DISABLED'|'DISCONNECTED'|'REPAIR_REQUIRED';
export interface AwsAccountContext {id:string;accountRecordId?:string;tenantId:string;organisationId?:string;ouId?:string;ouPath?:string;accountId:string;awsAccountNumber?:string;accountName:string;accountType:AccountType;environment:string;riskTier:string;region:string;connectionType:AwsConnectionType;connectionStatus:AwsConnectionStatus;sourceType?:AwsAccountSource;isDemo?:boolean;connectionSource?:AwsAccountSource;hasConnection?:boolean;executionRoleArn?:string;readRoleArn?:string;provisionRoleArn?:string;externalIdSecretReference?:string;credentialConfigured?:boolean;accessKeyIdMasked?:string;organisationDiscoveryRoleArn?:string;organisationsRegion?:string;provisioningEnabled?:boolean;provisioningStatus?:AwsConnectionStatus;provisionRoleStatus?:string;provisionRoleLastValidatedAt?:string;provisionRoleLastError?:string;lastValidatedAt?:string;lastSuccessfulReadAt?:string;lastSuccessfulProvisionAt?:string;lastErrorCode?:string;lastErrorMessage?:string}
export type TargetType='USER'|'ROLE'|'GROUP';
export type PolicyType='AWS_MANAGED'|'CUSTOMER_MANAGED';
export type RiskLevel='Low'|'Moderate'|'High'|'Critical';
export type RequestStatus='Draft'|'Pending approval'|'More information required'|'Approved'|'Rejected'|'Provisioning'|'Provisioned'|'Provisioning failed'|'Expired'|'Revoked';
export type ProvisioningMode='MOCK'|'SIMULATE'|'LIVE';
export interface DiscoveredResource { id:string;name:string;service:'S3'|'RDS'|'Lambda';type:string;region:string;arn:string;status:string;tags:Record<string,string> }
export interface IamAttachedPolicy { policyName:string;policyArn:string }
export interface IamIdentity { id:string;type:TargetType;name:string;arn:string;path:string;createdAt:string;description?:string;passwordEnabled?:boolean;maxSessionDuration?:number;attachedPolicies:IamAttachedPolicy[];inlinePolicies:string[];permissionBoundary?:string;tags?:Record<string,string>;trustPolicy?:unknown;serviceLinked?:boolean;users?:{userName:string;arn?:string}[];userCount?:number }
export interface RiskAnalysis { level:RiskLevel;flags:string[];services:string[];accessLevels:string[] }
export interface IamPolicySummary { policyName:string;arn:string;policyId?:string;path?:string;description?:string;type:PolicyType;currentVersion:string;createdAt:string;updatedAt:string;attachmentCount:number;permissionsBoundaryUsageCount?:number;isAttachable?:boolean;services:string[];accessLevels:string[];risk:RiskAnalysis;deprecated:boolean }
export interface IamPolicyDetail extends IamPolicySummary { document:Record<string,unknown>;statements:unknown[];actions:string[];resources:string[];conditions:unknown[];attachedUsers:string[];attachedRoles:string[];attachedGroups:string[];observations:string[] }
export interface PermissionRequestItem { mode:'MANAGED_POLICY'|'SPECIFIC_ACTIONS';operation?:'ATTACH'|'DETACH'|'UPDATE';policyArn?:string;policyName?:string;generatedPolicyName?:string;requestedPolicyName?:string;actions?:string[];generatedPolicyDocument?:Record<string,unknown> }
export interface GroupMemberRequest { userName:string;userArn?:string;operation?:'ADD'|'REMOVE';alreadyMember?:boolean;createUser?:boolean }
export interface PermissionRequest { id:string;title:string;tenantId?:string;awsOrganisationId?:string;ouId?:string;awsAccountId?:string;accountType?:AccountType;requesterUserId?:string;requester:string;approver:string;approverUserId?:string;targetSubjectType?:TargetType;targetType:TargetType;targetName:string;targetArn:string;group?:{mode:'CREATE'|'EXISTING';name:string;path?:string;createdByPermissionHub?:boolean};role?:{mode:'CREATE'|'UPDATE';updateAction?:'ADD_PERMISSIONS'|'REMOVE_PERMISSIONS'|'UPDATE_TRUST'|'UPDATE_METADATA';name:string;description?:string;path?:string;trustedPrincipalType?:'SERVICE'|'AWS';trustedPrincipal?:string;trustPolicyDocument?:Record<string,unknown>;maxSessionDuration?:number;tags?:Record<string,string>};members?:GroupMemberRequest[];approvalPolicyId?:string;requiredApprovalStages?:string[];completedApprovalStages?:string[];provisioningAccountId?:string;provisioningRoleArn?:string;items:PermissionRequestItem[];scope:{type:'ALL'|'RESOURCE'|'ARN';resources:string[];arn?:string};duration:string;startDate:string;expiryDate?:string;priority:'Low'|'Medium'|'High'|'Critical'|'Normal'|'Urgent';justification:string;notes?:string;status:RequestStatus;submittedAt?:string;createdAt:string;approvalComment?:string;provisioningResult?:unknown;simulationResult?:unknown;timeline:{label:string;timestamp:string;result?:string}[] }
export interface PermissionGrant { id:string;requestId:string;awsAccountId?:string;targetType:TargetType;targetName:string;targetArn:string;policyArn:string;attachedAt:string;activatedAt?:string;expiresAt?:string;grantedPolicyArn?:string;revocationStatus?:string;scheduledRevocationId?:string;provisioningResponse:unknown;revocationResponse?:unknown;revokedAt?:string;createdGroup?:boolean;groupMembersAdded?:string[];createdPolicies?:string[] }
export interface AuditEvent { id:string;timestamp:string;actor:string;actorUserId?:string;tenantId?:string;requestId?:string;awsAccountId?:string;targetArn?:string;policyArn?:string;action:string;previousState?:unknown;newState?:unknown;result:'SUCCESS'|'FAILED'|'INFO';errorCode?:string;awsRequestId?:string;correlationId?:string }
