import { Router,type Response } from 'express';
import { z } from 'zod';
import { ApiError,asyncHandler,page } from '../utils/http.js';
import type { AuthenticatedRequest,PermissionGrant,PermissionRequest,RequestStatus } from '../types.js';
import { auditEvents,grants,mockIdentities,requests } from '../services/mock.service.js';
import { AwsConnectionService,AwsResourceService,IamIdentityService,IamPolicyService,IamPolicyValidationService,IamProvisioningService,IamSimulationService } from '../services/aws/aws-services.js';
import { accountScope,authorize,requireCapability } from '../middleware/auth.js';
import { authorization } from '../services/authorization.service.js';
import { approvalRouting } from '../services/approval-routing.service.js';
import { developmentAccounts,developmentUsers,identityDomain } from '../services/identity-domain.service.js';
import { AwsOrganisationSyncService,AwsOrganizationsService } from '../services/aws/organizations.service.js';
import { awsConnectionBroker,buildRoleArn } from '../services/aws/connection-broker.service.js';
import { securityAudit } from '../services/security-audit.service.js';
import { AwsIdentityCenterDiscoveryService } from '../services/aws/identity-center.service.js';
import { env } from '../config/env.js';
import { prisma } from '../config/database.js';
import { cache } from '../services/cache.service.js';
import { awsAccountRepository } from '../services/aws-account.repository.js';
import {buildProvisioningPlan,dryRunResult,parseReviewInput,provisioningMode,reviewCapabilities,type ProvisioningPlan,type ReviewAction} from '../services/request-review.service.js';
import {liveProvisioningEnabled} from '../config/env.js';

const router=Router();
router.use('/admin/accounts/onboarding',(_req,_res,next)=>env.AWS_CONNECTION_MODE==='manual'?next(new ApiError(410,'Use the manual Add AWS account flow on the Connection page.','MANUAL_CONNECTION_REQUIRED')):next());
const accountOptionalPaths=['/accounts','/connections','/local-credentials','/diagnostics','/cache'];
router.use('/aws',(req,res,next)=>accountOptionalPaths.some(path=>req.path===path||req.path.startsWith(`${path}/`))?next():accountScope(req as AuthenticatedRequest,res,next));router.use('/requests',accountScope);router.use('/activity',accountScope);router.use('/approvers',accountScope);
router.param('id',(req:AuthenticatedRequest,_res,next,id)=>{const request=requests.find(item=>item.id===id),account=req.awsAccountContext;if(request&&((request.tenantId&&request.tenantId!==req.tenantId)||(request.awsAccountId&&request.awsAccountId!==account?.id&&request.awsAccountId!==account?.accountId)))return next(new ApiError(404,'Permission request not found','NOT_FOUND'));if(request&&account&&request.requesterUserId&&request.requesterUserId!==req.sessionUser?.id&&!authorization.canApproveInAccount(req.sessionUser!,account.id)&&!authorization.canProvisionInAccount(req.sessionUser!,account.id)&&!authorization.canRevokeInAccount(req.sessionUser!,account.id)&&!authorization.canManageAccountConfiguration(req.sessionUser!,account.id))return next(new ApiError(404,'Permission request not found','NOT_FOUND'));next()});
const connection=(req:AuthenticatedRequest)=>new AwsConnectionService(req.awsAccountContext,req.sessionUser),identities=(req:AuthenticatedRequest)=>new IamIdentityService(req.awsAccountContext,req.sessionUser),policies=(req:AuthenticatedRequest)=>new IamPolicyService(req.awsAccountContext,req.sessionUser),resources=(req:AuthenticatedRequest)=>new AwsResourceService(req.awsAccountContext,req.sessionUser),simulator=(req:AuthenticatedRequest)=>new IamSimulationService(req.awsAccountContext,req.sessionUser),policyValidator=(req:AuthenticatedRequest)=>new IamPolicyValidationService(req.awsAccountContext,req.sessionUser),provisioner=(req:AuthenticatedRequest,requestId=String(req.params.id??''))=>new IamProvisioningService(req.awsAccountContext,req.sessionUser,requestId);

const pagination=z.object({page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25),limit:z.coerce.number().int().min(1).max(100).optional(),cursor:z.string().optional(),search:z.string().optional(),status:z.string().optional(),scope:z.string().optional(),service:z.string().optional(),accessLevel:z.string().optional(),attached:z.string().optional(),sort:z.string().optional()});
const requestSchema=z.object({title:z.string().min(5).max(160),targetType:z.enum(['USER','ROLE']),targetName:z.string().min(1),targetArn:z.string().startsWith('arn:aws:iam::'),items:z.array(z.object({mode:z.enum(['MANAGED_POLICY','SPECIFIC_ACTIONS']),policyArn:z.string().optional(),policyName:z.string().optional(),generatedPolicyName:z.string().min(3).max(128).optional(),actions:z.array(z.string().regex(/^[a-z0-9-]+:[A-Za-z0-9*]+$/)).optional(),generatedPolicyDocument:z.record(z.string(),z.unknown()).optional()})).min(1),scope:z.object({type:z.enum(['ALL','RESOURCE','ARN']),resources:z.array(z.string()).default([]),arn:z.string().optional()}),duration:z.enum(['1 hour','8 hours','1 day','7 days','30 days','Permanent','Custom']),startDate:z.string(),expiryDate:z.string().optional(),priority:z.enum(['Low','Medium','High','Critical','Normal','Urgent']),approver:z.string().min(1),justification:z.string().min(20).max(3000),notes:z.string().max(2000).optional()});
router.post('/aws/cache/clear',asyncHandler(async(req:AuthenticatedRequest,res)=>{if(env.NODE_ENV==='production')throw new ApiError(404,'Not found.','NOT_FOUND');cache.deleteContaining(`${req.tenantId!}:`);if(req.sessionUser?.activeAccountId){const account=identityDomain.account(req.sessionUser,req.sessionUser.activeAccountId);if(account)awsConnectionBroker.invalidateAccount(req.tenantId!,account.accountId)}res.json({data:{cleared:true}})}));
router.get('/aws/diagnostics',asyncHandler(async(req:AuthenticatedRequest,res)=>{const active=req.sessionUser?.activeAccountId?identityDomain.account(req.sessionUser,req.sessionUser.activeAccountId):undefined;res.json({data:{authenticationMode:env.AUTH_ENABLED?'configured':'development',awsConnectionMode:env.AWS_CONNECTION_MODE,activeTenantId:req.tenantId,activeAccountId:active?.accountId,connectionType:active?.connectionType,demoDataEnabled:env.ENABLE_AWS_DEMO_DATA,lastValidation:active?.lastValidatedAt,connectionStatus:active?.connectionStatus}})}));

router.get('/aws/connection',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await connection(req).status(),account:req.awsAccountContext,settings:{provisioningMode:provisioningMode(),liveProvisioningEnabled}})));
router.post('/aws/connection/test',asyncHandler(async(req:AuthenticatedRequest,res)=>{const data=await connection(req).test();audit(req,'AWS connection test',undefined,data.connected?'SUCCESS':'INFO',undefined,{mode:data.mode,accountId:data.accountId,region:data.region});res.json({data})}));
router.get('/aws/connections',asyncHandler(async(req:AuthenticatedRequest,res)=>{await awsAccountRepository.refreshManualAccounts(req.tenantId!);res.json({data:identityDomain.accountsFor(req.sessionUser!).map(account=>publicConnection(account))})}));
router.post('/aws/connection/validate-read',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await awsConnectionBroker.validateAccountConnection(req.sessionUser!,req.awsAccountContext!.id,'READ')})));
router.post('/aws/connection/capabilities',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await awsConnectionBroker.testReadCapabilities(req.sessionUser!,req.awsAccountContext!.id)})));
router.post('/aws/connection/validate-provision',requireCapability('manage'),asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await awsConnectionBroker.validateAccountConnection(req.sessionUser!,req.awsAccountContext!.id,'PROVISION',true)})));
router.post('/aws/connection/status',requireCapability('manage'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=z.object({status:z.enum(['DISABLED','PENDING'])}).parse(req.body);req.awsAccountContext!.connectionStatus=input.status;awsConnectionBroker.invalidateAccount(req.tenantId!,req.awsAccountContext!.accountId);if(env.NODE_ENV!=='test')await prisma.awsAccountConnection.updateMany({where:{tenantId:req.tenantId,awsAccountId:req.awsAccountContext!.id},data:{connectionStatus:input.status}}).catch(()=>undefined);securityAudit.record({tenantId:req.tenantId,awsAccountId:req.awsAccountContext!.id,actorUserId:req.sessionUser!.id,action:input.status==='DISABLED'?'AWS_CONNECTION_DISABLED':'AWS_CONNECTION_ENABLED',outcome:'SUCCESS',metadata:{accountId:req.awsAccountContext!.accountId}});res.json({data:publicConnection(req.awsAccountContext!)})}));

router.get('/aws/identities/users',asyncHandler(async(req:AuthenticatedRequest,res)=>{const q=pagination.parse(req.query);const data=await identities(req).listUsers(q.search,q.pageSize);audit(req,'Identity discovery',undefined,'SUCCESS');res.json(page(data,q.page,q.pageSize))}));
router.get('/aws/identities/users/:userName',asyncHandler(async(req:AuthenticatedRequest,res)=>{const user=await identities(req).getUser(String(req.params.userName));if(!user)throw new ApiError(404,'IAM user not found','NOT_FOUND');res.json({data:user})}));
router.get('/aws/identities/roles',asyncHandler(async(req:AuthenticatedRequest,res)=>{const q=pagination.parse(req.query);const data=await identities(req).listRoles(q.search,String(req.query.includeServiceLinked)==='true',q.pageSize);audit(req,'Identity discovery',undefined,'SUCCESS');res.json(page(data,q.page,q.pageSize))}));
router.get('/aws/identities/roles/:roleName',asyncHandler(async(req:AuthenticatedRequest,res)=>{const role=await identities(req).getRole(String(req.params.roleName));if(!role)throw new ApiError(404,'IAM role not found','NOT_FOUND');res.json({data:role})}));

router.get('/aws/policies',asyncHandler(async(req:AuthenticatedRequest,res)=>{const q=pagination.parse(req.query);const result=await policies(req).list({...q,limit:q.limit??q.pageSize});audit(req,'Policy discovery',undefined,'SUCCESS',undefined,{loadedCount:result.loadedCount,cacheStatus:result.cacheStatus});res.json({data:result.items,pagination:{page:q.page,pageSize:q.limit??q.pageSize,total:result.loadedCount,totalPages:result.isComplete?Math.max(1,Math.ceil(result.loadedCount/(q.limit??q.pageSize))):q.page},nextCursor:result.nextCursor,isComplete:result.isComplete,loadedCount:result.loadedCount,cacheStatus:result.cacheStatus,timing:process.env.NODE_ENV==='production'?undefined:result.timing})}));
router.get('/aws/policies/:encodedArn',asyncHandler(async(req:AuthenticatedRequest,res)=>{const policy=await policies(req).get(String(req.params.encodedArn));if(!policy)throw new ApiError(404,'IAM policy not found','NOT_FOUND');res.json({data:policy})}));
router.post('/aws/policies/validate',asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=z.object({document:z.record(z.string(),z.unknown())}).parse(req.body);const result=await policyValidator(req).validate(input.document);audit(req,'Policy validation',undefined,'SUCCESS',undefined,{mode:result.mode,findings:Array.isArray(result.findings)?result.findings.length:0});res.json({data:result})}));

router.get('/aws/resources',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await resources(req).all()})));
router.get('/aws/resources/s3',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await resources(req).s3Resources()})));
router.get('/aws/resources/rds',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await resources(req).rdsResources()})));
router.get('/aws/resources/lambda',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await resources(req).lambdaResources()})));
router.get('/aws/identity-center/discover',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await new AwsIdentityCenterDiscoveryService().discover(req.sessionUser!,req.awsAccountContext!)})));
router.get('/aws/organisations/discover',authorize('ORGANISATION_ADMIN'),asyncHandler(async(req:AuthenticatedRequest,res)=>{if(!env.AWS_ORGANISATIONS_DISCOVERY_ENABLED)throw new ApiError(403,'AWS Organisations discovery is disabled.','FEATURE_DISABLED');const result=await new AwsOrganizationsService().discover(req.awsAccountContext!,String(req.query.refresh)==='true',req.sessionUser);audit(req,'AWS Organisation discovery',undefined,'SUCCESS',undefined,{accounts:result.accounts.length,organisationalUnits:result.organisationalUnits.length});res.json({data:result})}));
router.post('/aws/organisations/:organisationId/sync',authorize('ORGANISATION_ADMIN'),asyncHandler(async(req:AuthenticatedRequest,res)=>{if(!env.AWS_ORGANISATIONS_DISCOVERY_ENABLED)throw new ApiError(403,'AWS Organisations discovery is disabled.','FEATURE_DISABLED');const result=await new AwsOrganisationSyncService().syncOrganisation({actor:req.sessionUser!,tenantId:req.tenantId!,organisationConnectionId:String(req.params.organisationId),context:req.awsAccountContext!,forceRefresh:true});res.json({data:result})}));

router.get('/admin/directory',authorize('ORGANISATION_ADMIN'),asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:{tenants:identityDomain.tenantsFor(req.sessionUser!),organisations:identityDomain.organisationsFor(req.sessionUser!),organisationalUnits:identityDomain.ousFor(req.sessionUser!),accounts:identityDomain.accountsFor(req.sessionUser!),users:developmentUsers.filter(user=>user.memberships.some(m=>m.tenantId===req.tenantId)).map(user=>({id:user.id,email:user.email,displayName:user.displayName,memberships:user.memberships}))}})));
router.get('/admin/approval-policies',authorize('ORGANISATION_ADMIN'),asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:identityDomain.accountsFor(req.sessionUser!).map(account=>({accountType:account.accountType,...approvalRouting.route({account,duration:'8 hours',permanent:false})}))})));
router.post('/admin/scopes',authorize('ORGANISATION_ADMIN'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=z.object({membershipId:z.string(),scopeType:z.enum(['TENANT','AWS_ORGANISATION','ORGANISATIONAL_UNIT','AWS_ACCOUNT']),scopeId:z.string(),includeDescendants:z.boolean().default(true),canView:z.boolean().default(true),canRequest:z.boolean().default(false),canApprove:z.boolean().default(false),canProvision:z.boolean().default(false),canRevoke:z.boolean().default(false),canManageConfiguration:z.boolean().default(false)}).parse(req.body),{membershipId,...scope}=input;const membership=developmentUsers.flatMap(user=>user.memberships).find(item=>item.id===membershipId&&item.tenantId===req.tenantId);if(!membership)throw new ApiError(404,'Tenant membership not found.','NOT_FOUND');const existing=membership.scopes.find(item=>item.scopeType===scope.scopeType&&item.scopeId===scope.scopeId);if(existing)Object.assign(existing,scope);else membership.scopes.push(scope);audit(req,'Admin scope assigned',undefined,'SUCCESS',undefined,{membershipId,scopeType:scope.scopeType,scopeId:scope.scopeId});res.status(201).json({data:{membershipId,...scope}})}));
router.post('/admin/accounts/onboarding',authorize('ORGANISATION_ADMIN'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=z.object({accountId:z.string().regex(/^\d{12}$/),accountName:z.string().min(2).max(100),connectionType:z.enum(['ORGANISATION_MEMBER','STANDALONE','EXTERNAL_CUSTOMER']),accountType:z.enum(['MANAGEMENT','SECURITY','LOG_ARCHIVE','SHARED_SERVICES','NETWORK','PRODUCTION','STAGING','DEVELOPMENT','SANDBOX','EXTERNAL']),defaultRegion:z.string().min(3),rolePath:z.string().max(128).default(''),readRoleArn:z.string().startsWith('arn:aws:iam::').optional(),provisionRoleArn:z.string().startsWith('arn:aws:iam::').optional(),externalIdSecretReference:z.string().optional()}).parse(req.body);if(developmentAccounts.some(account=>account.tenantId===req.tenantId&&account.accountId===input.accountId))throw new ApiError(409,'This AWS account is already configured for the active tenant.','AWS_ACCOUNT_EXISTS');const id=`account_${input.accountId}`,account={id,tenantId:req.tenantId!,accountId:input.accountId,accountName:input.accountName,accountType:input.accountType,environment:input.accountType.toLowerCase(),riskTier:input.accountType==='PRODUCTION'||input.accountType==='SECURITY'?'HIGH':'MODERATE',region:input.defaultRegion,connectionType:input.connectionType,connectionStatus:'PENDING' as const,provisioningStatus:'DISABLED' as const,provisioningEnabled:false,readRoleArn:input.readRoleArn??buildRoleArn(input.accountId,env.AWS_READ_ROLE_NAME,input.rolePath),provisionRoleArn:input.provisionRoleArn??buildRoleArn(input.accountId,env.AWS_PROVISION_ROLE_NAME,input.rolePath),externalIdSecretReference:input.externalIdSecretReference,organisationsRegion:env.AWS_ORGANISATIONS_REGION};developmentAccounts.push(account);const membership=req.sessionUser!.memberships.find(item=>item.tenantId===req.tenantId);membership?.scopes.push({scopeType:'AWS_ACCOUNT',scopeId:id,includeDescendants:true,canView:true,canRequest:true,canApprove:true,canProvision:true,canRevoke:true,canManageConfiguration:true});securityAudit.record({tenantId:req.tenantId,awsAccountId:id,actorUserId:req.sessionUser!.id,action:'AWS_ACCOUNT_ONBOARDING_CREATED',outcome:'SUCCESS',metadata:{accountId:input.accountId,connectionType:input.connectionType,externalIdConfigured:Boolean(input.externalIdSecretReference)}});res.status(201).json({data:{account:publicConnection(account),templatePath:'infrastructure/aws-onboarding/permissionhub-account-role.yaml',instructions:['Deploy the onboarding template in the target account.','Store the generated external ID in the configured server-side secret reference.','Return here and validate the read connection.']}})}));

router.get('/requests',asyncHandler(async(req:AuthenticatedRequest,res)=>{const q=pagination.parse(req.query),account=req.awsAccountContext!,mayReview=authorization.canApproveInAccount(req.sessionUser!,account.id)||authorization.canProvisionInAccount(req.sessionUser!,account.id)||authorization.canRevokeInAccount(req.sessionUser!,account.id)||authorization.canManageAccountConfiguration(req.sessionUser!,account.id);let data=requests.filter(r=>(!r.tenantId||r.tenantId===req.tenantId)&&(!r.awsAccountId||r.awsAccountId===account.id||r.awsAccountId===account.accountId)&&(mayReview||r.requesterUserId===req.sessionUser!.id||(!r.requesterUserId&&r.requester===req.sessionUser!.displayName)));if(q.status)data=data.filter(r=>r.status===q.status);if(q.search){const s=q.search.toLowerCase();data=data.filter(r=>(r.id+r.title+r.requester+r.approver+r.targetName+r.items.map(i=>i.policyName??i.actions?.join(' ')).join(' ')).toLowerCase().includes(s))}res.json(page(data,q.page,q.pageSize))}));
router.post('/requests',requireCapability('request'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=requestSchema.parse(req.body);assertRequest(input);const account=req.awsAccountContext!,route=approvalRouting.route({account,duration:input.duration,permanent:input.duration==='Permanent'});if(input.duration==='Permanent'&&!route.permanentAccessAllowed)throw new ApiError(422,`Permanent access is not allowed for ${account.accountType} accounts.`,'PERMANENT_NOT_ALLOWED');const id=nextRequestId(),items=input.items.map((item,index)=>item.mode==='SPECIFIC_ACTIONS'?{...item,generatedPolicyName:item.generatedPolicyName??`PH-${id}-${index+1}`}:{...item});const created:PermissionRequest={id,tenantId:req.tenantId,awsOrganisationId:account.organisationId,ouId:account.ouId,awsAccountId:account.id,accountType:account.accountType,requesterUserId:req.sessionUser!.id,requester:req.sessionUser!.displayName,targetSubjectType:input.targetType,approvalPolicyId:route.policyId,requiredApprovalStages:route.requiredApprovalStages,provisioningAccountId:account.id,provisioningRoleArn:account.provisionRoleArn,status:'Draft',createdAt:new Date().toISOString(),timeline:[{label:'Draft created',timestamp:new Date().toISOString()}],...input,items};requests.unshift(created);audit(req,'REQUEST_CREATED',created.id,'SUCCESS',undefined,{status:created.status,targetArn:created.targetArn,awsAccountId:account.accountId,approvalPolicyId:route.policyId});res.status(201).json({data:created,approvalRoute:route})}));
router.get('/requests/:id',asyncHandler(async(req:AuthenticatedRequest,res)=>{const request=findRequest(String(req.params.id)),account=req.awsAccountContext!,approvalAllowed=request.status==='Pending approval'&&authorization.canApproveRequest(req.sessionUser!,{...request,awsAccountId:request.awsAccountId??account.id}),provisionPermission=authorization.canProvisionInAccount(req.sessionUser!,account.id);res.json({data:{...request,preview:preview(request),reviewCapabilities:reviewCapabilities({request,account,approvalAllowed,provisionPermission}),reviewContext:{accountName:account.accountName,awsAccountNumber:account.accountId,accountType:account.accountType,region:account.region,connectionStatus:account.connectionStatus,provisionRoleConfigured:Boolean(account.provisionRoleArn)}}})}));
router.post('/requests/:id/submit',asyncHandler(async(req:AuthenticatedRequest,res)=>{const request=findRequest(String(req.params.id));if(request.requesterUserId&&request.requesterUserId!==req.sessionUser!.id)throw new ApiError(403,'Only the requester can submit this draft.','REQUEST_OWNER_REQUIRED');transition(request,'Pending approval','Submitted');request.submittedAt=new Date().toISOString();audit(req,'Request submitted',request.id,'SUCCESS',{status:'Draft'},{status:request.status});res.json({data:request})}));
router.post('/requests/:id/review',asyncHandler(async(req:AuthenticatedRequest,res)=>handleReview(req,res)));
router.post('/requests/:id/request-information',asyncHandler(async(req:AuthenticatedRequest,res)=>handleReview(req,res,'REQUEST_INFORMATION')));
router.post('/requests/:id/approve',asyncHandler(async(req:AuthenticatedRequest,res)=>handleReview(req,res,'APPROVE')));
router.post('/requests/:id/reject',asyncHandler(async(req:AuthenticatedRequest,res)=>handleReview(req,res,'REJECT')));
router.post('/requests/:id/simulate',asyncHandler(async(req:AuthenticatedRequest,res)=>{const request=findRequest(String(req.params.id));const result=await simulator(req).simulate({targetArn:request.targetArn,actions:request.items.flatMap(i=>i.actions??[]),policyDocument:request.items.find(i=>i.generatedPolicyDocument)?.generatedPolicyDocument});request.simulationResult=result;request.timeline.push({label:'Simulation run',timestamp:new Date().toISOString(),result:'estimate'});audit(req,'Simulation run',request.id,'SUCCESS',undefined,result);res.json({data:{request,result,preview:preview(request)}})}));
router.post('/requests/:id/provision',(req:AuthenticatedRequest,_res,next)=>{const request=findRequest(String(req.params.id));if(request.expiryDate&&Date.parse(request.expiryDate)<=Date.now())return next(new ApiError(409,'This permission request has expired and cannot be provisioned.','REQUEST_EXPIRED'));next()});
router.post('/requests/:id/provision',asyncHandler(async(req:AuthenticatedRequest,res)=>{const request=findRequest(String(req.params.id));if(!authorization.canProvisionRequest(req.sessionUser!,{...request,awsAccountId:request.awsAccountId??req.awsAccountContext!.id}))throw new ApiError(403,'You are not authorised to provision this request.','PROVISIONING_FORBIDDEN');if(request.status!=='Approved'&&request.status!=='Provisioning failed')throw new ApiError(409,'Only approved or failed provisioning requests can be provisioned.','INVALID_STATE');const plan=buildProvisioningPlan(request,req.awsAccountContext!);if(!plan.valid)throw incompletePlan(plan);if(provisioningMode()==='disabled')throw new ApiError(409,'This request is approved, but provisioning is disabled for this environment.','PROVISIONING_DISABLED',{plannedOperations:plan.plannedOperations});res.json({data:await runProvisioning(req,request,plan)})}));
router.post('/requests/:id/revoke',asyncHandler(async(req:AuthenticatedRequest,res)=>{const request=findRequest(String(req.params.id));const active=grants.filter(g=>g.requestId===request.id&&!g.revokedAt);if(!active.every(grant=>authorization.canRevokeGrant(req.sessionUser!,{...grant,awsAccountId:grant.awsAccountId??req.awsAccountContext!.id})))throw new ApiError(403,'You are not authorised to revoke this grant.','REVOCATION_FORBIDDEN');const revoked=[];for(const grant of active){const result=await provisioner(req).detach({targetType:grant.targetType,targetName:grant.targetName,policyArn:grant.policyArn});grant.revokedAt=new Date().toISOString();grant.revocationResponse=result;revoked.push(result);audit(req,'Policy detached',request.id,'SUCCESS',undefined,{policyArn:grant.policyArn,result})}transition(request,'Revoked','Access removed');res.json({data:{request,revoked}})}));

router.get('/activity',asyncHandler(async(req,res)=>{const q=pagination.parse(req.query);res.json(page(auditEvents,q.page,q.pageSize))}));
router.get('/approvers',(req:AuthenticatedRequest,res)=>{const account=req.awsAccountContext!;const eligible=developmentUsers.map(user=>identityDomain.sessionUser(user,'development')).filter(user=>user.id!==req.sessionUser!.id&&authorization.canApproveRequest(user,{awsAccountId:account.id,requesterUserId:req.sessionUser!.id})).map(user=>({id:user.id,name:user.displayName,email:user.email,role:user.memberships.find(m=>m.tenantId===account.tenantId)?.role}));res.json({data:eligible})});

const reviewOperationResults=new Map<string,unknown>();
async function handleReview(req:AuthenticatedRequest,res:Response,forcedAction?:ReviewAction){
 const input=parseReviewInput({...req.body,action:forcedAction??req.body?.action}),request=findRequest(String(req.params.id)),operationKey=input.idempotencyKey??req.headers['idempotency-key']?.toString();
 if(operationKey){const stored=reviewOperationResults.get(`${request.id}:${operationKey}`);if(stored)return res.json({data:stored,idempotent:true})}
 if(request.status!=='Pending approval')throw new ApiError(409,'This request is not awaiting approval.','INVALID_REVIEW_STATE',{currentStatus:request.status});
 assertApprover(req,request);
 const account=req.awsAccountContext!,plan=buildProvisioningPlan(request,account);
 if(input.action==='APPROVE_AND_PROVISION'){
  if(!authorization.canProvisionInAccount(req.sessionUser!,account.id))throw new ApiError(403,'Approve and provision requires both approval and provisioning permission.','PROVISIONING_FORBIDDEN');
  if(!plan.valid)throw incompletePlan(plan);
 }
 request.approvalComment=input.comment;
 if(input.action==='REJECT'){
  transition(request,'Rejected','Rejected',input.comment);audit(req,'REQUEST_REJECTED',request.id,'SUCCESS',undefined,{comment:input.comment,provisioningMode:provisioningMode(),awsMutationOccurred:false});
  const result={request,reviewAction:input.action};if(operationKey)reviewOperationResults.set(`${request.id}:${operationKey}`,result);return res.json({data:result});
 }
 if(input.action==='REQUEST_INFORMATION'){
  transition(request,'More information required','More information requested',input.comment);audit(req,'REQUEST_INFORMATION_REQUESTED',request.id,'SUCCESS',undefined,{comment:input.comment,provisioningMode:provisioningMode(),awsMutationOccurred:false});
  const result={request,reviewAction:input.action};if(operationKey)reviewOperationResults.set(`${request.id}:${operationKey}`,result);return res.json({data:result});
 }
 const approvalStages=(request.requiredApprovalStages??['ACCOUNT_APPROVER']).filter(stage=>stage!=='PROVISIONER'),completed=request.completedApprovalStages??[],stage=approvalStages[completed.length]??'ACCOUNT_APPROVER';
 request.completedApprovalStages=[...completed,stage];const remaining=approvalStages.length-request.completedApprovalStages.length;
 if(remaining>0)request.timeline.push({label:`${stage.replaceAll('_',' ')} approved`,timestamp:new Date().toISOString(),result:`${remaining} approval stage${remaining===1?'':'s'} remaining`});else transition(request,'Approved','Approved',input.comment);
 audit(req,input.comment?'REQUEST_APPROVED_WITH_COMMENT':'REQUEST_APPROVED',request.id,'SUCCESS',undefined,{status:request.status,stage,comment:input.comment,provisioningMode:provisioningMode(),plannedOperations:plan.plannedOperations,awsMutationOccurred:false});
 let provisioning:unknown;
 if(input.action==='APPROVE_AND_PROVISION'&&remaining===0)provisioning=(await runProvisioning(req,request,plan)).provisioning;
 else if(input.action==='APPROVE_AND_PROVISION')provisioning={mode:provisioningMode(),executed:false,safe:true,plannedOperations:plan.plannedOperations,message:`Request approval recorded; ${remaining} approval stage${remaining===1?'':'s'} remain before provisioning.`};
 const result={request:{...request,preview:preview(request)},reviewAction:input.action,provisioning,capabilities:reviewCapabilities({request,account,approvalAllowed:false,provisionPermission:authorization.canProvisionInAccount(req.sessionUser!,account.id)})};
 if(operationKey)reviewOperationResults.set(`${request.id}:${operationKey}`,result);return res.json({data:result});
}

async function runProvisioning(req:AuthenticatedRequest,request:PermissionRequest,plan:ProvisioningPlan){
 const mode=provisioningMode();
 if(mode==='disabled'){
  const provisioning={mode,executed:false,safe:true,targetAccount:plan.targetAccount,targetPrincipal:plan.targetPrincipal,plannedOperations:plan.plannedOperations,validationResults:plan.validationResults,message:'This request was approved, but provisioning is disabled for this environment.'};request.provisioningResult=provisioning;audit(req,'PROVISIONING_SKIPPED',request.id,'INFO',undefined,{provisioningMode:mode,plannedOperations:plan.plannedOperations,awsMutationOccurred:false});return {request,provisioning};
 }
 if(mode==='dry-run'){
  audit(req,'PROVISIONING_DRY_RUN_STARTED',request.id,'INFO',undefined,{provisioningMode:mode,plannedOperations:plan.plannedOperations,awsMutationOccurred:false});const result=dryRunResult(request,plan);request.provisioningResult=result.provisioning;request.timeline.push({label:'Provisioning dry-run completed',timestamp:new Date().toISOString(),result:'No AWS changes were made'});audit(req,'PROVISIONING_DRY_RUN_COMPLETED',request.id,'SUCCESS',undefined,{provisioningMode:mode,plannedOperations:plan.plannedOperations,awsMutationOccurred:false,outcome:'VALIDATED'});return {request,...result};
 }
 if(!liveProvisioningEnabled)return blockedLiveResult(req,request,plan,'Live provisioning safety flags are incomplete.');
 if(req.awsAccountContext!.connectionStatus!=='CONNECTED')return blockedLiveResult(req,request,plan,'The AWS connection must be Connected before live provisioning.');
 if(!req.awsAccountContext!.provisionRoleArn)return blockedLiveResult(req,request,plan,'A validated provisioning role is required for live provisioning.');
 const identity=request.targetType==='USER'?await identities(req).getUser(request.targetName):await identities(req).getRole(request.targetName);
 if(!identity)return blockedLiveResult(req,request,plan,'The requested IAM target no longer exists.');
 for(const item of request.items.filter(item=>item.mode==='MANAGED_POLICY')){
  if(!item.policyArn||!await policies(req).get(item.policyArn))return blockedLiveResult(req,request,plan,'A requested managed policy no longer exists.');
  if(identity.attachedPolicies.some(policy=>policy.policyArn===item.policyArn))return blockedLiveResult(req,request,plan,'A requested managed policy is already attached to the target.');
 }
 const validation=await awsConnectionBroker.validateAccountConnection(req.sessionUser!,req.awsAccountContext!.id,'PROVISION',true);
 if(validation.accountId!==req.awsAccountContext!.accountId)return blockedLiveResult(req,request,plan,'STS returned an account that does not match the request account.');
 transition(request,'Provisioning','Provisioning started');audit(req,'PROVISIONING_STARTED',request.id,'INFO',undefined,{provisioningMode:mode,plannedOperations:plan.plannedOperations,awsMutationOccurred:false});
 const provisioned:unknown[]=[];
 try{
  for(const item of request.items){const service=provisioner(req),policyArn=item.policyArn??String((await service.createCustomerPolicy(item.generatedPolicyName!,item.generatedPolicyDocument!)).policyArn),result=await service.attach({targetType:request.targetType,targetName:request.targetName,policyArn});provisioned.push(result);const grant:PermissionGrant={id:`grant_${Date.now()}_${grants.length}`,requestId:request.id,awsAccountId:req.awsAccountContext!.id,targetType:request.targetType,targetName:request.targetName,targetArn:request.targetArn,policyArn,attachedAt:new Date().toISOString(),expiresAt:request.expiryDate,provisioningResponse:result};grants.push(grant)}
  request.provisioningResult={mode,executed:true,plannedOperations:plan.plannedOperations,results:provisioned};transition(request,'Provisioned','AWS operation completed');audit(req,'PROVISIONING_COMPLETED',request.id,'SUCCESS',undefined,{provisioningMode:mode,plannedOperations:plan.plannedOperations,awsMutationOccurred:true});return {request,provisioning:request.provisioningResult,grants:grants.filter(grant=>grant.requestId===request.id)};
 }catch(error:any){transition(request,'Provisioning failed','Provisioning failed',error?.message);audit(req,'PROVISIONING_FAILED',request.id,'FAILED',undefined,{provisioningMode:mode,plannedOperations:plan.plannedOperations,awsMutationOccurred:false,error:error?.message});throw new ApiError(422,'The request was approved, but live provisioning failed.','PROVISIONING_FAILED',{recommendedAction:'Review the sanitised provisioning error and retry after correcting the connection.'})}
}

function blockedLiveResult(req:AuthenticatedRequest,request:PermissionRequest,plan:ProvisioningPlan,message:string){const provisioning={mode:'live',executed:false,safe:false,targetAccount:plan.targetAccount,targetPrincipal:plan.targetPrincipal,plannedOperations:plan.plannedOperations,validationResults:plan.validationResults,message};request.provisioningResult=provisioning;audit(req,'PROVISIONING_FAILED',request.id,'FAILED',undefined,{provisioningMode:'live',plannedOperations:plan.plannedOperations,awsMutationOccurred:false,error:message});return {request,provisioning}}
function incompletePlan(plan:ProvisioningPlan){return new ApiError(422,'The request does not contain a complete IAM provisioning plan.','INCOMPLETE_PROVISIONING_PLAN',{blockingFields:plan.errors,recommendedAction:'Return to the request and complete the target, policy document, actions, and resource scope.'})}

function findRequest(id:string){const request=requests.find(r=>r.id===id);if(!request)throw new ApiError(404,'Permission request not found','NOT_FOUND');return request}
function assertApprover(req:AuthenticatedRequest,request:PermissionRequest){if(!authorization.canApproveRequest(req.sessionUser!,{...request,awsAccountId:request.awsAccountId??req.awsAccountContext!.id}))throw new ApiError(403,'You are not eligible to review this request. Requesters cannot review their own requests.','APPROVAL_FORBIDDEN')}
function nextRequestId(){const max=requests.reduce((current,request)=>Math.max(current,Number(request.id.match(/^PR-(\d+)$/)?.[1]??0)),1000);return `PR-${max+1}`}
function transition(request:PermissionRequest,status:RequestStatus,label:string,result?:string){const previous=request.status;request.status=status;request.timeline.push({label,timestamp:new Date().toISOString(),result:result??(previous!==status?status:undefined)})}
function assertRequest(input:z.infer<typeof requestSchema>){if(input.items.some(item=>item.policyArn?.endsWith('/AdministratorAccess')))throw new ApiError(422,'AdministratorAccess provisioning is explicitly blocked','BLOCKED_POLICY');if(input.duration==='Permanent'&&!input.notes)throw new ApiError(422,'Permanent access requires notes acknowledging the risk','PERMANENT_REQUIRES_NOTES')}
function preview(request:PermissionRequest){const identity=mockIdentities.find(i=>i.arn===request.targetArn);const existing=identity?.attachedPolicies??[];const requested=request.items.map(i=>({policyName:i.policyName??i.generatedPolicyName,policyArn:i.policyArn,actions:i.actions})),awsOperations=request.items.flatMap(item=>item.mode==='SPECIFIC_ACTIONS'?['CreatePolicy',request.targetType==='USER'?'AttachUserPolicy':'AttachRolePolicy']:[request.targetType==='USER'?'AttachUserPolicy':'AttachRolePolicy']);return {estimate:true,before:{managedPolicies:existing,inlinePolicies:identity?.inlinePolicies??[],effectiveActions:'Available through IAM simulation where supported.'},change:{policiesToAttach:requested,policiesToDetach:[],resourceScope:request.scope,expiration:request.duration==='Permanent'?'No automatic expiry':request.expiryDate},after:{managedPolicies:[...existing,...request.items.filter(i=>i.policyName&&i.policyArn).map(i=>({policyName:i.policyName!,policyArn:i.policyArn!}))],newlyAllowedActions:request.items.flatMap(i=>i.actions??[]),riskFlags:request.items.some(i=>i.policyArn?.endsWith('/PowerUserAccess'))?['Broad write access outside IAM']:[]},awsOperation:awsOperations.join(' → '),awsOperations}};
function audit(req:AuthenticatedRequest,action:string,requestId?:string,result:'SUCCESS'|'FAILED'|'INFO'='SUCCESS',previousState?:unknown,newState?:unknown){auditEvents.unshift({id:`evt_${Date.now()}_${auditEvents.length}`,timestamp:new Date().toISOString(),actor:req.sessionUser?.displayName??'System',actorUserId:req.sessionUser?.id,tenantId:req.tenantId,requestId,awsAccountId:req.awsAccountContext?.accountId,action,previousState,newState,result,correlationId:(req as any).correlationId})}
function publicConnection(account:import('../types.js').AwsAccountContext){const {externalIdSecretReference:_,...safe}=account;return {...safe,externalIdConfigured:Boolean(account.externalIdSecretReference),provisionRoleConfigured:Boolean(account.provisionRoleArn)}}

export default router;
