import { Router } from 'express';
import { z } from 'zod';
import { ApiError,asyncHandler,page } from '../utils/http.js';
import type { AuthenticatedRequest,PermissionGrant,PermissionRequest,RequestStatus } from '../types.js';
import { auditEvents,grants,mockIdentities,requests } from '../services/mock.service.js';
import { AwsConnectionService,AwsResourceService,IamIdentityService,IamPolicyService,IamPolicyValidationService,IamProvisioningService,IamSimulationService } from '../services/aws/aws-services.js';
import { accountScope,authorize,requireCapability } from '../middleware/auth.js';
import { authorization } from '../services/authorization.service.js';
import { approvalRouting } from '../services/approval-routing.service.js';
import { developmentAccounts,developmentOrganisations,developmentOus,developmentUsers,identityDomain } from '../services/identity-domain.service.js';
import { AwsOrganisationSyncService,AwsOrganizationsService } from '../services/aws/organizations.service.js';
import { awsConnectionBroker,buildRoleArn } from '../services/aws/connection-broker.service.js';
import { securityAudit } from '../services/security-audit.service.js';
import { AwsIdentityCenterDiscoveryService } from '../services/aws/identity-center.service.js';
import { env } from '../config/env.js';
import { prisma } from '../config/database.js';

const router=Router();
router.use('/aws',accountScope);router.use('/requests',accountScope);router.use('/activity',accountScope);router.use('/approvers',accountScope);
router.param('id',(req:AuthenticatedRequest,_res,next,id)=>{const request=requests.find(item=>item.id===id),account=req.awsAccountContext;if(request&&((request.tenantId&&request.tenantId!==req.tenantId)||(request.awsAccountId&&request.awsAccountId!==account?.id&&request.awsAccountId!==account?.accountId)))return next(new ApiError(404,'Permission request not found','NOT_FOUND'));if(request&&account&&request.requesterUserId&&request.requesterUserId!==req.sessionUser?.id&&!authorization.canApproveInAccount(req.sessionUser!,account.id)&&!authorization.canProvisionInAccount(req.sessionUser!,account.id)&&!authorization.canRevokeInAccount(req.sessionUser!,account.id)&&!authorization.canManageAccountConfiguration(req.sessionUser!,account.id))return next(new ApiError(404,'Permission request not found','NOT_FOUND'));next()});
const connection=(req:AuthenticatedRequest)=>new AwsConnectionService(req.awsAccountContext,req.sessionUser),identities=(req:AuthenticatedRequest)=>new IamIdentityService(req.awsAccountContext,req.sessionUser),policies=(req:AuthenticatedRequest)=>new IamPolicyService(req.awsAccountContext,req.sessionUser),resources=(req:AuthenticatedRequest)=>new AwsResourceService(req.awsAccountContext,req.sessionUser),simulator=(req:AuthenticatedRequest)=>new IamSimulationService(req.awsAccountContext,req.sessionUser),policyValidator=(req:AuthenticatedRequest)=>new IamPolicyValidationService(req.awsAccountContext,req.sessionUser),provisioner=(req:AuthenticatedRequest,requestId=String(req.params.id??''))=>new IamProvisioningService(req.awsAccountContext,req.sessionUser,requestId);

const pagination=z.object({page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25),limit:z.coerce.number().int().min(1).max(100).optional(),cursor:z.string().optional(),search:z.string().optional(),status:z.string().optional(),scope:z.string().optional(),service:z.string().optional(),accessLevel:z.string().optional(),attached:z.string().optional(),sort:z.string().optional()});
const requestSchema=z.object({title:z.string().min(5).max(160),targetType:z.enum(['USER','ROLE']),targetName:z.string().min(1),targetArn:z.string().startsWith('arn:aws:iam::'),items:z.array(z.object({mode:z.enum(['MANAGED_POLICY','SPECIFIC_ACTIONS']),policyArn:z.string().optional(),policyName:z.string().optional(),actions:z.array(z.string().regex(/^[a-z0-9-]+:[A-Za-z0-9*]+$/)).optional(),generatedPolicyDocument:z.record(z.string(),z.unknown()).optional()})).min(1),scope:z.object({type:z.enum(['ALL','RESOURCE','ARN']),resources:z.array(z.string()).default([]),arn:z.string().optional()}),duration:z.enum(['1 hour','8 hours','1 day','7 days','30 days','Permanent','Custom']),startDate:z.string(),expiryDate:z.string().optional(),priority:z.enum(['Low','Medium','High','Critical','Normal','Urgent']),approver:z.string().min(1),justification:z.string().min(20).max(3000),notes:z.string().max(2000).optional()});
const commentSchema=z.object({comment:z.string().min(2).max(2000)});

router.get('/aws/connection',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await connection(req).status(),account:req.awsAccountContext,settings:{provisioningMode:process.env.PROVISIONING_MODE??'MOCK',liveProvisioningEnabled:process.env.ENABLE_LIVE_PROVISIONING==='true'}})));
router.post('/aws/connection/test',asyncHandler(async(req:AuthenticatedRequest,res)=>{const data=await connection(req).test();audit(req,'AWS connection test',undefined,data.connected?'SUCCESS':'INFO',undefined,{mode:data.mode,accountId:data.accountId,region:data.region});res.json({data})}));
router.get('/aws/connections',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:identityDomain.accountsFor(req.sessionUser!).map(account=>publicConnection(account))})));
router.post('/aws/connection/validate-read',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await awsConnectionBroker.validateAccountConnection(req.sessionUser!,req.awsAccountContext!.id,'READ')})));
router.post('/aws/connection/capabilities',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await awsConnectionBroker.testReadCapabilities(req.sessionUser!,req.awsAccountContext!.id)})));
router.post('/aws/connection/validate-provision',requireCapability('manage'),asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await awsConnectionBroker.validateAccountConnection(req.sessionUser!,req.awsAccountContext!.id,'PROVISION',true)})));
router.post('/aws/connection/status',requireCapability('manage'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=z.object({status:z.enum(['DISABLED','PENDING'])}).parse(req.body);req.awsAccountContext!.connectionStatus=input.status;awsConnectionBroker.invalidateAccount(req.tenantId!,req.awsAccountContext!.accountId);if(env.NODE_ENV!=='test')await prisma.awsAccountConnection.updateMany({where:{tenantId:req.tenantId,awsAccountId:req.awsAccountContext!.id},data:{connectionStatus:input.status}}).catch(()=>undefined);securityAudit.record({tenantId:req.tenantId,awsAccountId:req.awsAccountContext!.id,actorUserId:req.sessionUser!.id,action:input.status==='DISABLED'?'AWS_CONNECTION_DISABLED':'AWS_CONNECTION_ENABLED',outcome:'SUCCESS',metadata:{accountId:req.awsAccountContext!.accountId}});res.json({data:publicConnection(req.awsAccountContext!)})}));

router.get('/aws/identities/users',asyncHandler(async(req:AuthenticatedRequest,res)=>{const q=pagination.parse(req.query);const data=await identities(req).listUsers(q.search,q.pageSize);audit(req,'Identity discovery',undefined,'SUCCESS');res.json(page(data,q.page,q.pageSize))}));
router.get('/aws/identities/users/:userName',asyncHandler(async(req:AuthenticatedRequest,res)=>{const user=await identities(req).getUser(String(req.params.userName));if(!user)throw new ApiError(404,'IAM user not found','NOT_FOUND');res.json({data:user})}));
router.get('/aws/identities/roles',asyncHandler(async(req:AuthenticatedRequest,res)=>{const q=pagination.parse(req.query);const data=await identities(req).listRoles(q.search,String(req.query.includeServiceLinked)==='true',q.pageSize);audit(req,'Identity discovery',undefined,'SUCCESS');res.json(page(data,q.page,q.pageSize))}));
router.get('/aws/identities/roles/:roleName',asyncHandler(async(req:AuthenticatedRequest,res)=>{const role=await identities(req).getRole(String(req.params.roleName));if(!role)throw new ApiError(404,'IAM role not found','NOT_FOUND');res.json({data:role})}));

router.get('/aws/policies',asyncHandler(async(req:AuthenticatedRequest,res)=>{const q=pagination.parse(req.query);const result=await policies(req).list({...q,limit:q.limit??q.pageSize});audit(req,'Policy discovery',undefined,'SUCCESS',undefined,{loadedCount:result.loadedCount,cacheStatus:result.cacheStatus});res.json({data:result.items,pagination:{page:q.page,pageSize:q.limit??q.pageSize,total:result.loadedCount,totalPages:result.isComplete?Math.max(1,Math.ceil(result.loadedCount/(q.limit??q.pageSize))):q.page},nextCursor:result.nextCursor,isComplete:result.isComplete,loadedCount:result.loadedCount,cacheStatus:result.cacheStatus,timing:process.env.NODE_ENV==='production'?undefined:result.timing})}));
router.get('/aws/policies/:encodedArn',asyncHandler(async(req:AuthenticatedRequest,res)=>{const policy=await policies(req).get(String(req.params.encodedArn));if(!policy)throw new ApiError(404,'IAM policy not found','NOT_FOUND');res.json({data:policy})}));
router.post('/aws/policies/validate',asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=z.object({document:z.record(z.string(),z.unknown())}).parse(req.body);const result=await policyValidator(req).validate(input.document);audit(req,'Policy validation',undefined,'SUCCESS',undefined,{mode:result.mode,findings:Array.isArray(result.findings)?result.findings.length:0});res.json({data:result})}));

router.get('/aws/resources',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await resources(req).all()})));
router.get('/aws/resources/s3',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await resources(req).s3Resources()})));
router.get('/aws/resources/rds',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await resources(req).rdsResources()})));
router.get('/aws/resources/lambda',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await resources(req).lambdaResources()})));
router.get('/aws/identity-center/discover',asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:await new AwsIdentityCenterDiscoveryService().discover(req.sessionUser!,req.awsAccountContext!)})));
router.get('/aws/organisations/discover',authorize('ORGANISATION_ADMIN'),asyncHandler(async(req:AuthenticatedRequest,res)=>{if(!env.AWS_ORGANISATIONS_DISCOVERY_ENABLED)throw new ApiError(403,'AWS Organisations discovery is disabled.','FEATURE_DISABLED');const result=await new AwsOrganizationsService().discover(req.awsAccountContext!,String(req.query.refresh)==='true',req.sessionUser);audit(req,'AWS Organisation discovery',undefined,'SUCCESS',undefined,{accounts:result.accounts.length,organisationalUnits:result.organisationalUnits.length});res.json({data:result})}));
router.post('/aws/organisations/:organisationId/sync',authorize('ORGANISATION_ADMIN'),asyncHandler(async(req:AuthenticatedRequest,res)=>{if(!env.AWS_ORGANISATIONS_DISCOVERY_ENABLED)throw new ApiError(403,'AWS Organisations discovery is disabled.','FEATURE_DISABLED');const result=await new AwsOrganisationSyncService().syncOrganisation({actor:req.sessionUser!,tenantId:req.tenantId!,organisationConnectionId:String(req.params.organisationId),context:req.awsAccountContext!,forceRefresh:true});res.json({data:result})}));

router.get('/admin/directory',authorize('ORGANISATION_ADMIN'),asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:{tenants:identityDomain.tenantsFor(req.sessionUser!),organisations:developmentOrganisations.filter(item=>item.tenantId===req.tenantId),organisationalUnits:developmentOus,accounts:developmentAccounts.filter(item=>item.tenantId===req.tenantId),users:developmentUsers.filter(user=>user.memberships.some(m=>m.tenantId===req.tenantId)).map(user=>({id:user.id,email:user.email,displayName:user.displayName,memberships:user.memberships}))}})));
router.get('/admin/approval-policies',authorize('ORGANISATION_ADMIN'),asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:developmentAccounts.filter(account=>account.tenantId===req.tenantId).map(account=>({accountType:account.accountType,...approvalRouting.route({account,duration:'8 hours',permanent:false})}))})));
router.post('/admin/scopes',authorize('ORGANISATION_ADMIN'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=z.object({membershipId:z.string(),scopeType:z.enum(['TENANT','AWS_ORGANISATION','ORGANISATIONAL_UNIT','AWS_ACCOUNT']),scopeId:z.string(),includeDescendants:z.boolean().default(true),canView:z.boolean().default(true),canRequest:z.boolean().default(false),canApprove:z.boolean().default(false),canProvision:z.boolean().default(false),canRevoke:z.boolean().default(false),canManageConfiguration:z.boolean().default(false)}).parse(req.body);const membership=developmentUsers.flatMap(user=>user.memberships).find(item=>item.id===input.membershipId&&item.tenantId===req.tenantId);if(!membership)throw new ApiError(404,'Tenant membership not found.','NOT_FOUND');const existing=membership.scopes.find(scope=>scope.scopeType===input.scopeType&&scope.scopeId===input.scopeId);if(existing)Object.assign(existing,input);else membership.scopes.push(input);audit(req,'Admin scope assigned',undefined,'SUCCESS',undefined,{membershipId:input.membershipId,scopeType:input.scopeType,scopeId:input.scopeId});res.status(201).json({data:input})}));
router.post('/admin/accounts/onboarding',authorize('ORGANISATION_ADMIN'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=z.object({accountId:z.string().regex(/^\d{12}$/),accountName:z.string().min(2).max(100),connectionType:z.enum(['ORGANISATION_MEMBER','STANDALONE','EXTERNAL_CUSTOMER']),accountType:z.enum(['MANAGEMENT','SECURITY','LOG_ARCHIVE','SHARED_SERVICES','NETWORK','PRODUCTION','STAGING','DEVELOPMENT','SANDBOX','EXTERNAL']),defaultRegion:z.string().min(3),rolePath:z.string().max(128).default(''),readRoleArn:z.string().startsWith('arn:aws:iam::').optional(),provisionRoleArn:z.string().startsWith('arn:aws:iam::').optional(),externalIdSecretReference:z.string().optional()}).parse(req.body);if(developmentAccounts.some(account=>account.tenantId===req.tenantId&&account.accountId===input.accountId))throw new ApiError(409,'This AWS account is already configured for the active tenant.','AWS_ACCOUNT_EXISTS');const id=`account_${input.accountId}`,account={id,tenantId:req.tenantId!,accountId:input.accountId,accountName:input.accountName,accountType:input.accountType,environment:input.accountType.toLowerCase(),riskTier:input.accountType==='PRODUCTION'||input.accountType==='SECURITY'?'HIGH':'MODERATE',region:input.defaultRegion,connectionType:input.connectionType,connectionStatus:'PENDING' as const,provisioningStatus:'DISABLED' as const,provisioningEnabled:false,readRoleArn:input.readRoleArn??buildRoleArn(input.accountId,env.AWS_READ_ROLE_NAME,input.rolePath),provisionRoleArn:input.provisionRoleArn??buildRoleArn(input.accountId,env.AWS_PROVISION_ROLE_NAME,input.rolePath),externalIdSecretReference:input.externalIdSecretReference,organisationsRegion:env.AWS_ORGANISATIONS_REGION};developmentAccounts.push(account);const membership=req.sessionUser!.memberships.find(item=>item.tenantId===req.tenantId);membership?.scopes.push({scopeType:'AWS_ACCOUNT',scopeId:id,includeDescendants:true,canView:true,canRequest:true,canApprove:true,canProvision:true,canRevoke:true,canManageConfiguration:true});securityAudit.record({tenantId:req.tenantId,awsAccountId:id,actorUserId:req.sessionUser!.id,action:'AWS_ACCOUNT_ONBOARDING_CREATED',outcome:'SUCCESS',metadata:{accountId:input.accountId,connectionType:input.connectionType,externalIdConfigured:Boolean(input.externalIdSecretReference)}});res.status(201).json({data:{account:publicConnection(account),templatePath:'infrastructure/aws-onboarding/permissionhub-account-role.yaml',instructions:['Deploy the onboarding template in the target account.','Store the generated external ID in the configured server-side secret reference.','Return here and validate the read connection.']}})}));

router.get('/requests',asyncHandler(async(req:AuthenticatedRequest,res)=>{const q=pagination.parse(req.query),account=req.awsAccountContext!,mayReview=authorization.canApproveInAccount(req.sessionUser!,account.id)||authorization.canProvisionInAccount(req.sessionUser!,account.id)||authorization.canRevokeInAccount(req.sessionUser!,account.id)||authorization.canManageAccountConfiguration(req.sessionUser!,account.id);let data=requests.filter(r=>(!r.tenantId||r.tenantId===req.tenantId)&&(!r.awsAccountId||r.awsAccountId===account.id||r.awsAccountId===account.accountId)&&(mayReview||r.requesterUserId===req.sessionUser!.id||(!r.requesterUserId&&r.requester===req.sessionUser!.displayName)));if(q.status)data=data.filter(r=>r.status===q.status);if(q.search){const s=q.search.toLowerCase();data=data.filter(r=>(r.id+r.title+r.requester+r.approver+r.targetName+r.items.map(i=>i.policyName??i.actions?.join(' ')).join(' ')).toLowerCase().includes(s))}res.json(page(data,q.page,q.pageSize))}));
router.post('/requests',requireCapability('request'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=requestSchema.parse(req.body);assertRequest(input);const account=req.awsAccountContext!,route=approvalRouting.route({account,duration:input.duration,permanent:input.duration==='Permanent'});if(input.duration==='Permanent'&&!route.permanentAccessAllowed)throw new ApiError(422,`Permanent access is not allowed for ${account.accountType} accounts.`,'PERMANENT_NOT_ALLOWED');const created:PermissionRequest={id:nextRequestId(),tenantId:req.tenantId,awsOrganisationId:account.organisationId,ouId:account.ouId,awsAccountId:account.id,accountType:account.accountType,requesterUserId:req.sessionUser!.id,requester:req.sessionUser!.displayName,targetSubjectType:input.targetType,approvalPolicyId:route.policyId,requiredApprovalStages:route.requiredApprovalStages,provisioningAccountId:account.id,provisioningRoleArn:account.provisionRoleArn, status:'Draft',createdAt:new Date().toISOString(),timeline:[{label:'Draft created',timestamp:new Date().toISOString()}],...input};requests.unshift(created);audit(req,'Request created',created.id,'SUCCESS',undefined,{status:created.status,targetArn:created.targetArn,awsAccountId:account.accountId,approvalPolicyId:route.policyId});res.status(201).json({data:created,approvalRoute:route})}));
router.get('/requests/:id',asyncHandler(async(req,res)=>{const request=findRequest(String(req.params.id));res.json({data:{...request,preview:preview(request)}})}));
router.post('/requests/:id/submit',asyncHandler(async(req:AuthenticatedRequest,res)=>{const request=findRequest(String(req.params.id));if(request.requesterUserId&&request.requesterUserId!==req.sessionUser!.id)throw new ApiError(403,'Only the requester can submit this draft.','REQUEST_OWNER_REQUIRED');transition(request,'Pending approval','Submitted');request.submittedAt=new Date().toISOString();audit(req,'Request submitted',request.id,'SUCCESS',{status:'Draft'},{status:request.status});res.json({data:request})}));
router.post('/requests/:id/request-information',asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=commentSchema.parse(req.body);const request=findRequest(String(req.params.id));assertApprover(req,request);request.approvalComment=input.comment;transition(request,'More information required','More information requested');audit(req,'Approval decision',request.id,'SUCCESS',undefined,{status:request.status,comment:input.comment});res.json({data:request})}));
router.post('/requests/:id/approve',asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=commentSchema.parse(req.body);const request=findRequest(String(req.params.id));if(!authorization.canApproveRequest(req.sessionUser!,{...request,awsAccountId:request.awsAccountId??req.awsAccountContext!.id}))throw new ApiError(403,'You are not eligible for the current approval stage. Requesters cannot approve their own requests.','APPROVAL_FORBIDDEN');request.approvalComment=input.comment;const approvalStages=(request.requiredApprovalStages??['ACCOUNT_APPROVER']).filter(stage=>stage!=='PROVISIONER'),completed=request.completedApprovalStages??[],stage=approvalStages[completed.length]??'ACCOUNT_APPROVER';request.completedApprovalStages=[...completed,stage];const remaining=approvalStages.length-request.completedApprovalStages.length;if(remaining>0){request.timeline.push({label:`${stage.replaceAll('_',' ')} approved`,timestamp:new Date().toISOString(),result:`${remaining} approval stage${remaining===1?'':'s'} remaining`})}else transition(request,'Approved','Approved');audit(req,'Approval decision',request.id,'SUCCESS',undefined,{status:request.status,stage,comment:input.comment});res.json({data:{...request,preview:preview(request)}})}));
router.post('/requests/:id/reject',asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=commentSchema.parse(req.body);const request=findRequest(String(req.params.id));assertApprover(req,request);request.approvalComment=input.comment;transition(request,'Rejected','Rejected');audit(req,'Approval decision',request.id,'SUCCESS',undefined,{status:request.status,comment:input.comment});res.json({data:request})}));
router.post('/requests/:id/simulate',asyncHandler(async(req:AuthenticatedRequest,res)=>{const request=findRequest(String(req.params.id));const result=await simulator(req).simulate({targetArn:request.targetArn,actions:request.items.flatMap(i=>i.actions??[]),policyDocument:request.items.find(i=>i.generatedPolicyDocument)?.generatedPolicyDocument});request.simulationResult=result;request.timeline.push({label:'Simulation run',timestamp:new Date().toISOString(),result:'estimate'});audit(req,'Simulation run',request.id,'SUCCESS',undefined,result);res.json({data:{request,result,preview:preview(request)}})}));
router.post('/requests/:id/provision',(req:AuthenticatedRequest,_res,next)=>{const request=findRequest(String(req.params.id));if(request.expiryDate&&Date.parse(request.expiryDate)<=Date.now())return next(new ApiError(409,'This permission request has expired and cannot be provisioned.','REQUEST_EXPIRED'));next()});
router.post('/requests/:id/provision',asyncHandler(async(req:AuthenticatedRequest,res)=>{const request=findRequest(String(req.params.id));if(!authorization.canProvisionRequest(req.sessionUser!,{...request,awsAccountId:request.awsAccountId??req.awsAccountContext!.id}))throw new ApiError(403,'You are not authorised to provision this request.','PROVISIONING_FORBIDDEN');if(request.status!=='Approved')throw new ApiError(409,'Only approved requests can be provisioned','INVALID_STATE');transition(request,'Provisioning','Provisioning started');const provisioned:unknown[]=[];try{for(const item of request.items){if(item.mode==='SPECIFIC_ACTIONS'&&!item.generatedPolicyDocument)throw new Error('Specific-action requests require reviewed generated policy document before provisioning.');const service=provisioner(req);const policyArn=item.policyArn??String((await service.createCustomerPolicy(`PH-${request.id}-${Date.now()}`,item.generatedPolicyDocument!)).policyArn);const result=await service.attach({targetType:request.targetType,targetName:request.targetName,policyArn});provisioned.push(result);const grant:PermissionGrant={id:`grant_${Date.now()}_${grants.length}`,requestId:request.id,awsAccountId:req.awsAccountContext!.id,targetType:request.targetType,targetName:request.targetName,targetArn:request.targetArn,policyArn,attachedAt:new Date().toISOString(),expiresAt:request.expiryDate,provisioningResponse:result};grants.push(grant);audit(req,'Policy attached',request.id,'SUCCESS',undefined,{targetArn:request.targetArn,policyArn,result})}request.provisioningResult=provisioned;transition(request,'Provisioned','AWS operation completed');res.json({data:{request,provisioning:provisioned,grants:grants.filter(g=>g.requestId===request.id)}})}catch(error:any){transition(request,'Provisioning failed','Provisioning failed',error?.message);audit(req,'Provisioning failed',request.id,'FAILED',undefined,{error:error?.message});throw new ApiError(422,error?.message??'Provisioning failed','PROVISIONING_FAILED')}}));
router.post('/requests/:id/revoke',asyncHandler(async(req:AuthenticatedRequest,res)=>{const request=findRequest(String(req.params.id));const active=grants.filter(g=>g.requestId===request.id&&!g.revokedAt);if(!active.every(grant=>authorization.canRevokeGrant(req.sessionUser!,{...grant,awsAccountId:grant.awsAccountId??req.awsAccountContext!.id})))throw new ApiError(403,'You are not authorised to revoke this grant.','REVOCATION_FORBIDDEN');const revoked=[];for(const grant of active){const result=await provisioner(req).detach({targetType:grant.targetType,targetName:grant.targetName,policyArn:grant.policyArn});grant.revokedAt=new Date().toISOString();grant.revocationResponse=result;revoked.push(result);audit(req,'Policy detached',request.id,'SUCCESS',undefined,{policyArn:grant.policyArn,result})}transition(request,'Revoked','Access removed');res.json({data:{request,revoked}})}));

router.get('/activity',asyncHandler(async(req,res)=>{const q=pagination.parse(req.query);res.json(page(auditEvents,q.page,q.pageSize))}));
router.get('/approvers',(req:AuthenticatedRequest,res)=>{const account=req.awsAccountContext!;const eligible=developmentUsers.map(user=>identityDomain.sessionUser(user,'development')).filter(user=>user.id!==req.sessionUser!.id&&authorization.canApproveRequest(user,{awsAccountId:account.id,requesterUserId:req.sessionUser!.id})).map(user=>({id:user.id,name:user.displayName,email:user.email,role:user.memberships.find(m=>m.tenantId===account.tenantId)?.role}));res.json({data:eligible})});

function findRequest(id:string){const request=requests.find(r=>r.id===id);if(!request)throw new ApiError(404,'Permission request not found','NOT_FOUND');return request}
function assertApprover(req:AuthenticatedRequest,request:PermissionRequest){if(!authorization.canApproveRequest(req.sessionUser!,{...request,awsAccountId:request.awsAccountId??req.awsAccountContext!.id}))throw new ApiError(403,'You are not eligible to review this request. Requesters cannot review their own requests.','APPROVAL_FORBIDDEN')}
function nextRequestId(){const max=requests.reduce((current,request)=>Math.max(current,Number(request.id.match(/^PR-(\d+)$/)?.[1]??0)),1000);return `PR-${max+1}`}
function transition(request:PermissionRequest,status:RequestStatus,label:string,result?:string){const previous=request.status;request.status=status;request.timeline.push({label,timestamp:new Date().toISOString(),result:result??(previous!==status?status:undefined)})}
function assertRequest(input:z.infer<typeof requestSchema>){if(input.items.some(item=>item.policyArn?.endsWith('/AdministratorAccess')))throw new ApiError(422,'AdministratorAccess provisioning is explicitly blocked','BLOCKED_POLICY');if(input.duration==='Permanent'&&!input.notes)throw new ApiError(422,'Permanent access requires notes acknowledging the risk','PERMANENT_REQUIRES_NOTES')}
function preview(request:PermissionRequest){const identity=mockIdentities.find(i=>i.arn===request.targetArn);const existing=identity?.attachedPolicies??[];const requested=request.items.map(i=>({policyName:i.policyName,policyArn:i.policyArn,actions:i.actions}));return {estimate:true,before:{managedPolicies:existing,inlinePolicies:identity?.inlinePolicies??[],effectiveActions:'Available through IAM simulation where supported.'},change:{policiesToAttach:requested,policiesToDetach:[],resourceScope:request.scope,expiration:request.duration==='Permanent'?'No automatic expiry':request.expiryDate},after:{managedPolicies:[...existing,...request.items.filter(i=>i.policyName&&i.policyArn).map(i=>({policyName:i.policyName!,policyArn:i.policyArn!}))],newlyAllowedActions:request.items.flatMap(i=>i.actions??[]),riskFlags:request.items.some(i=>i.policyArn?.endsWith('/PowerUserAccess'))?['Broad write access outside IAM']:[]},awsOperation:request.targetType==='USER'?'AttachUserPolicy':'AttachRolePolicy'}};
function audit(req:AuthenticatedRequest,action:string,requestId?:string,result:'SUCCESS'|'FAILED'|'INFO'='SUCCESS',previousState?:unknown,newState?:unknown){auditEvents.unshift({id:`evt_${Date.now()}_${auditEvents.length}`,timestamp:new Date().toISOString(),actor:req.sessionUser?.displayName??'System',requestId,awsAccountId:req.awsAccountContext?.accountId,action,previousState,newState,result})}
function publicConnection(account:import('../types.js').AwsAccountContext){const {externalIdSecretReference:_,...safe}=account;return {...safe,externalIdConfigured:Boolean(account.externalIdSecretReference),provisionRoleConfigured:Boolean(account.provisionRoleArn)}}

export default router;
