import { randomUUID } from 'node:crypto';
import { Router } from 'express';
import { z } from 'zod';
import { env } from '../config/env.js';
import { logger } from '../config/logger.js';
import { prisma } from '../config/database.js';
import { requireConnectionAdmin } from '../middleware/auth.js';
import { awsAccountRepository } from '../services/aws-account.repository.js';
import { awsConnectionBroker } from '../services/aws/connection-broker.service.js';
import { cache } from '../services/cache.service.js';
import { identityDomain } from '../services/identity-domain.service.js';
import { securityAudit } from '../services/security-audit.service.js';
import type { AuthenticatedRequest,AwsAccountContext } from '../types.js';
import { ApiError,asyncHandler } from '../utils/http.js';

const router=Router();
router.use('/aws/accounts',requireConnectionAdmin);
router.use('/aws/local-credentials',requireConnectionAdmin);

const accountInput=z.object({accountName:z.string().min(2).max(100),accountId:z.string().regex(/^\d{12}$/),accountType:z.enum(['MANAGEMENT','SECURITY','LOG_ARCHIVE','SHARED_SERVICES','NETWORK','PRODUCTION','STAGING','DEVELOPMENT','SANDBOX','EXTERNAL']),defaultRegion:z.string().regex(/^[a-z]{2}(?:-gov)?-[a-z]+-\d$/),connectionType:z.enum(['LOCAL_DEFAULT_CREDENTIALS','ASSUME_ROLE']),readRoleArn:z.string().startsWith('arn:aws:iam::').optional(),provisionRoleArn:z.string().startsWith('arn:aws:iam::').optional(),externalIdSecretReference:z.string().min(1).optional(),validateLater:z.boolean().default(false)}).superRefine((value,ctx)=>{if(value.connectionType==='ASSUME_ROLE'&&!value.readRoleArn)ctx.addIssue({code:'custom',path:['readRoleArn'],message:'Read role ARN is required for AssumeRole connections.'})});
const updateInput=z.object({accountName:z.string().min(2).max(100).optional(),accountType:z.enum(['MANAGEMENT','SECURITY','LOG_ARCHIVE','SHARED_SERVICES','NETWORK','PRODUCTION','STAGING','DEVELOPMENT','SANDBOX','EXTERNAL']).optional(),defaultRegion:z.string().regex(/^[a-z]{2}(?:-gov)?-[a-z]+-\d$/).optional(),readRoleArn:z.string().startsWith('arn:aws:iam::').optional(),provisionRoleArn:z.string().startsWith('arn:aws:iam::').optional(),externalIdSecretReference:z.string().min(1).optional(),status:z.enum(['DISABLED','PENDING']).optional()});
const confirmation=z.object({confirm:z.literal(true)});

router.get('/aws/accounts',asyncHandler(async(req:AuthenticatedRequest,res)=>{const accounts=await awsAccountRepository.getManualAccountsForConnectionPage(req.tenantId!);res.json({data:accounts.map(publicAccount)})}));
router.post('/aws/local-credentials/validate',asyncHandler(async(_req:AuthenticatedRequest,res)=>res.json({data:await awsConnectionBroker.validateLocalCredentialSource()})));

router.post('/aws/accounts',asyncHandler(async(req:AuthenticatedRequest,res)=>{
 const input=accountInput.parse(req.body),tenantId=req.tenantId!,existing=await awsAccountRepository.findExistingForTenant(tenantId,input.accountId);
 if(existing){const authorised=identityDomain.account(req.sessionUser!,existing.id)!==undefined,manual=existing.sourceType==='MANUAL'&&!existing.isDemo;
  logger.debug({activeTenantId:tenantId,submittedAwsAccountId:input.accountId,existingAccountDatabaseId:existing.id,existingAccountTenantId:existing.tenantId,connectionRecordPresent:existing.hasConnection,sourceType:existing.sourceType,connectionSource:existing.connectionSource,connectionStatus:existing.connectionStatus,passesManualModeFilters:manual,authorised},'AWS account onboarding conflict');
  throw existingAccountConflict(existing);
 }
 const id=randomUUID(),account:AwsAccountContext={id,tenantId,accountId:input.accountId,accountName:input.accountName,accountType:input.accountType,environment:input.accountType.toLowerCase(),riskTier:['MANAGEMENT','SECURITY','PRODUCTION'].includes(input.accountType)?'HIGH':'MODERATE',region:input.defaultRegion,connectionType:input.connectionType,connectionStatus:'PENDING',sourceType:'MANUAL',connectionSource:'MANUAL',hasConnection:true,isDemo:false,readRoleArn:input.readRoleArn,provisionRoleArn:input.provisionRoleArn,externalIdSecretReference:input.externalIdSecretReference,provisioningStatus:'DISABLED',provisioningEnabled:false};
 await prisma.awsAccount.create({data:{id,tenantId,accountId:input.accountId,accountName:input.accountName,accountType:input.accountType,environment:account.environment,riskTier:account.riskTier,region:input.defaultRegion,connectionType:input.connectionType,connectionStatus:'PENDING',readRoleArn:input.readRoleArn,provisionRoleArn:input.provisionRoleArn,externalIdSecretReference:input.externalIdSecretReference,sourceType:'MANUAL',isDemo:false,manuallyCreatedAt:new Date(),connection:{create:{tenantId,connectionType:input.connectionType,connectionSource:'MANUAL',readRoleArn:input.readRoleArn,provisionRoleArn:input.provisionRoleArn,externalIdSecretReference:input.externalIdSecretReference,defaultRegion:input.defaultRegion,connectionStatus:'PENDING'}}}}).catch(error=>{logger.warn({activeTenantId:tenantId,submittedAwsAccountId:input.accountId,errorCode:(error as any)?.code},'AWS account create failed');throw new ApiError(503,'The AWS account could not be saved.','DATABASE_UNAVAILABLE')});
 identityDomain.addManualAccount(account);securityAudit.record({tenantId,awsAccountId:id,actorUserId:req.sessionUser!.id,action:'AWS_MANUAL_ACCOUNT_CREATED',outcome:'SUCCESS',metadata:{accountId:input.accountId,connectionType:input.connectionType,status:'PENDING'}});
 if(input.validateLater)return res.status(201).json({data:{account:publicAccount(account)}});
 try{const validation=await validateAndActivate(req,account);return res.status(201).json({data:{account:publicAccount(account),validation}})}catch(error){await prisma.awsAccount.delete({where:{id}}).catch(()=>undefined);identityDomain.removeManualAccount(tenantId,id);throw error}
}));

router.post('/aws/accounts/:accountId/repair-connection',asyncHandler(async(req:AuthenticatedRequest,res)=>{confirmation.parse(req.body);try{const account=await awsAccountRepository.repairMissingConnection(req.tenantId!,String(req.params.accountId));identityDomain.addManualAccount(account);securityAudit.record({tenantId:req.tenantId,awsAccountId:account.id,actorUserId:req.sessionUser!.id,action:'AWS_ACCOUNT_CONNECTION_REPAIRED',outcome:'SUCCESS',metadata:{accountId:account.accountId,status:'PENDING'}});res.json({data:publicAccount(account)})}catch(error){const code=error instanceof Error?error.message:'REPAIR_FAILED';throw new ApiError(code==='ACCOUNT_NOT_FOUND'?404:409,code==='CONVERSION_REQUIRED'?'Convert this demo or legacy account before repairing its connection.':'AWS account could not be repaired.',code)}}));
router.post('/aws/accounts/:accountId/convert-to-manual',asyncHandler(async(req:AuthenticatedRequest,res)=>{if(env.NODE_ENV==='production')throw new ApiError(404,'Not found.','NOT_FOUND');confirmation.parse(req.body);try{const account=await awsAccountRepository.convertToManual(req.tenantId!,String(req.params.accountId));identityDomain.addManualAccount(account);securityAudit.record({tenantId:req.tenantId,awsAccountId:account.id,actorUserId:req.sessionUser!.id,action:'AWS_ACCOUNT_CONVERTED_TO_MANUAL',outcome:'SUCCESS',metadata:{accountId:account.accountId,status:'PENDING'}});res.json({data:publicAccount(account)})}catch{throw new ApiError(404,'AWS account was not found in the active tenant.','ACCOUNT_NOT_FOUND')}}));
router.post('/aws/accounts/:accountId/validate',asyncHandler(async(req:AuthenticatedRequest,res)=>{const account=await awsAccountRepository.getAccountConnection(req.tenantId!,String(req.params.accountId));if(!account)throw new ApiError(404,'AWS account connection not found.','NOT_FOUND');if(!account.hasConnection)throw new ApiError(409,'Repair the missing connection record before validation.','AWS_CONNECTION_REPAIR_REQUIRED');res.json({data:await validateAndActivate(req,account)})}));
router.patch('/aws/accounts/:accountId',asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=updateInput.parse(req.body),account=await awsAccountRepository.getAccountConnection(req.tenantId!,String(req.params.accountId));if(!account)throw new ApiError(404,'AWS account connection not found.','NOT_FOUND');await prisma.$transaction([prisma.awsAccount.update({where:{id:account.id},data:{accountName:input.accountName,accountType:input.accountType,region:input.defaultRegion,readRoleArn:input.readRoleArn,provisionRoleArn:input.provisionRoleArn,externalIdSecretReference:input.externalIdSecretReference,connectionStatus:input.status}}),prisma.awsAccountConnection.update({where:{awsAccountId:account.id},data:{defaultRegion:input.defaultRegion,readRoleArn:input.readRoleArn,provisionRoleArn:input.provisionRoleArn,externalIdSecretReference:input.externalIdSecretReference,connectionStatus:input.status}})]);clearAccountCaches(req.tenantId!,account);if(input.status==='DISABLED'&&req.sessionUser!.activeAccountId===account.id)req.sessionUser!.activeAccountId=undefined;const updated=await awsAccountRepository.getAccountConnection(req.tenantId!,account.id);res.json({data:publicAccount(updated!)})}));
router.delete('/aws/accounts/:accountId',asyncHandler(async(req:AuthenticatedRequest,res)=>{const account=await awsAccountRepository.getAccountConnection(req.tenantId!,String(req.params.accountId));if(!account)throw new ApiError(404,'AWS account connection not found.','NOT_FOUND');await prisma.awsAccount.delete({where:{id:account.id}});identityDomain.removeManualAccount(req.tenantId!,account.id);clearAccountCaches(req.tenantId!,account);if(req.sessionUser!.activeAccountId===account.id)req.sessionUser!.activeAccountId=undefined;securityAudit.record({tenantId:req.tenantId,awsAccountId:account.id,actorUserId:req.sessionUser!.id,action:'AWS_MANUAL_ACCOUNT_REMOVED',outcome:'SUCCESS',metadata:{accountId:account.accountId}});res.json({data:{removed:true}})}));

async function validateAndActivate(req:AuthenticatedRequest,account:AwsAccountContext){const identity=await awsConnectionBroker.validateAccountConnection(req.sessionUser!,account.id,'READ'),checks=await awsConnectionBroker.testReadCapabilities(req.sessionUser!,account.id),status=checks.iamUsersReadable&&checks.iamRolesReadable&&checks.policiesReadable?'CONNECTED':'DEGRADED';account.connectionStatus=status;account.lastValidatedAt=new Date().toISOString();await prisma.$transaction([prisma.awsAccount.update({where:{id:account.id},data:{connectionStatus:status}}),prisma.awsAccountConnection.update({where:{awsAccountId:account.id},data:{connectionStatus:status,lastValidatedAt:new Date(),lastErrorCode:null,lastErrorMessage:null}})]);identityDomain.addManualAccount(account);let activated=false;if(status==='CONNECTED'){const usable=await awsAccountRepository.getUsableConnectedAccountsForAwsOperations(req.tenantId!,req.sessionUser!);if(usable.length===1){req.sessionUser!.activeAccountId=account.id;req.session.user=req.sessionUser;await new Promise<void>((resolve,reject)=>req.session.save(error=>error?reject(error):resolve()));activated=true}}return {success:true,expectedAccountId:account.accountId,actualAccountId:identity.accountId,callerArn:identity.principalArn,connectionType:account.connectionType,capabilities:{sts:true,iamUsers:checks.iamUsersReadable,iamRoles:checks.iamRolesReadable,iamPolicies:checks.policiesReadable},validatedAt:account.lastValidatedAt,status,activeAccountSet:activated}}
function clearAccountCaches(tenantId:string,account:AwsAccountContext){awsConnectionBroker.invalidateAccount(tenantId,account.accountId);cache.deleteContaining(`${tenantId}:${account.accountId}:`)}
function publicAccount(account:AwsAccountContext){const {externalIdSecretReference:_,...safe}=account;return {...safe,externalIdConfigured:Boolean(account.externalIdSecretReference),provisionRoleConfigured:Boolean(account.provisionRoleArn)}}
export function existingAccountConflict(existing:AwsAccountContext){const manual=existing.sourceType==='MANUAL'&&!existing.isDemo;return new ApiError(409,'This AWS account already exists for the active tenant.','AWS_ACCOUNT_ALREADY_EXISTS',{existingAccountId:existing.id,connectionStatus:existing.connectionStatus,sourceType:existing.sourceType??'LEGACY',connectionPresent:existing.hasConnection,canValidate:Boolean(manual&&existing.hasConnection),canEdit:manual,canRemove:manual,canRepair:Boolean(manual&&!existing.hasConnection),canConvert:env.NODE_ENV!=='production'&&!manual})}

export default router;
