import { Router } from 'express';
import { z } from 'zod';
import { env } from '../config/env.js';
import { logger } from '../config/logger.js';
import { prisma } from '../config/database.js';
import { requireNamedCapability } from '../middleware/auth.js';
import { awsAccountRepository,type ManualAccountInput } from '../services/aws-account.repository.js';
import { buildEncryptedStaticCredentials } from '../services/credential-encryption.service.js';
import { awsConnectionBroker,sanitiseAwsConnectionError } from '../services/aws/connection-broker.service.js';
import { cache } from '../services/cache.service.js';
import { identityDomain,saveSessionPreferences } from '../services/identity-domain.service.js';
import { securityAudit } from '../services/security-audit.service.js';
import type { AuthenticatedRequest,AwsAccountContext } from '../types.js';
import { ApiError,asyncHandler } from '../utils/http.js';

const router=Router();
const connectionTypeSchema=z.enum(['LOCAL_DEFAULT_CREDENTIALS','ACCESS_KEYS','ASSUME_ROLE']);
const optionalTrimmed=z.string().trim().optional().transform(value=>value||undefined);
const accountInput=z.object({accountName:z.string().min(2).max(100),accountId:z.string().regex(/^\d{12}$/).optional(),awsAccountNumber:z.string().regex(/^\d{12}$/).optional(),accountType:z.enum(['MANAGEMENT','SECURITY','LOG_ARCHIVE','SHARED_SERVICES','NETWORK','PRODUCTION','STAGING','DEVELOPMENT','SANDBOX','EXTERNAL']),defaultRegion:z.string().regex(/^[a-z]{2}(?:-gov)?-[a-z]+-\d$/),connectionType:connectionTypeSchema,readRoleArn:z.string().startsWith('arn:aws:iam::').optional(),provisionRoleArn:z.string().startsWith('arn:aws:iam::').optional(),externalIdSecretReference:z.string().min(1).optional(),accessKeyId:optionalTrimmed,secretAccessKey:optionalTrimmed,sessionToken:optionalTrimmed,validateLater:z.boolean().default(false)}).superRefine((value,ctx)=>{if(!value.accountId&&!value.awsAccountNumber)ctx.addIssue({code:'custom',path:['awsAccountNumber'],message:'AWS account number is required.'});if(value.accountId&&value.awsAccountNumber&&value.accountId!==value.awsAccountNumber)ctx.addIssue({code:'custom',path:['awsAccountNumber'],message:'AWS account number fields do not match.'});if(value.connectionType==='ASSUME_ROLE'&&!value.readRoleArn)ctx.addIssue({code:'custom',path:['readRoleArn'],message:'Read role ARN is required for AssumeRole connections.'});if(value.connectionType==='ACCESS_KEYS'){if(!value.accessKeyId)ctx.addIssue({code:'custom',path:['accessKeyId'],message:'Access Key ID is required.'});if(!value.secretAccessKey)ctx.addIssue({code:'custom',path:['secretAccessKey'],message:'Secret Access Key is required.'})}});
const updateInput=z.object({accountName:z.string().min(2).max(100).optional(),accountType:z.enum(['MANAGEMENT','SECURITY','LOG_ARCHIVE','SHARED_SERVICES','NETWORK','PRODUCTION','STAGING','DEVELOPMENT','SANDBOX','EXTERNAL']).optional(),defaultRegion:z.string().regex(/^[a-z]{2}(?:-gov)?-[a-z]+-\d$/).optional(),connectionType:connectionTypeSchema.optional(),readRoleArn:z.string().startsWith('arn:aws:iam::').optional(),provisionRoleArn:z.string().startsWith('arn:aws:iam::').optional(),externalIdSecretReference:z.string().min(1).optional(),accessKeyId:optionalTrimmed,secretAccessKey:optionalTrimmed,sessionToken:optionalTrimmed,provisioningEnabled:z.boolean().optional(),status:z.enum(['DISABLED','PENDING']).optional()});
const staticCredentialValidation=z.object({accountId:z.string().regex(/^\d{12}$/).optional(),awsAccountNumber:z.string().regex(/^\d{12}$/).optional(),defaultRegion:z.string().regex(/^[a-z]{2}(?:-gov)?-[a-z]+-\d$/),accessKeyId:z.string().trim().min(8),secretAccessKey:z.string().trim().min(8),sessionToken:optionalTrimmed}).superRefine((value,ctx)=>{if(value.accountId&&value.awsAccountNumber&&value.accountId!==value.awsAccountNumber)ctx.addIssue({code:'custom',path:['awsAccountNumber'],message:'AWS account number fields do not match.'})});
const confirmation=z.object({confirm:z.literal(true)});

router.get('/debug/runtime',asyncHandler(async(req:AuthenticatedRequest,res)=>{
 if(env.NODE_ENV==='production'||!env.ENABLE_RUNTIME_DEBUG)throw new ApiError(404,'Not found.','NOT_FOUND');
 const configured=safeDatabaseTarget(env.DATABASE_URL),database=await prisma.$queryRawUnsafe<Array<{databaseName:string;databaseSchema:string}>>('SELECT current_database() AS "databaseName", current_schema() AS "databaseSchema"');
 res.json({data:{backendProcessId:String(process.pid),databaseHost:configured.host,databasePort:configured.port,databaseName:database[0]?.databaseName??configured.name,databaseSchema:database[0]?.databaseSchema??configured.schema,activeTenantId:req.tenantId,activeUserId:req.sessionUser?.id,activeUserRole:req.auth?.role,awsConnectionMode:env.AWS_CONNECTION_MODE,demoDataEnabled:env.ENABLE_AWS_DEMO_DATA,buildCommit:env.BUILD_COMMIT}});
}));

router.post('/aws/active-account',asyncHandler(async(req:AuthenticatedRequest,res)=>{
 const {accountRecordId}=z.object({accountRecordId:z.string().uuid()}).parse(req.body),account=await awsAccountRepository.getByRecordId(req.tenantId!,accountRecordId);
 if(!account||!identityDomain.account(req.sessionUser!,accountRecordId))throw new ApiError(403,'AWS account selection is not permitted.','AWS_ACCOUNT_FORBIDDEN');
 if(!['CONNECTED','DEGRADED'].includes(account.connectionStatus))throw new ApiError(409,'Only validated AWS accounts can be selected.','AWS_ACCOUNT_NOT_CONNECTED');
 setActiveAccount(req,accountRecordId);await saveSessionPreferences(req.sessionUser!);await saveSession(req);res.json({data:{activeAwsAccountRecordId:accountRecordId,account:publicAccount(account)}});
}));

router.get('/aws/accounts',requireNamedCapability('CONNECTION_VIEW'),asyncHandler(async(req:AuthenticatedRequest,res)=>res.json({data:(await awsAccountRepository.getManualAccountsForConnectionPage(req.tenantId!)).map(publicAccount)})));
router.get('/aws/accounts/:accountRecordId',requireNamedCapability('CONNECTION_VIEW'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const account=await awsAccountRepository.getByRecordId(req.tenantId!,String(req.params.accountRecordId));if(!account||!identityDomain.account(req.sessionUser!,account.id))throw new ApiError(404,'AWS account record not found.','AWS_ACCOUNT_NOT_FOUND');res.json({data:publicAccount(account)})}));
router.post('/aws/local-credentials/validate',requireNamedCapability('CONNECTION_MANAGE'),asyncHandler(async(_req:AuthenticatedRequest,res)=>res.json({data:await awsConnectionBroker.validateLocalCredentialSource()})));
router.post('/aws/access-keys/validate',requireNamedCapability('CONNECTION_MANAGE'),asyncHandler(async(req:AuthenticatedRequest,res)=>{
 const parsed=staticCredentialValidation.parse(req.body),expectedAccountId=parsed.awsAccountNumber??parsed.accountId;
 const validation=await awsConnectionBroker.validateStaticCredentials({region:parsed.defaultRegion,expectedAccountId,accessKeyId:parsed.accessKeyId,secretAccessKey:parsed.secretAccessKey,sessionToken:parsed.sessionToken});
 securityAudit.record({tenantId:req.tenantId,actorUserId:req.sessionUser!.id,action:'AWS_STATIC_CREDENTIALS_VALIDATED',outcome:'SUCCESS',metadata:{expectedAccountId,actualAccountId:validation.accountId,region:parsed.defaultRegion}});
 res.json({data:validation});
}));
router.post('/aws/accounts',requireNamedCapability('CONNECTION_MANAGE'),onboard);
router.put('/aws/accounts/by-account-id/:awsAccountNumber',requireNamedCapability('CONNECTION_MANAGE'),onboard);

async function onboard(req:AuthenticatedRequest,res:any){
 const parsed=accountInput.parse(req.body),awsAccountNumber=String(req.params.awsAccountNumber??parsed.awsAccountNumber??parsed.accountId),tenantId=req.tenantId!,input:ManualAccountInput={...parsed,awsAccountNumber};
 logger.info({event:'aws_account_onboarding_started',routeHandlerReached:true,correlationId:req.correlationId,activeTenantId:tenantId,activeUserId:req.sessionUser!.id,submittedAwsAccountNumber:awsAccountNumber,prismaOperation:'transaction.findUnique/create/recover'},'AWS account onboarding started');
 try{
  const result=await awsAccountRepository.onboardManualAccount(tenantId,input),account=result.account;
  logger.info({event:'aws_account_onboarding_resolved',correlationId:req.correlationId,activeTenantId:tenantId,submittedAwsAccountNumber:awsAccountNumber,duplicateLookupResult:result.outcome!=='CREATED',existingAccountRecordId:account.id,existingConnectionPresent:account.hasConnection,existingConnectionSource:account.connectionSource,existingSourceType:account.sourceType,existingStatus:account.connectionStatus,prismaConflictRecovered:result.prismaConflictRecovered,finalResponseCode:result.outcome==='CONVERSION_REQUIRED'?'LEGACY_ACCOUNT_CONFLICT':'AWS_ACCOUNT_ONBOARDED'},'AWS account onboarding resolved');
  if(result.outcome==='CONVERSION_REQUIRED')throw recoverableConflict(account,'LEGACY_ACCOUNT_CONFLICT','This AWS account exists as a legacy or development record and must be explicitly converted.');
  identityDomain.addManualAccount(account);securityAudit.record({tenantId,awsAccountId:account.id,actorUserId:req.sessionUser!.id,action:result.outcome==='CREATED'?'AWS_MANUAL_ACCOUNT_CREATED':'AWS_MANUAL_ACCOUNT_RECOVERED',outcome:'SUCCESS',metadata:{awsAccountNumber,outcome:result.outcome,status:account.connectionStatus}});
  const validation=parsed.validateLater?undefined:await validateAndActivate(req,account);
  const refreshed=(await awsAccountRepository.getByRecordId(tenantId,account.id))??account;
  return res.status(result.outcome==='CREATED'?201:200).json({data:{account:publicAccount(refreshed),onboardingResult:result.outcome,validation}});
 }catch(error){
  if(error instanceof ApiError)throw error;
  const prismaCode=(error as {code?:string})?.code,code=prismaCode==='P2002'?'TENANT_ACCOUNT_UNIQUE_CONFLICT':'DATABASE_WRITE_FAILED';
  logger.error({event:'aws_account_onboarding_failed',correlationId:req.correlationId,activeTenantId:tenantId,submittedAwsAccountNumber:awsAccountNumber,prismaOperation:'transaction.findUnique/create/recover',prismaErrorCode:prismaCode,finalResponseCode:code},'AWS account onboarding failed');
  throw new ApiError(prismaCode==='P2002'?409:503,prismaCode==='P2002'?'The tenant account conflict could not be recovered.':'The AWS account could not be saved.',code);
 }
}

router.post('/aws/accounts/:accountRecordId/repair-connection',requireNamedCapability('CONNECTION_MANAGE'),asyncHandler(async(req:AuthenticatedRequest,res)=>{confirmation.parse(req.body);try{const account=await awsAccountRepository.repairMissingConnection(req.tenantId!,String(req.params.accountRecordId));identityDomain.addManualAccount(account);securityAudit.record({tenantId:req.tenantId,awsAccountId:account.id,actorUserId:req.sessionUser!.id,action:'AWS_ACCOUNT_CONNECTION_REPAIRED',outcome:'SUCCESS',metadata:{awsAccountNumber:account.accountId,status:'PENDING'}});res.json({data:publicAccount(account)})}catch(error){const code=error instanceof Error?error.message:'REPAIR_FAILED';throw new ApiError(code==='ACCOUNT_NOT_FOUND'?404:409,code==='CONVERSION_REQUIRED'?'Convert this demo or legacy account before repairing its connection.':'AWS account could not be repaired.',code==='CONVERSION_REQUIRED'?'LEGACY_ACCOUNT_CONFLICT':'AWS_CONNECTION_REPAIR_FAILED')}}));
router.post('/aws/accounts/:accountRecordId/convert-to-manual',requireNamedCapability('CONNECTION_MANAGE'),asyncHandler(async(req:AuthenticatedRequest,res)=>{if(env.NODE_ENV==='production')throw new ApiError(404,'Not found.','NOT_FOUND');confirmation.parse(req.body);try{const account=await awsAccountRepository.convertToManual(req.tenantId!,String(req.params.accountRecordId));identityDomain.addManualAccount(account);res.json({data:publicAccount(account)})}catch{throw new ApiError(404,'AWS account was not found in the active tenant.','AWS_ACCOUNT_NOT_FOUND')}}));
router.post('/aws/accounts/:accountRecordId/validate',requireNamedCapability('CONNECTION_MANAGE'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const account=await awsAccountRepository.getByRecordId(req.tenantId!,String(req.params.accountRecordId));if(!account)throw new ApiError(404,'AWS account connection not found.','AWS_ACCOUNT_NOT_FOUND');if(!account.hasConnection)throw new ApiError(409,'Repair the missing connection record before validation.','AWS_CONNECTION_REPAIR_REQUIRED');identityDomain.addManualAccount(account);res.json({data:await validateAndActivate(req,account)})}));
router.post('/aws/accounts/:accountRecordId/validate-provision-role',requireNamedCapability('CONNECTION_MANAGE'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const account=await awsAccountRepository.getByRecordId(req.tenantId!,String(req.params.accountRecordId));if(!account)throw new ApiError(404,'AWS account connection not found.','AWS_ACCOUNT_NOT_FOUND');if(!account.provisionRoleArn)throw new ApiError(422,'Configure a separate provisioning role before validation.','PROVISION_ROLE_REQUIRED');identityDomain.addManualAccount(account);const validation=await awsConnectionBroker.validateAccountConnection(req.sessionUser!,account.id,'PROVISION',true),policySimulation=await awsConnectionBroker.testProvisionCapabilities(req.sessionUser!,account.id),refreshed=await awsAccountRepository.getByRecordId(req.tenantId!,account.id);if(refreshed)identityDomain.addManualAccount(refreshed);res.json({data:{account:publicAccount(refreshed??account),validation,mutationPerformed:false,policySimulation}})}));
router.patch('/aws/accounts/:accountRecordId',requireNamedCapability('CONNECTION_MANAGE'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const input=updateInput.parse(req.body),account=await awsAccountRepository.getByRecordId(req.tenantId!,String(req.params.accountRecordId));if(!account)throw new ApiError(404,'AWS account connection not found.','AWS_ACCOUNT_NOT_FOUND');const credentialData=input.connectionType==='ACCESS_KEYS'&&input.accessKeyId&&input.secretAccessKey?buildEncryptedStaticCredentials({accessKeyId:input.accessKeyId,secretAccessKey:input.secretAccessKey,sessionToken:input.sessionToken}):{};await prisma.$transaction([prisma.awsAccount.update({where:{id:account.id},data:{accountName:input.accountName,accountType:input.accountType,region:input.defaultRegion,connectionType:input.connectionType,readRoleArn:input.readRoleArn,provisionRoleArn:input.provisionRoleArn,externalIdSecretReference:input.externalIdSecretReference,connectionStatus:input.status??(Object.keys(credentialData).length?'PENDING':undefined)}}),prisma.awsAccountConnection.update({where:{awsAccountId:account.id},data:{connectionType:input.connectionType,defaultRegion:input.defaultRegion,readRoleArn:input.readRoleArn,provisionRoleArn:input.provisionRoleArn,externalIdSecretReference:input.externalIdSecretReference,provisioningEnabled:input.provisioningEnabled,provisionRoleStatus:input.provisionRoleArn&&input.provisionRoleArn!==account.provisionRoleArn?'NOT_VALIDATED':undefined,provisionRoleLastValidatedAt:input.provisionRoleArn&&input.provisionRoleArn!==account.provisionRoleArn?null:undefined,connectionStatus:input.status??(Object.keys(credentialData).length?'PENDING':undefined),...credentialData}})]);clearAccountCaches(req.tenantId!,account);if(input.status==='DISABLED'&&activeRecordId(req)===account.id){setActiveAccount(req,undefined);await saveSessionPreferences(req.sessionUser!);await saveSession(req)}const updated=await awsAccountRepository.getByRecordId(req.tenantId!,account.id);identityDomain.addManualAccount(updated!);res.json({data:publicAccount(updated!)})}));
router.delete('/aws/accounts/:accountRecordId',requireNamedCapability('CONNECTION_MANAGE'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const account=await awsAccountRepository.getByRecordId(req.tenantId!,String(req.params.accountRecordId));if(!account)throw new ApiError(404,'AWS account connection not found.','AWS_ACCOUNT_NOT_FOUND');await prisma.awsAccount.delete({where:{id:account.id}});identityDomain.removeManualAccount(req.tenantId!,account.id);clearAccountCaches(req.tenantId!,account);if(activeRecordId(req)===account.id){setActiveAccount(req,undefined);await saveSessionPreferences(req.sessionUser!);await saveSession(req)}res.json({data:{removed:true}})}));
router.post('/aws/accounts/:accountRecordId/reset',requireNamedCapability('CONNECTION_MANAGE'),asyncHandler(async(req:AuthenticatedRequest,res)=>{if(env.NODE_ENV==='production')throw new ApiError(404,'Not found.','NOT_FOUND');const {dryRun,confirm}=z.object({dryRun:z.boolean().default(true),confirm:z.boolean().default(false)}).parse(req.body),account=await awsAccountRepository.getByRecordId(req.tenantId!,String(req.params.accountRecordId));if(!account)throw new ApiError(404,'AWS account connection not found.','AWS_ACCOUNT_NOT_FOUND');const relatedRequestCount=await prisma.request.count({where:{tenantId:req.tenantId!,awsAccountId:account.id}}),canReset=relatedRequestCount===0;if(dryRun||!confirm)return res.json({data:{dryRun:true,account:publicAccount(account),relatedRequestCount,canReset}});if(!canReset)throw new ApiError(409,'This account has request history and cannot be reset. Disable it instead.','AWS_ACCOUNT_RESET_BLOCKED_BY_HISTORY',{relatedRequestCount});await prisma.awsAccount.delete({where:{id:account.id}});identityDomain.removeManualAccount(req.tenantId!,account.id);clearAccountCaches(req.tenantId!,account);if(activeRecordId(req)===account.id){setActiveAccount(req,undefined);await saveSessionPreferences(req.sessionUser!);await saveSession(req)}res.json({data:{dryRun:false,removed:true,accountRecordId:account.id}})}));

async function validateAndActivate(req:AuthenticatedRequest,account:AwsAccountContext){
 try{
  const identity=await awsConnectionBroker.validateAccountConnection(req.sessionUser!,account.id,'READ'),checks=await awsConnectionBroker.testReadCapabilities(req.sessionUser!,account.id),status=checks.iamUsersReadable&&checks.iamRolesReadable&&checks.policiesReadable?'CONNECTED':'DEGRADED',now=new Date();
  account.connectionStatus=status;account.lastValidatedAt=now.toISOString();await prisma.$transaction([prisma.awsAccount.update({where:{id:account.id},data:{connectionStatus:status}}),prisma.awsAccountConnection.update({where:{awsAccountId:account.id},data:{connectionStatus:status,lastValidatedAt:now,lastErrorCode:null,lastErrorMessage:null}})]);identityDomain.addManualAccount(account);
  let activeAccountSet=false;if(status==='CONNECTED'&&(await awsAccountRepository.getUsableConnectedAccountsForAwsOperations(req.tenantId!,req.sessionUser!)).length===1){setActiveAccount(req,account.id);await saveSessionPreferences(req.sessionUser!);await saveSession(req);activeAccountSet=true}
  return {success:true,accountRecordId:account.id,expectedAwsAccountNumber:account.accountId,actualAwsAccountNumber:identity.accountId,callerArn:identity.principalArn,connectionType:account.connectionType,capabilities:{sts:true,iamUsers:checks.iamUsersReadable,iamRoles:checks.iamRolesReadable,iamPolicies:checks.policiesReadable},validatedAt:account.lastValidatedAt,status,activeAccountSet};
 }catch(error){const safe=sanitiseAwsConnectionError(error),now=new Date();account.connectionStatus='ERROR';account.lastErrorCode=safe.code;account.lastErrorMessage=safe.message;await prisma.$transaction([prisma.awsAccount.update({where:{id:account.id},data:{connectionStatus:'ERROR'}}),prisma.awsAccountConnection.update({where:{awsAccountId:account.id},data:{connectionStatus:'ERROR',lastValidatedAt:now,lastErrorCode:safe.code,lastErrorMessage:safe.message}})]);identityDomain.addManualAccount(account);return {success:false,accountRecordId:account.id,expectedAwsAccountNumber:account.accountId,status:'ERROR',errorCode:safe.code,message:safe.message,validatedAt:now.toISOString(),activeAccountSet:false}}
}
function availableActions(account:AwsAccountContext){const actions=['EDIT','REMOVE'];if(!account.hasConnection)actions.unshift('REPAIR');else actions.unshift('VALIDATE');if(['CONNECTED','DEGRADED'].includes(account.connectionStatus))actions.unshift('SELECT');if(env.NODE_ENV!=='production')actions.push('RESET');return actions}
function publicAccount(account:AwsAccountContext){const {externalIdSecretReference:_,...safe}=account;return {...safe,id:account.id,accountRecordId:account.id,accountId:account.accountId,awsAccountNumber:account.accountId,availableActions:availableActions(account),externalIdConfigured:Boolean(account.externalIdSecretReference),provisionRoleConfigured:Boolean(account.provisionRoleArn)}}
export function recoverableConflict(account:AwsAccountContext,code:string,message:string){return new ApiError(409,message,code,{account:publicAccount(account),existingAccountRecordId:account.id,existingAwsAccountNumber:account.accountId,connectionStatus:account.connectionStatus,sourceType:account.sourceType??'LEGACY',connectionPresent:account.hasConnection,availableActions:['CONVERT','REMOVE'],canConvert:env.NODE_ENV!=='production',canRemove:true})}
function clearAccountCaches(tenantId:string,account:AwsAccountContext){awsConnectionBroker.invalidateAccount(tenantId,account.accountId);cache.deleteContaining(`${tenantId}:${account.accountId}:`)}
function activeRecordId(req:AuthenticatedRequest){return req.sessionUser?.activeAwsAccountRecordId??req.sessionUser?.activeAccountId}
function setActiveAccount(req:AuthenticatedRequest,value:string|undefined){if(!req.sessionUser)return;req.sessionUser.activeAwsAccountRecordId=value;req.sessionUser.activeAccountId=value;req.session.user=req.sessionUser}
function saveSession(req:AuthenticatedRequest){return new Promise<void>((resolve,reject)=>req.session.save(error=>error?reject(error):resolve()))}
function safeDatabaseTarget(value:string){try{const url=new URL(value);return {host:url.hostname,port:url.port||'5432',name:url.pathname.replace(/^\//,'')||'unknown',schema:url.searchParams.get('schema')??'public'}}catch{return {host:'invalid',port:'unknown',name:'unknown',schema:'unknown'}}}
export default router;
