ALTER TABLE "Request"
  ADD COLUMN IF NOT EXISTS "group" JSONB,
  ADD COLUMN IF NOT EXISTS "role" JSONB,
  ADD COLUMN IF NOT EXISTS "members" JSONB,
  ADD COLUMN IF NOT EXISTS "approvalComment" TEXT,
  ADD COLUMN IF NOT EXISTS "provisioningResult" JSONB,
  ADD COLUMN IF NOT EXISTS "simulationResult" JSONB,
  ADD COLUMN IF NOT EXISTS "timeline" JSONB NOT NULL DEFAULT '[]';

ALTER TABLE "RequestItem"
  ADD COLUMN IF NOT EXISTS "operation" TEXT,
  ADD COLUMN IF NOT EXISTS "generatedPolicyName" TEXT,
  ADD COLUMN IF NOT EXISTS "requestedPolicyName" TEXT;
