import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Building2,Network,ShieldCheck,Users} from 'lucide-react';
import {api} from '../lib/api';

type Tab='accounts'|'memberships'|'scopes'|'rules'|'development';
export default function Administration(){
 const [tab,setTab]=useState<Tab>('accounts'),directory=useQuery({queryKey:['admin-directory'],queryFn:api.adminDirectory}),policies=useQuery({queryKey:['approval-policies'],queryFn:api.approvalPolicies}),queryClient=useQueryClient(),save=useMutation({mutationFn:api.saveScope,onSuccess:()=>queryClient.invalidateQueries({queryKey:['admin-directory']})});
 if(directory.isLoading)return <div className="page"><div className="panel">Loading authorised administration data…</div></div>;
 if(directory.error)return <div className="page"><div className="error-box">You do not have organisation administration access.</div></div>;
 const data=directory.data,tabs:Tab[]=['accounts','memberships','scopes','rules',...(data.development?['development' as const]:[])];
 return <div className="page"><header className="page-header"><div><p className="eyebrow">Tenant administration</p><h1>Access configuration</h1><p>Manage delegated scopes and approval routing without granting platform-wide AWS access.</p></div></header><div className="tabs admin-tabs">{tabs.map(value=><button className={tab===value?'active':''} onClick={()=>setTab(value)} key={value}>{value.replace(/^./,c=>c.toUpperCase())}</button>)}</div>
 {tab==='accounts'&&<section className="panel"><h2><Network size={18}/> Organisation and account browser</h2>{data.accounts.map((account:any)=><div className="account-row" key={account.id}><span><strong>{account.accountName}</strong><small>{account.accountId} · {account.region}</small></span><em>{account.accountType.replaceAll('_',' ')}</em><i>{account.connectionStatus}</i></div>)}</section>}
 {tab==='memberships'&&<section className="panel"><h2><Users size={18}/> Tenant memberships</h2><div className="membership-list">{data.users.map((user:any)=><article key={user.id}><span><strong>{user.displayName}</strong><small>{user.email}</small></span>{user.memberships.map((membership:any)=><em key={membership.id}>{membership.role.replaceAll('_',' ')}</em>)}</article>)}</div></section>}
 {tab==='scopes'&&<ScopeAssignment data={data} onSave={payload=>save.mutate(payload)} busy={save.isPending}/>}
 {tab==='rules'&&<section className="panel"><h2><ShieldCheck size={18}/> Approval rules</h2><div className="rule-list">{policies.data?.map((policy:any)=><article key={policy.accountType}><strong>{policy.accountType.replaceAll('_',' ')}</strong><span>{policy.requiredApprovalStages.join(' → ')}</span><small>{policy.provisioningMode} provisioning · Permanent {policy.permanentAccessAllowed?'allowed':'restricted'}</small></article>)}</div></section>}
 {tab==='development'&&data.development&&<DevelopmentPanel data={data.development}/>}</div>;
}

function DevelopmentPanel({data}:{data:any}){return <section className="panel"><h2>Development request access</h2><p className="warning">Development only. These controls do not weaken production authorisation or configure AWS credentials.</p><dl className="detail-dl"><Row label="Current user" value={`${data.currentUser.email} · ${data.currentUser.roles.join(', ')||'No active-account roles'}`}/><Row label="Active tenant" value={data.activeTenantId}/><Row label="Active account" value={data.activeAccount?`${data.activeAccount.name} (${data.activeAccount.awsAccountNumber})`:'None'}/><Row label="Provisioning mode" value={data.provisioningMode}/><Row label="Cross-account provisioning" value={String(data.crossAccountProvisioningEnabled)}/><Row label="Self approval" value={String(data.selfApprovalAllowed)}/><Row label="Expiry revocation" value={data.expiryRevocationMode}/><Row label="Live test allowlist" value={data.liveTestAllowedPrincipals.join(', ')||'Not configured'}/></dl><h3>Active account-scoped grants</h3><pre>{JSON.stringify(data.roleGrants,null,2)}</pre><h3>Explicit CLI workflow</h3><pre>npm run dev:grant-request-access -- --user-email user@example --account-id 123456789012 --roles SECURITY_REVIEWER,PROVISIONER --confirm</pre><p>Sign out and back in after changing grants so the server-managed session reloads them.</p></section>}
function ScopeAssignment({data,onSave,busy}:{data:any;onSave:(value:any)=>void;busy:boolean}){const [membershipId,setMembershipId]=useState(data.users[0]?.memberships[0]?.id??''),[accountId,setAccountId]=useState(data.accounts[0]?.id??'');return <section className="panel"><h2><Building2 size={18}/> Assign account scope</h2><p>Platform administrators receive no customer AWS scope automatically.</p><div className="form-grid"><label className="field"><span>Tenant member</span><select value={membershipId} onChange={event=>setMembershipId(event.target.value)}>{data.users.flatMap((user:any)=>user.memberships.map((membership:any)=><option value={membership.id} key={membership.id}>{user.displayName} — {membership.role.replaceAll('_',' ')}</option>))}</select></label><label className="field"><span>AWS account</span><select value={accountId} onChange={event=>setAccountId(event.target.value)}>{data.accounts.map((account:any)=><option value={account.id} key={account.id}>{account.accountName} ({account.accountId})</option>)}</select></label></div><button className="btn primary" disabled={busy} onClick={()=>onSave({membershipId,scopeType:'AWS_ACCOUNT',scopeId:accountId,includeDescendants:true,canView:true,canRequest:true,canApprove:false,canProvision:false,canRevoke:false,canManageConfiguration:false})}>{busy?'Saving…':'Grant view and request scope'}</button></section>}
function Row({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
