import { useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { AlertTriangle,CheckCircle2,Pencil,RefreshCw,Trash2,Wrench } from 'lucide-react';
import { api } from '../lib/api';
import { useAuthStore } from '../store/auth';
import type { AwsAccountContext } from '../types';

type AccountForm={accountName:string;accountId:string;accountType:string;defaultRegion:string;connectionType:string;readRoleArn:string;provisionRoleArn:string;externalIdSecretReference:string;validateLater:boolean};
type Conflict={code:string;message:string;existingAccountId:string;connectionStatus:string;sourceType:string;connectionPresent?:boolean;canValidate:boolean;canEdit:boolean;canRemove:boolean;canRepair?:boolean;canConvert?:boolean};
const blank:AccountForm={accountName:'',accountId:'',accountType:'SANDBOX',defaultRegion:'af-south-1',connectionType:'LOCAL_DEFAULT_CREDENTIALS',readRoleArn:'',provisionRoleArn:'',externalIdSecretReference:'',validateLater:false};

export default function Connection(){
 const qc=useQueryClient(),session=useAuthStore(state=>state.session),setSession=useAuthStore(state=>state.setSession),activeId=session?.user?.activeAccountId;
 const accounts=useQuery({queryKey:['connections',session?.user?.activeTenantId],queryFn:api.connections});
 const diagnostics=useQuery({queryKey:['aws-diagnostics',activeId],queryFn:api.awsDiagnostics});
 const [form,setForm]=useState<AccountForm>(blank),[formOpen,setFormOpen]=useState(false),[editingId,setEditingId]=useState<string>(),[result,setResult]=useState<any>(),[conflict,setConflict]=useState<Conflict>();
 const refresh=async()=>{await Promise.all([qc.invalidateQueries({queryKey:['connections']}),qc.invalidateQueries({queryKey:['auth-context']}),qc.invalidateQueries({queryKey:['aws-diagnostics']})])};
 const syncSession=async()=>{const value=await api.session();setSession(value);await refresh()};
 const create=useMutation({mutationFn:api.createAwsAccount,onSuccess:async value=>{setConflict(undefined);setResult(value);closeForm();await syncSession()},onError:error=>{const detail=conflictFrom(error);if(detail){setConflict(detail);setFormOpen(false);void refresh()}}});
 const validate=useMutation({mutationFn:api.validateAwsAccount,onSuccess:async value=>{setResult(value);await syncSession()}});
 const update=useMutation({mutationFn:({id,input}:{id:string;input:unknown})=>api.updateAwsAccount(id,input),onSuccess:async value=>{setResult(value);closeForm();await refresh()}});
 const repair=useMutation({mutationFn:api.repairAwsAccount,onSuccess:async value=>{setConflict(undefined);setResult(value);await refresh()}});
 const convert=useMutation({mutationFn:api.convertAwsAccount,onSuccess:async value=>{setConflict(undefined);setResult(value);await refresh()}});
 const remove=useMutation({mutationFn:api.removeAwsAccount,onSuccess:async()=>{setConflict(undefined);setResult({removed:true});await syncSession()}});
 const select=useMutation({mutationFn:api.selectAccount,onSuccess:async value=>{await qc.cancelQueries();qc.clear();setSession(value)}});
 const pending=[create,validate,update,repair,convert,remove,select].some(item=>item.isPending),active=accounts.data?.find(account=>account.id===activeId);
 const error=create.error||validate.error||update.error||repair.error||convert.error||remove.error||select.error||accounts.error;
 function closeForm(){setForm(blank);setEditingId(undefined);setFormOpen(false)}
 function edit(account:AwsAccountContext){setConflict(undefined);setEditingId(account.id);setForm({...blank,accountName:account.accountName,accountId:account.accountId,accountType:account.accountType,defaultRegion:account.region,connectionType:account.connectionType,readRoleArn:account.readRoleArn??'',provisionRoleArn:account.provisionRoleArn??''});setFormOpen(true)}
 function submit(){const input={...form,readRoleArn:form.readRoleArn||undefined,provisionRoleArn:form.provisionRoleArn||undefined,externalIdSecretReference:form.externalIdSecretReference||undefined};if(editingId)update.mutate({id:editingId,input:{accountName:input.accountName,accountType:input.accountType,defaultRegion:input.defaultRegion,readRoleArn:input.readRoleArn,provisionRoleArn:input.provisionRoleArn,externalIdSecretReference:input.externalIdSecretReference}});else create.mutate(input)}
 return <div className="page">
  <div className="page-header"><div><p className="eyebrow">Connection</p><h1>AWS account connections</h1><p>Pending and failed manual connections remain visible here. Only validated connected accounts appear in the active-account selector.</p></div><div className="button-stack"><button className="btn secondary" onClick={()=>void api.validateLocalCredentials().then(setResult).catch(error=>setResult({success:false,message:friendlyError(error)}))}>Validate local AWS credentials</button><button className="primary-action" onClick={()=>{setConflict(undefined);setFormOpen(true)}}>Add AWS account</button></div></div>
  {error&&!conflict&&<div className="error-box" role="alert"><AlertTriangle size={17}/>{friendlyError(error)}</div>}
  {conflict&&<ConflictPanel conflict={conflict} busy={pending} onValidate={()=>validate.mutate(conflict.existingAccountId)} onRepair={()=>repair.mutate(conflict.existingAccountId)} onConvert={()=>confirm('Convert this existing record to a pending manual connection?')&&convert.mutate(conflict.existingAccountId)} onRemove={()=>confirm('Remove this stale manual account connection?')&&remove.mutate(conflict.existingAccountId)}/>}
  <section className="panel"><div className="panel-title">Manual accounts <button className="btn secondary" onClick={()=>accounts.refetch()}><RefreshCw size={14}/> Refresh</button></div>{accounts.isLoading?<p>Loading AWS connections…</p>:!accounts.data?.length?<div className="empty-state"><h2>No AWS accounts have been connected.</h2><p>Add an account or recover an existing conflicting record.</p><button className="btn primary" onClick={()=>setFormOpen(true)}>Add AWS account</button></div>:<div className="connection-account-list">{accounts.data.map(account=><AccountCard key={account.id} account={account} active={account.id===activeId} busy={pending} onValidate={()=>validate.mutate(account.id)} onRepair={()=>repair.mutate(account.id)} onSelect={()=>select.mutate(account.id)} onEdit={()=>edit(account)} onDisable={()=>update.mutate({id:account.id,input:{status:'DISABLED'}})} onRemove={()=>confirm(`Remove ${account.accountName}?`)&&remove.mutate(account.id)}/>)}</div>}</section>
  {formOpen&&<AccountEditor form={form} setForm={setForm} editing={Boolean(editingId)} busy={pending} onCancel={closeForm} onSubmit={submit}/>}
  <section className="overview-grid"><div className="panel wide"><div className="panel-title">Active account</div>{active?<dl><Row label="Account" value={`${active.accountName} (${active.accountId})`}/><Row label="Type / region" value={`${active.accountType} · ${active.region}`}/><Row label="Connection" value={`${active.connectionType} · ${active.connectionStatus}`}/><Row label="Last validated" value={active.lastValidatedAt?fmt(active.lastValidatedAt):'Never'}/><Row label="Last error" value={active.lastErrorMessage??'None'}/></dl>:<p>No AWS account selected.</p>}</div><div className="panel"><div className="panel-title">Development controls</div><div className="button-stack"><button className="btn secondary" onClick={()=>void api.clearAccount().then(value=>{qc.clear();setSession(value)})}>Clear AWS context</button><button className="btn secondary" onClick={()=>void api.clearAwsCache().then(setResult)}>Clear AWS cache</button></div></div></section>
  <section className="panel"><div className="panel-title">Diagnostics</div><pre>{JSON.stringify(diagnostics.data??{status:'Loading diagnostics…'},null,2)}</pre></section>
  {result&&<section className="panel success-box" aria-live="polite"><div className="panel-title"><CheckCircle2 size={17}/> Operation result</div><pre>{JSON.stringify(result,null,2)}</pre></section>}
 </div>;
}

function AccountCard({account,active,busy,onValidate,onRepair,onSelect,onEdit,onDisable,onRemove}:{account:AwsAccountContext;active:boolean;busy:boolean;onValidate:()=>void;onRepair:()=>void;onSelect:()=>void;onEdit:()=>void;onDisable:()=>void;onRemove:()=>void}){const usable=account.connectionStatus==='CONNECTED';return <article id={`account-${account.id}`} className={active?'connection-account selected':'connection-account'}><span><strong>{account.accountName}</strong><small>{account.accountId} · {account.accountType.replaceAll('_',' ')} · {account.region}</small><small>{account.sourceType??'LEGACY'} · {account.hasConnection?'Connection record present':'Connection record missing'}</small><small>{account.readRoleArn||'Backend default credential chain'}</small></span><em>{account.connectionType.replaceAll('_',' ')}</em><i className={account.connectionStatus.toLowerCase()}>{account.connectionStatus}</i><div className="button-stack">{!account.hasConnection?<button className="btn secondary" disabled={busy} onClick={onRepair}><Wrench size={14}/> Repair connection</button>:<button className="btn secondary" disabled={busy} onClick={onValidate}>Validate connection</button>}<button className="btn secondary" disabled={busy||!usable} onClick={onSelect}>Set active</button><button className="btn secondary" disabled={busy} onClick={onEdit}><Pencil size={14}/> Edit</button><button className="btn secondary" disabled={busy||account.connectionStatus==='DISABLED'} onClick={onDisable}>Disable</button><button className="icon-btn" aria-label={`Remove ${account.accountName}`} disabled={busy} onClick={onRemove}><Trash2 size={15}/></button></div></article>}
function ConflictPanel({conflict,busy,onValidate,onRepair,onConvert,onRemove}:{conflict:Conflict;busy:boolean;onValidate:()=>void;onRepair:()=>void;onConvert:()=>void;onRemove:()=>void}){return <section className="panel conflict-panel" role="alert"><div className="panel-title"><AlertTriangle size={17}/> This AWS account has already been added.</div><p>Status: <strong>{conflict.connectionStatus}</strong> · Source: <strong>{conflict.sourceType}</strong></p><div className="button-stack">{conflict.canValidate&&<button className="btn secondary" disabled={busy} onClick={onValidate}>Validate connection</button>}{conflict.canRepair&&<button className="btn secondary" disabled={busy} onClick={onRepair}>Repair missing connection</button>}{conflict.canConvert&&<button className="btn secondary" disabled={busy} onClick={onConvert}>Convert existing record to manual connection</button>}{conflict.canRemove&&<button className="btn secondary" disabled={busy} onClick={onRemove}>Remove stale connection</button>}</div></section>}
function AccountEditor({form,setForm,editing,busy,onCancel,onSubmit}:{form:AccountForm;setForm:(value:AccountForm)=>void;editing:boolean;busy:boolean;onCancel:()=>void;onSubmit:()=>void}){const set=(key:keyof AccountForm,value:string|boolean)=>setForm({...form,[key]:value});return <section className="panel"><div className="panel-title">{editing?'Edit AWS account':'Add AWS account'}</div><div className="form-grid onboarding-form"><Field label="Account name"><input value={form.accountName} onChange={event=>set('accountName',event.target.value)}/></Field><Field label="AWS account ID"><input value={form.accountId} disabled={editing} inputMode="numeric" maxLength={12} onChange={event=>set('accountId',event.target.value.replace(/\D/g,''))}/></Field><Field label="Account type"><select value={form.accountType} onChange={event=>set('accountType',event.target.value)}>{['SANDBOX','DEVELOPMENT','STAGING','PRODUCTION','SECURITY','MANAGEMENT','EXTERNAL'].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Default region"><input value={form.defaultRegion} onChange={event=>set('defaultRegion',event.target.value)}/></Field><Field label="Connection type"><select value={form.connectionType} disabled={editing} onChange={event=>set('connectionType',event.target.value)}><option>LOCAL_DEFAULT_CREDENTIALS</option><option>ASSUME_ROLE</option></select></Field>{form.connectionType==='ASSUME_ROLE'&&<Field label="Read role ARN"><input value={form.readRoleArn} onChange={event=>set('readRoleArn',event.target.value)}/></Field>}<Field label="Provision role ARN (optional)"><input value={form.provisionRoleArn} onChange={event=>set('provisionRoleArn',event.target.value)}/></Field><Field label="External ID secret reference (optional)"><input value={form.externalIdSecretReference} onChange={event=>set('externalIdSecretReference',event.target.value)}/></Field>{!editing&&<label className="field"><span><input type="checkbox" checked={form.validateLater} onChange={event=>set('validateLater',event.target.checked)}/> Save as pending and validate later</span></label>}<div className="button-stack"><button className="btn secondary" onClick={onCancel}>Cancel</button><button className="btn primary" disabled={busy||form.accountId.length!==12||!form.accountName} onClick={onSubmit}>{busy?'Saving…':editing?'Save configuration':'Add account'}</button></div></div></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Row({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function fmt(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}
function friendlyError(error:unknown){const value=error as {response?:{data?:{error?:{message?:string}}};message?:string};return value.response?.data?.error?.message??value.message??'The AWS operation failed.'}
export function conflictFrom(error:unknown){const value=(error as {response?:{data?:{error?:Conflict}}}).response?.data?.error;return value?.code==='AWS_ACCOUNT_ALREADY_EXISTS'?value:undefined}
