import { useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { AlertTriangle,CheckCircle2,RefreshCw,Trash2 } from 'lucide-react';
import { api } from '../lib/api';
import { useAuthStore } from '../store/auth';

const initial={accountName:'',accountId:'',accountType:'SANDBOX',defaultRegion:'af-south-1',connectionType:'LOCAL_DEFAULT_CREDENTIALS',readRoleArn:'',provisionRoleArn:'',externalIdSecretReference:'',validateLater:false};
export default function Connection(){
 const qc=useQueryClient(),session=useAuthStore(s=>s.session),setSession=useAuthStore(s=>s.setSession),activeId=session?.user?.activeAccountId;
 const connections=useQuery({queryKey:['connections',session?.user?.activeTenantId],queryFn:api.connections}),diagnostics=useQuery({queryKey:['aws-diagnostics',activeId],queryFn:api.awsDiagnostics});
 const [form,setForm]=useState(initial),[open,setOpen]=useState(false),[result,setResult]=useState<any>();
 const refresh=()=>{void qc.invalidateQueries({queryKey:['connections']});void qc.invalidateQueries({queryKey:['auth-context']});void qc.invalidateQueries({queryKey:['aws-diagnostics']})};
 const create=useMutation({mutationFn:api.createAwsAccount,onSuccess:value=>{setResult(value);setForm(initial);setOpen(false);refresh()}}),validate=useMutation({mutationFn:api.validateAwsAccount,onSuccess:value=>{setResult(value);refresh()}}),remove=useMutation({mutationFn:api.removeAwsAccount,onSuccess:async()=>{const next=await api.clearAccount();setSession(next);qc.clear();setResult({removed:true})}}),select=useMutation({mutationFn:api.selectAccount,onSuccess:async value=>{await qc.cancelQueries();qc.clear();setSession(value)}});
 const active=connections.data?.find(a=>a.id===activeId),pending=create.isPending||validate.isPending||remove.isPending||select.isPending,error=create.error||validate.error||remove.error||select.error||connections.error;
 const clearContext=async()=>{const value=await api.clearAccount();await qc.cancelQueries();qc.clear();setSession(value)};
 return <div className="page"><div className="page-header"><div><p className="eyebrow">Connection</p><h1>AWS account connections</h1><p>Only manually added accounts are shown. Credentials remain in the backend provider chain.</p></div><div className="button-stack"><button className="btn secondary" onClick={()=>void api.validateLocalCredentials().then(setResult).catch(error=>setResult({success:false,message:friendlyError(error)}))}>Validate local AWS credentials</button><button className="primary-action" onClick={()=>setOpen(true)}>Add AWS account</button></div></div>
 {error&&<div className="error-box" role="alert"><AlertTriangle size={17}/>{friendlyError(error)}</div>}
 <section className="panel"><div className="panel-title">Manual accounts <button className="btn secondary" onClick={()=>connections.refetch()}><RefreshCw size={14}/> Refresh</button></div>{connections.isLoading?<p>Loading AWS connections…</p>:!connections.data?.length?<div className="empty-state"><h2>No AWS accounts have been connected.</h2><p>Add an account, then validate it before browsing IAM data.</p><button className="btn primary" onClick={()=>setOpen(true)}>Add AWS account</button></div>:<div className="connection-account-list">{connections.data.map(a=><article className={a.id===activeId?'connection-account selected':'connection-account'} key={a.id}><span><strong>{a.accountName}</strong><small>{a.accountId} · {a.accountType.replaceAll('_',' ')} · {a.region}</small><small>{a.readRoleArn||'Backend default credential chain'}</small></span><em>{a.connectionType.replaceAll('_',' ')}</em><i className={a.connectionStatus.toLowerCase()}>{a.connectionStatus}</i><div className="button-stack"><button className="btn secondary" disabled={pending} onClick={()=>validate.mutate(a.id)}>Validate</button><button className="btn secondary" disabled={pending||!['CONNECTED','DEGRADED'].includes(a.connectionStatus)} onClick={()=>select.mutate(a.id)}>Set active</button><button className="icon-btn" aria-label={`Remove ${a.accountName}`} disabled={pending} onClick={()=>confirm(`Remove ${a.accountName}?`)&&remove.mutate(a.id)}><Trash2 size={15}/></button></div></article>)}</div>}</section>
 {open&&<section className="panel"><div className="panel-title">Add AWS account</div><div className="form-grid onboarding-form"><Field label="Account name"><input value={form.accountName} onChange={e=>setForm({...form,accountName:e.target.value})}/></Field><Field label="AWS account ID"><input value={form.accountId} inputMode="numeric" maxLength={12} onChange={e=>setForm({...form,accountId:e.target.value.replace(/\D/g,'')})}/></Field><Field label="Account type"><select value={form.accountType} onChange={e=>setForm({...form,accountType:e.target.value})}>{['SANDBOX','DEVELOPMENT','STAGING','PRODUCTION','SECURITY','MANAGEMENT','EXTERNAL'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Default region"><input value={form.defaultRegion} onChange={e=>setForm({...form,defaultRegion:e.target.value})}/></Field><Field label="Connection type"><select value={form.connectionType} onChange={e=>setForm({...form,connectionType:e.target.value})}><option>LOCAL_DEFAULT_CREDENTIALS</option><option>ASSUME_ROLE</option></select></Field>{form.connectionType==='ASSUME_ROLE'&&<Field label="Read role ARN"><input value={form.readRoleArn} onChange={e=>setForm({...form,readRoleArn:e.target.value})}/></Field>}<Field label="Provision role ARN (optional)"><input value={form.provisionRoleArn} onChange={e=>setForm({...form,provisionRoleArn:e.target.value})}/></Field><Field label="External ID secret reference (optional)"><input value={form.externalIdSecretReference} onChange={e=>setForm({...form,externalIdSecretReference:e.target.value})}/></Field><label className="field"><span><input type="checkbox" checked={form.validateLater} onChange={e=>setForm({...form,validateLater:e.target.checked})}/> Save as pending and validate later</span></label><div className="button-stack"><button className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary" disabled={create.isPending||form.accountId.length!==12||!form.accountName} onClick={()=>create.mutate({...form,readRoleArn:form.readRoleArn||undefined,provisionRoleArn:form.provisionRoleArn||undefined,externalIdSecretReference:form.externalIdSecretReference||undefined})}>{create.isPending?'Validating…':'Add account'}</button></div></div></section>}
 <section className="overview-grid"><div className="panel wide"><div className="panel-title">Active account</div>{active?<dl><Row label="Account" value={`${active.accountName} (${active.accountId})`}/><Row label="Type / region" value={`${active.accountType} · ${active.region}`}/><Row label="Connection" value={`${active.connectionType} · ${active.connectionStatus}`}/><Row label="Last validated" value={active.lastValidatedAt?fmt(active.lastValidatedAt):'Never'}/><Row label="Last error" value={active.lastErrorMessage??'None'}/></dl>:<p>No AWS account selected.</p>}</div><div className="panel"><div className="panel-title">Development controls</div><div className="button-stack"><button className="btn secondary" onClick={()=>void clearContext()}>Clear AWS context</button><button className="btn secondary" onClick={()=>void api.clearAwsCache().then(setResult)}>Clear AWS cache</button></div></div></section>
 <section className="panel"><div className="panel-title">Diagnostics</div><pre>{JSON.stringify(diagnostics.data??{status:'Loading diagnostics…'},null,2)}</pre></section>{result&&<section className="panel success-box" aria-live="polite"><div className="panel-title"><CheckCircle2 size={17}/> Operation result</div><pre>{JSON.stringify(result,null,2)}</pre></section>}</div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Row({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function fmt(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}
function friendlyError(error:unknown){const candidate=error as {response?:{data?:{error?:{message?:string}}};message?:string};return candidate.response?.data?.error?.message??candidate.message??'The AWS operation failed.'}
