import { useEffect,useRef,useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { AlertTriangle,CheckCircle2,Pencil,RefreshCw,Trash2,Wrench } from 'lucide-react';
import { api } from '../lib/api';
import { useAuthStore } from '../store/auth';
import type { AwsAccountContext } from '../types';
import {AwsConnectionGuideButton,AwsConnectionGuideDialog,type ConnectionMethod} from '../components/aws-connection-guide';

type AccountForm={accountName:string;accountId:string;accountType:string;defaultRegion:string;connectionType:string;readRoleArn:string;provisionRoleArn:string;externalIdSecretReference:string;provisioningEnabled?:boolean;validateLater:boolean};
type ApiIssue={status?:number;code:string;message:string;correlationId?:string;existingAccountRecordId?:string;existingAccountId?:string;connectionStatus?:string;sourceType?:string;connectionPresent?:boolean;availableActions?:string[];canValidate?:boolean;canEdit?:boolean;canRemove?:boolean;canRepair?:boolean;canConvert?:boolean};
const blank:AccountForm={accountName:'',accountId:'',accountType:'SANDBOX',defaultRegion:'af-south-1',connectionType:'LOCAL_DEFAULT_CREDENTIALS',readRoleArn:'',provisionRoleArn:'',externalIdSecretReference:'',provisioningEnabled:false,validateLater:false};

export default function Connection(){
 const qc=useQueryClient(),session=useAuthStore(state=>state.session),setSession=useAuthStore(state=>state.setSession),activeId=session?.user?.activeAwsAccountRecordId??session?.user?.activeAccountId;
 const accounts=useQuery({queryKey:['connections',session?.user?.activeTenantId],queryFn:api.connections});
 const diagnostics=useQuery({queryKey:['aws-diagnostics',activeId],queryFn:api.awsDiagnostics});
 const [form,setForm]=useState<AccountForm>(blank),[formOpen,setFormOpen]=useState(false),[guideOpen,setGuideOpen]=useState(false),[editingId,setEditingId]=useState<string>(),[result,setResult]=useState<any>(),[issue,setIssue]=useState<ApiIssue>(),[focusAccountId,setFocusAccountId]=useState<string>();
 const guideButtonRef=useRef<HTMLButtonElement>(null);
 const refresh=async()=>{await Promise.all([qc.invalidateQueries({queryKey:['connections']}),qc.invalidateQueries({queryKey:['auth-context']}),qc.invalidateQueries({queryKey:['aws-diagnostics']})])};
 const syncSession=async()=>{const value=await api.session();setSession(value);await refresh()};
 const create=useMutation({mutationFn:api.createAwsAccount,onSuccess:async value=>{setIssue(undefined);setResult(value);setFocusAccountId(value.account?.accountRecordId);closeForm();await syncSession()},onError:error=>{setIssue(issueFrom(error));void refresh()}});
 const validate=useMutation({mutationFn:api.validateAwsAccount,onSuccess:async value=>{setResult(value);await syncSession()},onError:error=>{setIssue(issueFrom(error));void refresh()}});
 const validateProvisionRole=useMutation({mutationFn:api.validateProvisionRole,onSuccess:async value=>{setResult(value);await refresh()},onError:error=>setIssue(issueFrom(error))});
 const update=useMutation({mutationFn:({id,input}:{id:string;input:unknown})=>api.updateAwsAccount(id,input),onSuccess:async value=>{setResult(value);closeForm();await refresh()}});
 const repair=useMutation({mutationFn:api.repairAwsAccount,onSuccess:async value=>{setIssue(undefined);setResult(value);setFocusAccountId(value.accountRecordId);await refresh()}});
 const convert=useMutation({mutationFn:api.convertAwsAccount,onSuccess:async value=>{setIssue(undefined);setResult(value);setFocusAccountId(value.accountRecordId);await refresh()}});
 const remove=useMutation({mutationFn:api.removeAwsAccount,onSuccess:async()=>{setIssue(undefined);setResult({removed:true});await syncSession()}});
 const reset=useMutation({mutationFn:({id,dryRun,confirm}:{id:string;dryRun:boolean;confirm:boolean})=>api.resetAwsAccount(id,dryRun,confirm),onSuccess:async value=>{setResult(value);if(!value.dryRun){setIssue(undefined);await syncSession()}}});
 const select=useMutation({mutationFn:api.selectAccount,onSuccess:async value=>{await qc.cancelQueries();qc.clear();setSession(value)}});
 const pending=[create,validate,validateProvisionRole,update,repair,convert,remove,reset,select].some(item=>item.isPending),active=accounts.data?.find(account=>account.accountRecordId===activeId);
 const error=validate.error||update.error||repair.error||convert.error||remove.error||reset.error||select.error||accounts.error;
 useEffect(()=>{if(!focusAccountId)return;requestAnimationFrame(()=>document.getElementById(`account-${focusAccountId}`)?.scrollIntoView({behavior:'smooth',block:'center'}))},[focusAccountId,accounts.data]);
 function closeForm(){setForm(blank);setEditingId(undefined);setFormOpen(false)}
 function edit(account:AwsAccountContext){setIssue(undefined);setEditingId(account.accountRecordId);setForm({...blank,accountName:account.accountName,accountId:account.awsAccountNumber,accountType:account.accountType,defaultRegion:account.region,connectionType:account.connectionType,readRoleArn:account.readRoleArn??'',provisionRoleArn:account.provisionRoleArn??'',externalIdSecretReference:'',provisioningEnabled:Boolean(account.provisioningEnabled),validateLater:false});setFormOpen(true)}
 function useGuideMethod(method:ConnectionMethod){setGuideOpen(false);setIssue(undefined);setEditingId(undefined);setForm(current=>applyGuideMethod(current,method));setFormOpen(true)}
 async function resetAccount(account:AwsAccountContext){const preview=await api.resetAwsAccount(account.accountRecordId,true,false);setResult(preview);if(preview.canReset&&confirm(`Reset onboarding for ${account.accountName}? This removes only this tenant's manual account and connection.`))reset.mutate({id:account.accountRecordId,dryRun:false,confirm:true})}
 function submit(){const input={...form,readRoleArn:form.readRoleArn||undefined,provisionRoleArn:form.provisionRoleArn||undefined,externalIdSecretReference:form.externalIdSecretReference||undefined};if(editingId)update.mutate({id:editingId,input:{accountName:input.accountName,accountType:input.accountType,defaultRegion:input.defaultRegion,readRoleArn:input.readRoleArn,provisionRoleArn:input.provisionRoleArn,externalIdSecretReference:input.externalIdSecretReference,provisioningEnabled:input.provisioningEnabled}});else create.mutate(input)}
 return <div className="page">
  <div className="page-header"><div><p className="eyebrow">Connection</p><h1>AWS account connections</h1><p>Pending and failed manual connections remain visible here. Only validated connected accounts appear in the active-account selector.</p></div><div className="connection-page-actions"><AwsConnectionGuideButton ref={guideButtonRef} userId={session?.user?.id} attention={!accounts.isLoading&&!accounts.data?.length} onOpen={()=>setGuideOpen(true)}/><button className="btn secondary" onClick={()=>void api.validateLocalCredentials().then(setResult).catch(error=>setResult({success:false,message:friendlyError(error)}))}>Validate local AWS credentials</button><button className="primary-action" onClick={()=>{setIssue(undefined);setFormOpen(true)}}>Add AWS account</button></div></div>
  {error&&<div className="error-box" role="alert"><AlertTriangle size={17}/>{friendlyError(error)}</div>}
  {issue&&<IssuePanel issue={issue} busy={pending} onOpen={()=>{const id=recordId(issue);if(id){setFocusAccountId(id);document.getElementById(`account-${id}`)?.scrollIntoView({behavior:'smooth',block:'center'})}}} onValidate={()=>recordId(issue)&&validate.mutate(recordId(issue)!)} onRepair={()=>recordId(issue)&&repair.mutate(recordId(issue)!)} onConvert={()=>recordId(issue)&&confirm('Convert this existing record to a pending manual connection?')&&convert.mutate(recordId(issue)!)} onRemove={()=>recordId(issue)&&confirm('Remove this stale manual account connection?')&&remove.mutate(recordId(issue)!)} />}
  <section className="panel"><div className="panel-title">Manual accounts <button className="btn secondary" onClick={()=>accounts.refetch()}><RefreshCw size={14}/> Refresh</button></div>{accounts.isLoading?<p>Loading AWS connections…</p>:!accounts.data?.length?<div className="empty-state"><h2>No AWS accounts have been connected.</h2><p>Add an account or recover an existing conflicting record.</p><button className="btn primary" onClick={()=>setFormOpen(true)}>Add AWS account</button></div>:<div className="connection-account-list">{accounts.data.map(account=><AccountCard key={account.accountRecordId} account={account} active={account.accountRecordId===activeId} busy={pending} onValidate={()=>validate.mutate(account.accountRecordId)} onValidateProvisionRole={()=>validateProvisionRole.mutate(account.accountRecordId)} onRepair={()=>repair.mutate(account.accountRecordId)} onSelect={()=>select.mutate(account.accountRecordId)} onEdit={()=>edit(account)} onDisable={()=>update.mutate({id:account.accountRecordId,input:{status:'DISABLED'}})} onRemove={()=>confirm(`Remove ${account.accountName}?`)&&remove.mutate(account.accountRecordId)} onReset={()=>void resetAccount(account)}/>)}</div>}</section>
  {formOpen&&<AccountEditor form={form} setForm={setForm} editing={Boolean(editingId)} busy={pending} issue={issue} onCancel={closeForm} onSubmit={submit}/>}
  <section className="overview-grid"><div className="panel wide"><div className="panel-title">Active account</div>{active?<dl><Row label="Account" value={`${active.accountName} (${active.accountId})`}/><Row label="Type / region" value={`${active.accountType} · ${active.region}`}/><Row label="Connection" value={`${active.connectionType} · ${active.connectionStatus}`}/><Row label="Last validated" value={active.lastValidatedAt?fmt(active.lastValidatedAt):'Never'}/><Row label="Last error" value={active.lastErrorMessage??'None'}/></dl>:<p>No AWS account selected.</p>}</div><div className="panel"><div className="panel-title">Development controls</div><div className="button-stack"><button className="btn secondary" onClick={()=>void api.clearAccount().then(value=>{qc.clear();setSession(value)})}>Clear AWS context</button><button className="btn secondary" onClick={()=>void api.clearAwsCache().then(setResult)}>Clear AWS cache</button></div></div></section>
  <section className="panel"><div className="panel-title">Diagnostics</div><pre>{JSON.stringify(diagnostics.data??{status:'Loading diagnostics…'},null,2)}</pre></section>
  {result&&<section className="panel success-box" aria-live="polite"><div className="panel-title"><CheckCircle2 size={17}/> Operation result</div><pre>{JSON.stringify(result,null,2)}</pre></section>}
  <AwsConnectionGuideDialog open={guideOpen} onClose={()=>setGuideOpen(false)} returnFocusRef={guideButtonRef} onUseMethod={useGuideMethod}/>
 </div>;
}

function AccountCard({account,active,busy,onValidate,onValidateProvisionRole,onRepair,onSelect,onEdit,onDisable,onRemove,onReset}:{account:AwsAccountContext;active:boolean;busy:boolean;onValidate:()=>void;onValidateProvisionRole:()=>void;onRepair:()=>void;onSelect:()=>void;onEdit:()=>void;onDisable:()=>void;onRemove:()=>void;onReset:()=>void}){const usable=['CONNECTED','DEGRADED'].includes(account.connectionStatus);return <article id={`account-${account.accountRecordId}`} className={active?'connection-account selected':'connection-account'}><span><strong>{account.accountName}</strong><small>{account.awsAccountNumber} · {account.accountType.replaceAll('_',' ')} · {account.region}</small><small>{account.sourceType??'LEGACY'} · {account.hasConnection?'Connection record present':'Connection record missing'}</small><small>{account.readRoleArn||'Backend default credential chain'}</small><small>Provision role: {account.provisionRoleStatus??'NOT VALIDATED'}{account.provisionRoleLastValidatedAt?` · ${fmt(account.provisionRoleLastValidatedAt)}`:''}</small></span><em>{account.connectionType.replaceAll('_',' ')}</em><i className={account.connectionStatus.toLowerCase()}>{account.connectionStatus.replaceAll('_',' ')}</i><div className="button-stack">{!account.hasConnection?<button className="btn secondary" disabled={busy} onClick={onRepair}><Wrench size={14}/> Repair connection</button>:<button className="btn secondary" disabled={busy} onClick={onValidate}>Validate connection</button>}{account.provisionRoleArn&&<button className="btn secondary" disabled={busy||!usable} onClick={onValidateProvisionRole}>Validate provision role</button>}<button className="btn secondary" disabled={busy||!usable} onClick={onSelect}>Set active</button><button className="btn secondary" disabled={busy} onClick={onEdit}><Pencil size={14}/> Edit</button><button className="btn secondary" disabled={busy||account.connectionStatus==='DISABLED'} onClick={onDisable}>Disable</button>{import.meta.env.DEV&&<button className="btn secondary" disabled={busy} onClick={onReset}>Reset onboarding</button>}<button className="icon-btn" aria-label={`Remove ${account.accountName}`} disabled={busy} onClick={onRemove}><Trash2 size={15}/></button></div></article>}
function IssuePanel({issue,busy,onOpen,onValidate,onRepair,onConvert,onRemove}:{issue:ApiIssue;busy:boolean;onOpen:()=>void;onValidate:()=>void;onRepair:()=>void;onConvert:()=>void;onRemove:()=>void}){const known=issue.code==='AWS_ACCOUNT_ALREADY_EXISTS'||issue.code==='LEGACY_ACCOUNT_CONFLICT',title=known?'This AWS account already exists for this tenant.':issue.status===409?'The server reported a conflict while adding this AWS account.':'The AWS account could not be added.';return <section className="panel conflict-panel" role="alert"><div className="panel-title"><AlertTriangle size={17}/>{title}</div><p>{issue.message}</p>{issue.connectionStatus&&<p>Status: <strong>{issue.connectionStatus}</strong> · Source: <strong>{issue.sourceType??'unknown'}</strong></p>}<div className="button-stack">{recordId(issue)&&<button className="btn secondary" disabled={busy} onClick={onOpen}>Open existing account</button>}{(issue.canValidate||issue.availableActions?.includes('VALIDATE'))&&<button className="btn secondary" disabled={busy} onClick={onValidate}>Validate connection</button>}{(issue.canRepair||issue.availableActions?.includes('REPAIR'))&&<button className="btn secondary" disabled={busy} onClick={onRepair}>Repair connection</button>}{issue.canConvert&&<button className="btn secondary" disabled={busy} onClick={onConvert}>Convert to manual connection</button>}{issue.canRemove&&<button className="btn secondary" disabled={busy} onClick={onRemove}>Remove stale record</button>}</div><details><summary>Technical details</summary><p>Error code: <code>{issue.code}</code></p><p>Correlation ID: <code>{issue.correlationId??'not supplied'}</code></p></details></section>}
function AccountEditor({form,setForm,editing,busy,issue,onCancel,onSubmit}:{form:AccountForm;setForm:(value:AccountForm)=>void;editing:boolean;busy:boolean;issue?:ApiIssue;onCancel:()=>void;onSubmit:()=>void}){const set=(key:keyof AccountForm,value:string|boolean)=>setForm({...form,[key]:value});return <section className="panel"><div className="panel-title">{editing?'Edit AWS account':'Add AWS account'}</div>{issue&&<div className="error-box" role="alert"><AlertTriangle size={17}/><span><strong>{issue.message}</strong><br/><small>{issue.code}{issue.correlationId?` · Correlation ${issue.correlationId}`:''}</small></span></div>}<div className="form-grid onboarding-form"><Field label="Account name"><input value={form.accountName} onChange={event=>set('accountName',event.target.value)}/></Field><Field label="AWS account ID"><input value={form.accountId} disabled={editing} inputMode="numeric" maxLength={12} onChange={event=>set('accountId',event.target.value.replace(/\D/g,''))}/></Field><Field label="Account type"><select value={form.accountType} onChange={event=>set('accountType',event.target.value)}>{['SANDBOX','DEVELOPMENT','STAGING','PRODUCTION','SECURITY','MANAGEMENT','EXTERNAL'].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Default region"><input value={form.defaultRegion} onChange={event=>set('defaultRegion',event.target.value)}/></Field><Field label="Connection type"><select value={form.connectionType} disabled={editing} onChange={event=>set('connectionType',event.target.value)}><option>LOCAL_DEFAULT_CREDENTIALS</option><option>ASSUME_ROLE</option></select></Field>{form.connectionType==='ASSUME_ROLE'&&<Field label="Read role ARN"><input value={form.readRoleArn} onChange={event=>set('readRoleArn',event.target.value)}/></Field>}<Field label="Provision role ARN (optional)"><input value={form.provisionRoleArn} onChange={event=>set('provisionRoleArn',event.target.value)}/></Field><Field label="External ID secret reference (optional)"><input value={form.externalIdSecretReference} onChange={event=>set('externalIdSecretReference',event.target.value)}/></Field>{editing&&<label className="field"><span><input type="checkbox" checked={form.provisioningEnabled} onChange={event=>set('provisioningEnabled',event.target.checked)}/> Enable provisioning for this account</span><small>Live provisioning still requires all server safety flags, a validated role, and workflow authorisation.</small></label>}{!editing&&<label className="field"><span><input type="checkbox" checked={form.validateLater} onChange={event=>set('validateLater',event.target.checked)}/> Save as pending and validate later</span></label>}<div className="button-stack"><button className="btn secondary" onClick={onCancel}>Cancel</button><button className="btn primary" disabled={busy||form.accountId.length!==12||!form.accountName} onClick={onSubmit}>{busy?'Saving…':editing?'Save configuration':'Add account'}</button></div></div></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Row({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function fmt(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}
function friendlyError(error:unknown){const value=error as {response?:{data?:{error?:{message?:string}}};message?:string};return value.response?.data?.error?.message??value.message??'The AWS operation failed.'}
function recordId(issue:ApiIssue){return issue.existingAccountRecordId??issue.existingAccountId}
export function issueFrom(error:unknown):ApiIssue{const response=(error as {response?:{status?:number;data?:{error?:ApiIssue}};message?:string}).response,value=response?.data?.error;return value?{status:response?.status,...value}:{code:'REQUEST_FAILED',message:(error as Error)?.message??'The AWS operation failed.'}}
export function conflictFrom(error:unknown){const value=issueFrom(error);return ['AWS_ACCOUNT_ALREADY_EXISTS','LEGACY_ACCOUNT_CONFLICT'].includes(value.code)?value:undefined}
export function applyGuideMethod(form:AccountForm,method:ConnectionMethod):AccountForm{return {...form,connectionType:method}}
