import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Link,useParams} from 'react-router-dom';
import {api} from '../lib/api';
import {approvalProvisionLabel,reviewCommentError,reviewProvisionButtonDisabled,type ReviewAction} from '../lib/review';
import {Button,LoadingSkeleton,Modal,RiskBadge,StatusBadge} from '../components/ui';
import {ProvisioningExperience,type ProvisioningEnvelope} from '../components/ProvisioningExperience';
import {ApprovalTimeline} from '../components/requestJourney';
import {useAuthStore} from '../store/auth';
import {can} from '../lib/authz';
import {accountLabel, requestRisk} from '../lib/requestPresentation';
import type {AttachedPolicy,PermissionRequest,ReviewCapabilities} from '../types';

type ReviewResult=ProvisioningEnvelope;
type ApiIssue={code:string;message:string;correlationId?:string;blockingFields?:{field:string;message:string}[];recommendedAction?:string;awsError?:string;plannedOperations?:unknown[]};

export default function RequestDetail(){
 const {id=''}=useParams(),qc=useQueryClient(),session=useAuthStore(state=>state.session),canApprove=can(session,'REQUEST_APPROVE'),canReject=can(session,'REQUEST_REJECT'),canReassign=can(session,'REQUEST_REASSIGN'),canReview=can(session,'REQUEST_REVIEW'),canProvision=can(session,'PROVISION_EXECUTE'),canRevoke=can(session,'GRANT_REVOKE');
 const {data,isLoading}=useQuery({queryKey:['request',id],queryFn:()=>api.request(id),enabled:Boolean(id)});
 const connection=useQuery({queryKey:['connection'],queryFn:api.connection,enabled:Boolean(data?.provisioningResult)});
 const activity=useQuery({queryKey:['activity'],queryFn:api.activity,enabled:Boolean(data?.provisioningResult)});
 const approvers=useQuery({queryKey:['approvers',id],queryFn:()=>api.approvers(id),enabled:Boolean(id)&&canReassign});
 const [comment,setComment]=useState(''),[commentError,setCommentError]=useState<string>(),[result,setResult]=useState<ReviewResult>(),[liveConfirmOpen,setLiveConfirmOpen]=useState(false),[safeTargetConfirmed,setSafeTargetConfirmed]=useState(false),[awsMutationConfirmed,setAwsMutationConfirmed]=useState(false),[confirmationPhrase,setConfirmationPhrase]=useState(''),[selectedApprover,setSelectedApprover]=useState('');
 const reload=async()=>{await Promise.all([qc.invalidateQueries({queryKey:['request',id]}),qc.invalidateQueries({queryKey:['requests']}),qc.invalidateQueries({queryKey:['activity']})])};
 const review=useMutation({mutationFn:({action,key,confirmation}:{action:ReviewAction;key:string;confirmation?:{phrase:string;safeTargetConfirmed:true;awsMutationConfirmed:true}})=>api.review(id,action,comment,key,confirmation),onSuccess:async value=>{setResult(value);setCommentError(undefined);setLiveConfirmOpen(false);setSafeTargetConfirmed(false);setAwsMutationConfirmed(false);setConfirmationPhrase('');await reload()}});
 const reassign=useMutation({mutationFn:()=>api.reassignApprover(id,selectedApprover),onSuccess:reload});
 const simulate=useMutation({mutationFn:()=>api.simulate(id),onSuccess:reload}),provision=useMutation({mutationFn:()=>api.provision(id),onSuccess:async value=>{setResult(value);await reload()}}),revoke=useMutation({mutationFn:()=>api.revoke(id),onSuccess:reload});
 const busy=review.isPending||simulate.isPending||provision.isPending||revoke.isPending||reassign.isPending,error=review.error||simulate.error||provision.error||revoke.error||reassign.error;
 if(isLoading||!data)return <div className="page"><LoadingSkeleton rows={8}/></div>;
 const capabilities=data.reviewCapabilities,mode=capabilities?.provisioningMode??'disabled',localMode=mode==='local',pending=data.status==='Pending approval',readyForProvisioning=data.status==='Approved',approved=['Approved','Provisioning failed'].includes(data.status),failed=data.status==='Provisioning failed',provisioning=data.status==='Provisioning',activeGrant=data.status==='Provisioned',approvalAllowed=(localMode||canApprove)&&Boolean(capabilities?.approvalAllowed),effectiveCanProvision=localMode||canProvision,provisionReviewAllowed=approvalAllowed&&effectiveCanProvision&&Boolean(capabilities?.provisioningAllowed)&&Boolean(capabilities?.planValid),issue=error?readIssue(error):undefined;
 function submitReview(action:ReviewAction){
  if(review.isPending)return;
  const validationError=reviewCommentError(action,comment);if(validationError){setCommentError(validationError);return}setCommentError(undefined);
  if(action==='APPROVE_AND_PROVISION'&&mode==='live'&&!liveConfirmOpen){setLiveConfirmOpen(true);return}review.mutate({action,key:operationId()});
 }
 const accountName=data.reviewContext?.accountName??accountLabel(data),targetKind=iamTargetKind(data.targetType),targetConsoleUrl=iamTargetConsoleUrl(data.targetType,data.targetName);
 const risk=requestRisk(data);
 const summary=requestSummary(data,accountName,targetKind,risk);
 const change=requestedChange(data);
 const readiness=reviewReadiness(capabilities);
 return <div className="page detail-page compact-request-detail">
  <div className="detail-header compact"><div><Link to="/requests" className="back-link">← Requests</Link><div className="request-title-line"><h1>{data.id} · {data.title}</h1><StatusBadge status={data.status}/></div><p>{summary.contextLine}</p></div></div>
  <section className="request-summary-strip" aria-label="Request summary"><SummaryBlock label="Requested by" value={summary.requester}/><SummaryBlock label="Target" value={summary.target} detail={summary.targetKind}/><SummaryBlock label="Account" value={summary.account} detail={summary.accountNumber}/><SummaryBlock label="Duration" value={summary.duration} detail={summary.expiry}/><SummaryBlock label="Permission" value={summary.access} detail={summary.permissionCount}/><SummaryBlock label="Resource scope" value={summary.scope}/><SummaryBlock label="Submitted" value={summary.submitted}/><div className="summary-block"><span>Risk</span><strong><RiskBadge risk={risk}/></strong></div></section>
  <section className="request-section compact-justification"><h2>Business justification</h2><ClampText text={data.justification}/>{data.notes&&<details><summary>Optional notes</summary><p>{data.notes}</p></details>}</section>
  <section className="panel compact-workflow"><ApprovalTimeline request={data}/></section>
  <section className="detail-layout">
   <article className="detail-main">
    <section className="request-section requested-access-panel"><p className="eyebrow">Requested access</p><h2>{change.permissions}</h2><p className="muted">{change.permissionDetail}</p><dl className="clean-kv-list"><div><dt>Target</dt><dd>{change.target}<small>{change.targetDetail}</small></dd></div><div><dt>Resource scope</dt><dd>{change.scope}</dd></div><div><dt>Duration</dt><dd>{change.duration}<small>{change.window}</small></dd></div>{data.targetType==='GROUP'&&<><div><dt>Change</dt><dd>{change.groupChange}<small>{change.groupCurrent}</small></dd></div><div><dt>Members</dt><dd>{change.groupMembers}</dd></div><div><dt>Permissions</dt><dd>{change.groupPermissions}</dd></div></>}<div><dt>Risk</dt><dd><RiskBadge risk={risk}/></dd></div></dl>{change.extraPermissions.length>0&&<details className="inline-disclosure"><summary>View permission details</summary><ul>{change.allPermissions.map(item=><li key={item}>{item}</li>)}</ul></details>}{change.riskFactors.length>0&&<div className="risk-factor-list"><strong>Risk factors</strong><ul>{change.riskFactors.map(flag=><li key={flag}>{flag}</li>)}</ul></div>}</section>
    {(canReview||can(session,'REQUEST_VIEW_ALL')||can(session,'IDENTITY_VIEW_ALL'))&&<section className="request-section security-context compact-review-context"><h2>Review context</h2><dl className="review-context-list"><div><dt>Account connection</dt><dd>{data.reviewContext?.connectionStatus??'Unavailable'}</dd></div><div><dt>Approval stage</dt><dd>{pending?'Account approval':data.status}</dd></div><div><dt>Required reviewer</dt><dd>{data.requiredApprovalStages?.join(' → ')||'Account approver'}</dd></div><div><dt>Provisioning</dt><dd>{readiness.label}</dd></div></dl>{capabilities&&<details className="technical-details compact readiness-details"><summary><strong>Provisioning details</strong><small>{readiness.reason}</small></summary><div className="technical-details-body"><CapabilityChecklist capabilities={capabilities}/></div></details>}</section>}
    <details className="panel compact-permission-change"><summary><strong>Permission change preview</strong><span>{change.previewSummary}</span></summary><div className="compact-diff">{renderPolicySet('Before',dedupePolicies(data.preview?.before.managedPolicies??[]),data.preview?.before.inlinePolicies??[])}<i>→</i><div><h3>Requested</h3>{requestedPreviewItems(data).map(item=><p key={item.key}>{item.label}</p>)}<p><strong>Operation plan:</strong> {data.preview?.awsOperation}</p><small>Simulation is an estimate, not a guarantee of final live authorization.</small></div><i>→</i>{renderPolicySet('After',effectiveAfterPolicies(data),[],data.preview?.after.riskFlags??[])}</div>{data.items.some(i=>i.generatedPolicyDocument)&&<details className="generated-policy-summary"><summary>Generated policy document</summary><pre>{JSON.stringify(data.items.find(i=>i.generatedPolicyDocument)?.generatedPolicyDocument,null,2)}</pre></details>}</details>
    {Boolean(data.simulationResult)&&<section className="panel"><h2>Simulation results</h2><pre>{JSON.stringify(data.simulationResult,null,2)}</pre></section>}
    <ProvisioningExperience request={data} envelope={result} connection={connection.data} auditEvents={activity.data?.data} inProgress={review.isPending&&review.variables?.action==='APPROVE_AND_PROVISION'||provision.isPending} failure={issue?.code.includes('PROVISION')?{message:issue.message,code:issue.code,correlationId:issue.correlationId}:undefined} canRevoke={canRevoke&&activeGrant} revokePending={revoke.isPending} onRevoke={()=>revoke.mutate()}/>
   </article>
   <aside className="panel side-panel approval-panel compact-actions">
    <h2>{pending?'Review request':failed?'Provisioning failed':approved?'Ready for provisioning':provisioning?'Provisioning in progress':activeGrant?'Access active':'Request status'}</h2>
    <p className="muted">{pending?'Review the reason and requested access before making a decision.':failed?'Retry after reviewing the failure details.':approved?'Required approvals are complete. Provisioning is now the primary action.':provisioning?'PermissionHub is applying the approved IAM change.':activeGrant?'The approved permission is active.':'No workflow action is currently available.'}</p>
    {localMode&&<p className="info-note compact">Development provisioning mode enabled.</p>}
    {canReview&&pending&&<label className="field"><span>Reviewer comment</span><textarea value={comment} onChange={event=>{setComment(event.target.value);setCommentError(undefined)}} placeholder="Optional for approval; required for reject or information requests."/><small>Required for Reject and Request information.</small>{commentError&&<span className="field-error" role="alert">{commentError}</span>}</label>}
    {canReview&&<div className="approval-actions">
     {pending&&canApprove&&<Button onClick={()=>submitReview('APPROVE')} disabled={busy||!approvalAllowed}>Approve request</Button>}
     {pending&&localMode&&<Button variant="secondary" className="strong-secondary" title={capabilities?.reason} aria-busy={review.isPending} onClick={()=>submitReview('APPROVE_AND_PROVISION')} disabled={reviewProvisionButtonDisabled(mode,busy,pending,provisionReviewAllowed)}>{approvalProvisionLabel(mode)}</Button>}
     {pending&&!localMode&&canApprove&&effectiveCanProvision&&mode!=='disabled'&&<Button variant="secondary" className="strong-secondary" title={capabilities?.reason} onClick={()=>submitReview('APPROVE_AND_PROVISION')} disabled={reviewProvisionButtonDisabled(mode,busy,pending,provisionReviewAllowed)}>{approvalProvisionLabel(mode)}</Button>}
     {pending&&canApprove&&<Button variant="ghost" onClick={()=>submitReview('REQUEST_INFORMATION')} disabled={busy||!approvalAllowed}>Request information</Button>}
     {pending&&canReject&&<Button variant="danger" onClick={()=>submitReview('REJECT')} disabled={busy||!approvalAllowed}>Reject</Button>}
     {readyForProvisioning&&canProvision&&mode==='live'&&<Button title={capabilities?.reason} onClick={()=>provision.mutate()} disabled={busy||!capabilities?.planValid||!data.reviewContext?.provisionRoleConfigured}>Provision access</Button>}
     {readyForProvisioning&&canReview&&<Button variant="secondary" onClick={()=>simulate.mutate()} disabled={busy||(!localMode&&!canApprove)}>Run simulation</Button>}
     {failed&&canProvision&&<Button onClick={()=>provision.mutate()} disabled={busy}>Retry provisioning</Button>}
     {failed&&<a className="btn btn-secondary" href="#technical-details">View failure details</a>}
     {activeGrant&&targetConsoleUrl&&<a className="btn btn-secondary" href={targetConsoleUrl} target="_blank" rel="noreferrer">View AWS access</a>}
     {activeGrant&&canRevoke&&<Button variant="danger" onClick={()=>revoke.mutate()} disabled={busy}>Revoke access</Button>}
    </div>}
    {pending&&effectiveCanProvision&&mode!=='disabled'&&!provisionReviewAllowed&&<p className="muted action-hint">{readiness.label}</p>}
    {busy&&<p className="muted" aria-live="polite">Updating request lifecycle…</p>}
    {issue&&<IssuePanel issue={issue}/>}
    {canReassign&&<details className="more-review-options"><summary>More review options</summary><div className="reassign-approver"><h3>Reassign approver</h3><select aria-label="Eligible approver" value={selectedApprover} onChange={event=>setSelectedApprover(event.target.value)}><option value="">Select an eligible approver</option>{approvers.data?.map((item:any)=><option key={item.id} value={item.id}>{item.name} — {item.roles.join(', ')}</option>)}</select><Button variant="secondary" disabled={!selectedApprover||busy} onClick={()=>reassign.mutate()}>Reassign approver</Button></div></details>}
   </aside>
  </section>
  <details className="panel activity-accordion"><summary>Activity</summary><ol className="timeline">{data.timeline.map((event,index)=><li key={`${event.label}${index}`}><i/><div><strong>{event.label}</strong><span>{fmt(event.timestamp)}{event.result?` · ${event.result}`:''}</span></div></li>)}</ol></details>
  <Modal open={liveConfirmOpen} onClose={()=>setLiveConfirmOpen(false)} title={mode==='local'?'Confirm local development IAM change':'Confirm live IAM change'} wide><div className="live-provision-confirmation"><p className="warning">{mode==='local'?'DEVELOPMENT-ONLY local provisioning will use the currently connected backend AWS credentials and change IAM permissions.':'LIVE provisioning will change IAM permissions in AWS.'}</p><dl><div><dt>Account</dt><dd>{data.reviewContext?.accountName} · {data.reviewContext?.awsAccountNumber}</dd></div><div><dt>Environment</dt><dd>{data.reviewContext?.accountType}</dd></div><div><dt>Target</dt><dd>{data.targetType} · {data.targetArn}</dd></div><div><dt>Scope</dt><dd>{data.scope.type==='ALL'?'All applicable resources':data.scope.resources.join(', ')||data.scope.arn}</dd></div><div><dt>Duration / expiry</dt><dd>{data.duration} · {data.expiryDate?fmt(data.expiryDate):'Permanent'}</dd></div><div><dt>Provisioning mode</dt><dd>{mode==='local'?'LOCAL DEVELOPMENT':'LIVE'}</dd></div></dl><h3>Intended AWS operations</h3><pre>{JSON.stringify(capabilities?.plannedOperations??[],null,2)}</pre><label className="field"><span>Type PROVISION {data.id}</span><input value={confirmationPhrase} onChange={event=>setConfirmationPhrase(event.target.value)}/></label><label className="ack"><input type="checkbox" checked={safeTargetConfirmed} onChange={event=>setSafeTargetConfirmed(event.target.checked)}/><span>I confirm this target is safe for testing.</span></label><label className="ack"><input type="checkbox" checked={awsMutationConfirmed} onChange={event=>setAwsMutationConfirmed(event.target.checked)}/><span>I understand this will change IAM permissions in AWS.</span></label><div className="button-row"><Button variant="secondary" onClick={()=>setLiveConfirmOpen(false)}>Cancel</Button><Button disabled={confirmationPhrase!==`PROVISION ${data.id}`||!safeTargetConfirmed||!awsMutationConfirmed||review.isPending} onClick={()=>review.mutate({action:'APPROVE_AND_PROVISION',key:operationId(),confirmation:{phrase:confirmationPhrase,safeTargetConfirmed:true,awsMutationConfirmed:true}})}>Confirm and provision</Button></div></div></Modal>
 </div>;
}

function IssuePanel({issue}:{issue:ApiIssue}){return <div className="review-error" role="alert"><strong>{issue.message}</strong>{issue.awsError&&<p>AWS response: {issue.awsError}</p>}{issue.recommendedAction&&<p>{issue.recommendedAction}</p>}{issue.blockingFields?.map(item=><p key={item.field}><code>{item.field}</code>: {item.message}</p>)}<details><summary>Technical details</summary><p>Error code: <code>{issue.code}</code></p><p>Correlation ID: <code>{issue.correlationId??'not supplied'}</code></p>{issue.plannedOperations&&<pre>{JSON.stringify(issue.plannedOperations,null,2)}</pre>}</details></div>}
export function CapabilityChecklist({capabilities}:{capabilities:ReviewCapabilities}){return <div className="capability-checklist"><h3>Provisioning capability</h3>{capabilities.checklist.map(item=><div key={item.key} className={item.passed?'capability-pass':'capability-fail'}><strong>{item.passed?'✓':'✕'} {item.label}</strong>{item.reason&&<small>{item.reason}</small>}</div>)}{capabilities.blockingReasons.length>0&&<details><summary>Blocking reasons</summary><ul>{capabilities.blockingReasons.map(reason=><li key={reason}><code>{reason}</code></li>)}</ul></details>}<p className="muted">Required roles: {capabilities.requiredApproverRoles.join(', ')||'None'}<br/>Your roles: {capabilities.currentUserRoles.join(', ')||'None'}</p></div>}
export function isLiveConfirmationReady(requestId:string,phrase:string,safeTargetConfirmed:boolean,awsMutationConfirmed:boolean){return phrase===`PROVISION ${requestId}`&&safeTargetConfirmed&&awsMutationConfirmed}
function SummaryBlock({label,value,detail}:{label:string;value:string;detail?:string}){return <div className="summary-block"><span>{label}</span><strong>{value||'Unavailable'}</strong>{detail&&<small>{detail}</small>}</div>}
function ClampText({text}:{text:string}){const [open,setOpen]=useState(false),long=text.length>360;return <div className="clamped-text"><p className={!open&&long?'clamped':''}>{text}</p>{long&&<button type="button" onClick={()=>setOpen(value=>!value)}>{open?'Show less':'Show more'}</button>}</div>}
function fmt(value?:string){return value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Not submitted'}
function readIssue(error:unknown):ApiIssue{const value=(error as any)?.response?.data?.error;return value??{code:'REQUEST_ACTION_FAILED',message:(error as Error)?.message??'Request action failed.'}}
function operationId(){return globalThis.crypto?.randomUUID?.()??`review-${Date.now()}-${Math.random().toString(36).slice(2)}`}
function iamTargetKind(targetType:string){return targetType==='USER'?'IAM User':targetType==='ROLE'?'IAM Role':targetType==='GROUP'?'IAM User Group':targetType}
function iamTargetConsoleUrl(targetType:string,targetName:string){const encoded=encodeURIComponent(targetName);if(targetType==='USER')return `https://console.aws.amazon.com/iam/home#/users/details/${encoded}`;if(targetType==='ROLE')return `https://console.aws.amazon.com/iam/home#/roles/details/${encoded}`;if(targetType==='GROUP')return `https://console.aws.amazon.com/iam/home#/groups/details/${encoded}`;return undefined}
function requestSummary(request:PermissionRequest,account:string,targetKind:string,risk:string){const access=permissionNames(request),scope=scopeLabel(request),number=request.reviewContext?.awsAccountNumber??request.awsAccountId??'Account number unavailable';return {requester:request.requester,target:request.targetName,targetKind,account,accountNumber:number,access:firstWithCount(access),permissionCount:`${access.length} permission${access.length===1?'':'s'}`,scope,duration:request.duration,expiry:request.expiryDate?`Expires ${fmt(request.expiryDate)}`:'No automatic expiry',submitted:fmt(request.submittedAt),contextLine:`${account} · ${request.targetName} · ${targetKind} · ${request.duration} · ${risk} risk`}}
function requestedChange(request:PermissionRequest){const names=permissionNames(request),members=request.members??[],newMembers=members.filter(member=>!member.alreadyMember),newPolicies=request.items.filter(item=>!item.policyArn||!alreadyAttached(request,item.policyArn));const riskFactors=request.preview?.after.riskFlags??[];return {target:request.targetName,targetDetail:iamTargetKind(request.targetType),permissions:firstWithCount(names),permissionDetail:`${names.length} permission${names.length===1?'':'s'}`,allPermissions:names,extraPermissions:names.slice(3),scope:scopeLabel(request),duration:request.duration,window:`${fmt(request.startDate)} → ${request.expiryDate?fmt(request.expiryDate):'No automatic expiry'}`,groupChange:request.group?.mode==='EXISTING'?'Update existing group':request.group?.mode==='CREATE'?'Create group':'Not a group request',groupCurrent:`Current: ${members.filter(member=>member.alreadyMember).length} known members`,groupMembers:`+${newMembers.length} user${newMembers.length===1?'':'s'}`,groupPermissions:`+${newPolicies.length} polic${newPolicies.length===1?'y':'ies'}`,riskFactors,previewSummary:previewSummary(request)}}
function reviewReadiness(capabilities?:ReviewCapabilities){if(!capabilities)return {label:'Unavailable',reason:'Provisioning capability is unavailable.'};if(capabilities.planValid&&capabilities.provisioningAllowed)return {label:'Ready',reason:'Provisioning plan is ready.'};if(!capabilities.planValid)return {label:'Provisioning plan incomplete',reason:friendlyReason(capabilities.reason)};return {label:'Not ready',reason:friendlyReason(capabilities.reason)}}
function friendlyReason(value?:string){if(!value)return 'No blocking reason reported.';const map:Record<string,string>={PROVISIONING_PLAN_INVALID:'The IAM operation plan must be completed before access can be provisioned.',PROVISIONING_MODE_DRY_RUN:'Provisioning is configured for dry-run mode.',PROVISION_ROLE_NOT_CONFIGURED:'A provision role must be configured before live provisioning.',EXPIRY_REVOCATION_NOT_CONFIGURED:'Temporary-access cleanup must be configured.',CURRENT_USER_NOT_ASSIGNED_APPROVER:'Current user is not assigned as the approver.',CURRENT_USER_NOT_ELIGIBLE_APPROVER:'Current user is not eligible to approve this request.',SELF_APPROVAL_BLOCKED:'Requester self-approval is blocked.'};return map[value]??value.replaceAll('_',' ').toLowerCase().replace(/^\w/,letter=>letter.toUpperCase())}
function permissionNames(request:PermissionRequest){return request.items.map(item=>item.policyName??item.generatedPolicyName??item.requestedPolicyName??item.actions?.join(', ')??'Permission item')}
function firstWithCount(items:string[]){if(!items.length)return 'No permission selected';if(items.length===1)return items[0]??'Permission item';return `${items.slice(0,3).join(', ')}${items.length>3?` +${items.length-3} more`:''}`}
function scopeLabel(request:PermissionRequest){return request.scope.type==='ALL'?'All applicable resources':request.scope.resources.join(', ')||request.scope.arn||'Unspecified'}
function dedupePolicies(policies:AttachedPolicy[]){const seen=new Set<string>();return policies.filter(policy=>{const key=policy.policyArn||policy.policyName;if(seen.has(key))return false;seen.add(key);return true})}
function alreadyAttached(request:PermissionRequest,policyArn?:string){return Boolean(policyArn&&request.preview?.before.managedPolicies.some(policy=>policy.policyArn===policyArn))}
function requestedPreviewItems(request:PermissionRequest){return request.preview?.change.policiesToAttach.map(item=>{const key=item.policyArn??item.policyName??item.actions?.join(', ')??'requested';const label=item.policyArn&&alreadyAttached(request,item.policyArn)?`${item.policyName??item.policyArn} · Already attached`:item.policyName??item.actions?.join(', ')??'Permission item';return {key,label}})??[]}
function effectiveAfterPolicies(request:PermissionRequest){const before=dedupePolicies(request.preview?.before.managedPolicies??[]),requested=(request.preview?.change.policiesToAttach??[]).filter(item=>item.policyArn&&!alreadyAttached(request,item.policyArn)).map(item=>({policyName:item.policyName??item.policyArn!,policyArn:item.policyArn!}));return dedupePolicies([...before,...requested])}
function renderPolicySet(title:string,managed:AttachedPolicy[],inline:string[]=[],riskFlags:string[]=[]){return <div><h3>{title}</h3>{managed.length?managed.map(policy=><p key={policy.policyArn}>{policy.policyName}</p>):<p className="muted">No direct managed policies reported.</p>}{inline.map(policy=><p key={policy}>{policy} inline</p>)}{riskFlags.map(flag=><p className="risk-text" key={flag}>{flag}</p>)}</div>}
function previewSummary(request:PermissionRequest){const requested=request.preview?.change.policiesToAttach??[];if(requested.length&&requested.every(item=>item.policyArn&&alreadyAttached(request,item.policyArn)))return 'No effective policy change';return `${requested.length} requested change${requested.length===1?'':'s'}`}
