// @vitest-environment jsdom
import {renderToStaticMarkup} from 'react-dom/server';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {cleanup,render,screen,within} from '@testing-library/react';
import {MemoryRouter,Route,Routes} from 'react-router-dom';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import RequestDetail,{CapabilityChecklist,isLiveConfirmationReady} from './RequestDetail';
import {api} from '../lib/api';
import {useAuthStore} from '../store/auth';
import type {AuthSession,PermissionRequest,ReviewCapabilities} from '../types';

vi.mock('../lib/api',()=>({
 setCsrfToken:vi.fn(),
 api:{request:vi.fn(),connection:vi.fn(),activity:vi.fn(),approvers:vi.fn(),review:vi.fn(),reassignApprover:vi.fn(),simulate:vi.fn(),provision:vi.fn(),revoke:vi.fn()}
}));

const capabilities:ReviewCapabilities={requestId:'PR-1009',canReview:true,canApprove:false,canProvision:false,approvalAllowed:false,provisioningAllowed:false,provisioningMode:'dry-run',reason:'CURRENT_USER_NOT_ELIGIBLE_APPROVER',blockingReasons:['CURRENT_USER_NOT_ELIGIBLE_APPROVER','PROVISIONING_MODE_DRY_RUN'],requiredApproverRoles:['SECURITY_REVIEWER'],currentUserRoles:['ORGANISATION_ADMIN'],checklist:[{key:'approvalEligibility',label:'Eligible approver',passed:false,reason:'Assign the required reviewer role.'},{key:'planValidation',label:'Provisioning plan valid',passed:true}],planValid:true,plannedOperations:[],blockingFields:[],liveTestAllowedPrincipals:[],provisionRoleStatus:'NOT_VALIDATED',expiryRevocationMode:'disabled',selfApprovalAllowed:false};
const session:AuthSession={authenticated:true,csrfToken:'csrf',authProvider:'development',devAuthAvailable:true,user:{id:'reviewer',email:'reviewer@example.com',displayName:'Security Reviewer',provider:'development',providerSubject:'reviewer',activeTenantId:'tenant-1',activeAccountId:'account-1',activeAwsAccountRecordId:'account-1',permissions:['REQUEST_REVIEW','REQUEST_APPROVE','REQUEST_REJECT','REQUEST_VIEW_ALL'],memberships:[]}};
const request:PermissionRequest={id:'PR-1007',title:'Attach S3 read access for finance investigation',requester:'Maya Chen',requesterUserId:'maya',approver:'Security Reviewer',approverUserId:'reviewer',targetType:'USER',targetName:'maya.chen',targetArn:'arn:aws:iam::143671530412:user/maya.chen',items:[{mode:'MANAGED_POLICY',policyName:'AmazonS3ReadOnlyAccess',policyArn:'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'}],scope:{type:'RESOURCE',resources:['finance-reports-dev']},duration:'7 days',startDate:'2026-08-14T08:33:00.000Z',expiryDate:'2026-08-21T08:33:00.000Z',priority:'High',justification:'Finance reporting job failed and engineering needs read-only bucket access to compare generated report objects with source records.',status:'Pending approval',submittedAt:'2026-08-14T08:33:00.000Z',createdAt:'2026-08-14T08:30:00.000Z',timeline:[{label:'Submitted',timestamp:'2026-08-14T08:33:00.000Z'}],requiredApprovalStages:['ACCOUNT_APPROVER','SECURITY_REVIEWER'],completedApprovalStages:[],accountType:'PRODUCTION',reviewContext:{accountName:'Production',awsAccountNumber:'143671530412',accountType:'PRODUCTION',region:'af-south-1',connectionStatus:'CONNECTED',provisionRoleConfigured:false},reviewCapabilities:capabilities,preview:{estimate:true,before:{managedPolicies:[{policyName:'AmazonS3ReadOnlyAccess',policyArn:'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'}],inlinePolicies:[],effectiveActions:'estimate'},change:{policiesToAttach:[{policyName:'AmazonS3ReadOnlyAccess',policyArn:'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'}],policiesToDetach:[],resourceScope:{type:'RESOURCE',resources:['finance-reports-dev']}},after:{managedPolicies:[{policyName:'AmazonS3ReadOnlyAccess',policyArn:'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'},{policyName:'AmazonS3ReadOnlyAccess',policyArn:'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'}],newlyAllowedActions:[],riskFlags:['Data read access']},awsOperation:'AttachUserPolicy'}};
function renderDetail(value:PermissionRequest=request){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<MemoryRouter initialEntries={[`/requests/${value.id}`]}><QueryClientProvider client={client}><Routes><Route path="/requests/:id" element={<RequestDetail/>}/></Routes></QueryClientProvider></MemoryRouter>)}

beforeEach(()=>{useAuthStore.setState({session,loading:false});vi.mocked(api.request).mockResolvedValue(request);vi.mocked(api.approvers).mockResolvedValue([]);vi.mocked(api.activity).mockResolvedValue({data:[],pagination:{page:1,pageSize:10,total:0,totalPages:1}} as any);vi.mocked(api.connection).mockResolvedValue({} as any)});
afterEach(()=>{cleanup();vi.clearAllMocks();useAuthStore.getState().clear()});
describe('request provisioning capability UI',()=>{
 it('renders blocker codes and remediation',()=>{const html=renderToStaticMarkup(<CapabilityChecklist capabilities={capabilities}/>);expect(html).toContain('CURRENT_USER_NOT_ELIGIBLE_APPROVER');expect(html).toContain('Assign the required reviewer role.');expect(html).toContain('SECURITY_REVIEWER');expect(html).toContain('ORGANISATION_ADMIN')});
 it('requires the exact request phrase and both acknowledgements',()=>{expect(isLiveConfirmationReady('PR-1009','PROVISION PR-1009',true,true)).toBe(true);expect(isLiveConfirmationReady('PR-1009','PROVISION PR-1008',true,true)).toBe(false);expect(isLiveConfirmationReady('PR-1009','PROVISION PR-1009',false,true)).toBe(false)});
 it('renders the development bypass without a Provisioner role',()=>{const html=renderToStaticMarkup(<CapabilityChecklist capabilities={{...capabilities,provisioningMode:'local',localProvisioningEnabled:true,canApprove:true,canProvision:true,approvalAllowed:true,provisioningAllowed:true,blockingReasons:[],requiredApproverRoles:['DEVELOPMENT_REVIEW'],currentUserRoles:['REQUESTER'],checklist:[{key:'local',label:'Development provisioning authorization bypass',passed:true}]}}/>);expect(html).toContain('Development provisioning authorization bypass');expect(html).toContain('DEVELOPMENT_REVIEW');expect(html).toContain('REQUESTER')});
 it('renders a compact request overview without duplicate access summary sections',async()=>{renderDetail();const summary=await screen.findByLabelText('Request summary');expect(summary).toBeTruthy();expect(within(summary).getByText(/Maya Chen is requesting/)).toBeTruthy();expect(within(summary).getAllByText('AmazonS3ReadOnlyAccess').length).toBeGreaterThan(0);expect(within(summary).getByText('AWS account')).toBeTruthy();expect(within(summary).getByText('Target identity')).toBeTruthy();expect(screen.getByText('Business justification')).toBeTruthy();expect(screen.getByText('Requested access')).toBeTruthy();expect(screen.queryByText('Access summary')).toBeNull();expect(screen.queryByText('Scope and timing')).toBeNull();expect(screen.queryByText('Requested change')).toBeNull()});
 it('summarises permission preview without a before/requested/after diagram',async()=>{renderDetail();const preview=await screen.findByText('Permission change preview');expect(preview).toBeTruthy();expect(screen.getByText('No effective change')).toBeTruthy();expect(screen.getByText("AmazonS3ReadOnlyAccess is already attached to maya.chen. Approving this request will not change the user's effective permissions.")).toBeTruthy();expect(screen.getByText('Current status')).toBeTruthy();expect(screen.getByText('Already attached: AmazonS3ReadOnlyAccess')).toBeTruthy();expect(screen.getByText('Effective change')).toBeTruthy();expect(screen.queryByText('Before')).toBeNull();expect(screen.queryByText('After')).toBeNull();expect(screen.getByText('View technical details')).toBeTruthy()});
});
