import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Link,useParams} from 'react-router-dom';
import {api} from '../lib/api';
import {approvalProvisionLabel,reviewCommentError,reviewProvisionButtonDisabled,type ReviewAction} from '../lib/review';
import {Button,LoadingSkeleton,Modal,StatusBadge} from '../components/ui';
import {ProvisioningExperience,type ProvisioningEnvelope} from '../components/ProvisioningExperience';
import {ApprovalTimeline} from '../components/requestJourney';
import {useAuthStore} from '../store/auth';
import {can} from '../lib/authz';
import {accountLabel, requestRisk} from '../lib/requestPresentation';
import type {ReviewCapabilities} from '../types';

type ReviewResult=ProvisioningEnvelope;
type ApiIssue={code:string;message:string;correlationId?:string;blockingFields?:{field:string;message:string}[];recommendedAction?:string;awsError?:string;plannedOperations?:unknown[]};

export default function RequestDetail(){
 const {id=''}=useParams(),qc=useQueryClient(),session=useAuthStore(state=>state.session),canApprove=can(session,'REQUEST_APPROVE'),canReject=can(session,'REQUEST_REJECT'),canReassign=can(session,'REQUEST_REASSIGN'),canReview=can(session,'REQUEST_REVIEW'),canProvision=can(session,'PROVISION_EXECUTE'),canRevoke=can(session,'GRANT_REVOKE');
 const {data,isLoading}=useQuery({queryKey:['request',id],queryFn:()=>api.request(id),enabled:Boolean(id)});
 const connection=useQuery({queryKey:['connection'],queryFn:api.connection,enabled:Boolean(data?.provisioningResult)});
 const activity=useQuery({queryKey:['activity'],queryFn:api.activity,enabled:Boolean(data?.provisioningResult)});
 const approvers=useQuery({queryKey:['approvers',id],queryFn:()=>api.approvers(id),enabled:Boolean(id)&&canReassign});
 const [comment,setComment]=useState(''),[commentError,setCommentError]=useState<string>(),[result,setResult]=useState<ReviewResult>(),[liveConfirmOpen,setLiveConfirmOpen]=useState(false),[safeTargetConfirmed,setSafeTargetConfirmed]=useState(false),[awsMutationConfirmed,setAwsMutationConfirmed]=useState(false),[confirmationPhrase,setConfirmationPhrase]=useState(''),[selectedApprover,setSelectedApprover]=useState('');
 const reload=async()=>{await Promise.all([qc.invalidateQueries({queryKey:['request',id]}),qc.invalidateQueries({queryKey:['requests']}),qc.invalidateQueries({queryKey:['activity']})])};
 const review=useMutation({mutationFn:({action,key,confirmation}:{action:ReviewAction;key:string;confirmation?:{phrase:string;safeTargetConfirmed:true;awsMutationConfirmed:true}})=>api.review(id,action,comment,key,confirmation),onSuccess:async value=>{setResult(value);setCommentError(undefined);setLiveConfirmOpen(false);setSafeTargetConfirmed(false);setAwsMutationConfirmed(false);setConfirmationPhrase('');await reload()}});
 const reassign=useMutation({mutationFn:()=>api.reassignApprover(id,selectedApprover),onSuccess:reload});
 const simulate=useMutation({mutationFn:()=>api.simulate(id),onSuccess:reload}),provision=useMutation({mutationFn:()=>api.provision(id),onSuccess:async value=>{setResult(value);await reload()}}),revoke=useMutation({mutationFn:()=>api.revoke(id),onSuccess:reload});
 const busy=review.isPending||simulate.isPending||provision.isPending||revoke.isPending||reassign.isPending,error=review.error||simulate.error||provision.error||revoke.error||reassign.error;
 if(isLoading||!data)return <div className="page"><LoadingSkeleton rows={8}/></div>;
 const capabilities=data.reviewCapabilities,mode=capabilities?.provisioningMode??'disabled',localMode=mode==='local',pending=data.status==='Pending approval',readyForProvisioning=data.status==='Approved',approved=['Approved','Provisioning failed'].includes(data.status),failed=data.status==='Provisioning failed',provisioning=data.status==='Provisioning',activeGrant=data.status==='Provisioned',approvalAllowed=(localMode||canApprove)&&Boolean(capabilities?.approvalAllowed),effectiveCanProvision=localMode||canProvision,provisionReviewAllowed=approvalAllowed&&effectiveCanProvision&&Boolean(capabilities?.provisioningAllowed)&&Boolean(capabilities?.planValid),issue=error?readIssue(error):undefined;
 function submitReview(action:ReviewAction){
  if(review.isPending)return;
  const validationError=reviewCommentError(action,comment);if(validationError){setCommentError(validationError);return}setCommentError(undefined);
  if(action==='APPROVE_AND_PROVISION'&&mode==='live'&&!liveConfirmOpen){setLiveConfirmOpen(true);return}review.mutate({action,key:operationId()});
 }
 const accountName=accountLabel(data);
 const risk=requestRisk(data);
 return <div className="page detail-page compact-request-detail">
  <div className="detail-header compact"><div><Link to="/requests" className="back-link">← Requests</Link><div className="request-title-line"><h1>{data.id} · {data.title}</h1><StatusBadge status={data.status}/></div><p>{accountName} · {data.targetName} · {data.duration} · {risk} risk</p></div></div>
  <section className="panel compact-request-summary"><SummaryBlock label="Requested by" value={data.requester}/><SummaryBlock label="Target" value={data.targetName} detail={`IAM ${data.targetType==='USER'?'User':'Role'}`}/><SummaryBlock label="Account" value={accountName} detail={data.reviewContext?.awsAccountNumber??data.awsAccountId}/><SummaryBlock label="Access" value={data.items.map(item=>item.policyName??item.generatedPolicyName??item.actions?.join(', ')).join(', ')} detail={`${risk} risk`}/><SummaryBlock label="Duration" value={data.duration} detail={data.expiryDate?`Expires ${fmt(data.expiryDate)}`:'No automatic expiry'}/><SummaryBlock label="Resource scope" value={data.scope.type==='ALL'?'All applicable resources':data.scope.resources.join(', ')||data.scope.arn||'Unspecified'}/><SummaryBlock label="Submitted" value={fmt(data.submittedAt)}/></section>
  <section className="panel compact-justification"><h2>Business justification</h2><ClampText text={data.justification}/>{data.notes&&<details><summary>Optional notes</summary><p>{data.notes}</p></details>}</section>
  <section className="panel compact-workflow"><ApprovalTimeline request={data}/></section>
  <section className="detail-layout">
   <article className="detail-main">
    <section className="panel access-summary-panel"><p className="eyebrow">Access summary</p><h2>Requested AWS permission change</h2><div className="access-summary-grid"><SummaryBlock label="AWS account" value={accountName} detail={`${data.accountType??data.reviewContext?.accountType??'Account'} · ${data.reviewContext?.region??'region unavailable'}`}/><SummaryBlock label="Target identity" value={`${data.targetType} · ${data.targetName}`} detail={data.targetArn}/><SummaryBlock label="Requested access" value={data.items.map(item=>item.policyName??item.generatedPolicyName??item.actions?.join(', ')).join(', ')} detail={`${data.items.length} permission item${data.items.length===1?'':'s'}`}/><SummaryBlock label="Risk" value={risk} detail="Application-generated indicator"/></div></section>
    <section className="panel"><p className="eyebrow">Scope and timing</p><h2>Where and how long access applies</h2><dl className="detail-dl"><div><dt>Resource scope</dt><dd>{data.scope.type==='ALL'?'All applicable resources':data.scope.resources.join(', ')||data.scope.arn}</dd></div><div><dt>Duration</dt><dd>{data.duration}</dd></div><div><dt>Starts</dt><dd>{fmt(data.startDate)}</dd></div><div><dt>Expires</dt><dd>{data.expiryDate?fmt(data.expiryDate):'No automatic expiry'}</dd></div></dl></section>
    {(canReview||can(session,'REQUEST_VIEW_ALL')||can(session,'IDENTITY_VIEW_ALL'))&&<section className="panel security-context"><p className="eyebrow">Reviewer context</p><h2>Security and account checks</h2><dl className="detail-dl"><div><dt>Connection</dt><dd>{data.reviewContext?.connectionStatus??'Unavailable'}</dd></div><div><dt>Provision role</dt><dd>{data.reviewContext?.provisionRoleConfigured?'Configured':'Not configured'}</dd></div><div><dt>Required stages</dt><dd>{data.requiredApprovalStages?.join(' → ')||'Account approval'}</dd></div><div><dt>Completed stages</dt><dd>{data.completedApprovalStages?.join(' → ')||'None yet'}</dd></div></dl>{capabilities&&<CapabilityChecklist capabilities={capabilities}/>}</section>}
    <section className="panel"><h2>Permission change preview</h2><div className="preview-grid"><div><h3>Before</h3>{data.preview?.before.managedPolicies.map(p=><p key={p.policyArn}>{p.policyName}</p>)}{data.preview?.before.inlinePolicies.map(p=><p key={p}>{p} inline</p>)||<p className="muted">No inline policies reported.</p>}</div><div><h3>Requested change</h3>{data.preview?.change.policiesToAttach.map(p=><p key={p.policyArn??p.policyName}>{p.policyName??p.actions?.join(', ')}</p>)}<p><strong>Operation plan:</strong> {data.preview?.awsOperation}</p><small>Simulation is an estimate, not a guarantee of final live authorization.</small></div><div><h3>After</h3>{data.preview?.after.managedPolicies.map(p=><p key={p.policyArn}>{p.policyName}</p>)}{data.preview?.after.riskFlags.map(flag=><p className="risk-text" key={flag}>{flag}</p>)}</div></div>{data.items.some(i=>i.generatedPolicyDocument)&&<><h3>Generated policy document</h3><pre>{JSON.stringify(data.items.find(i=>i.generatedPolicyDocument)?.generatedPolicyDocument,null,2)}</pre></>}</section>
    {Boolean(data.simulationResult)&&<section className="panel"><h2>Simulation results</h2><pre>{JSON.stringify(data.simulationResult,null,2)}</pre></section>}
    <ProvisioningExperience request={data} envelope={result} connection={connection.data} auditEvents={activity.data?.data} inProgress={review.isPending&&review.variables?.action==='APPROVE_AND_PROVISION'||provision.isPending} failure={issue?.code.includes('PROVISION')?{message:issue.message,code:issue.code,correlationId:issue.correlationId}:undefined} canRevoke={canRevoke&&activeGrant} revokePending={revoke.isPending} onRevoke={()=>revoke.mutate()}/>
   </article>
   <aside className="panel side-panel approval-panel compact-actions">
    <h2>{pending?'Review request':failed?'Provisioning failed':approved?'Ready for provisioning':provisioning?'Provisioning in progress':activeGrant?'Access active':'Request status'}</h2>
    <p className="muted">{pending?'Review the reason and requested access before making a decision.':failed?'Retry after reviewing the failure details.':approved?'Required approvals are complete. Provisioning is now the primary action.':provisioning?'PermissionHub is applying the approved IAM change.':activeGrant?'The approved permission is active.':'No workflow action is currently available.'}</p>
    {localMode&&<details className="dev-mode-details"><summary>Development provisioning mode enabled</summary><div className="status-badge warning" role="status">LOCAL PROVISIONING</div><p className="muted">Development authorization and provision-role gates may be bypassed by server configuration.</p></details>}
    <div className={`provisioning-mode ${mode}`}><strong>{mode.replace('-',' ')} mode</strong><span>{capabilities?.reason??'Provisioning capability is unavailable.'}</span></div>
    {capabilities&&<div className="compact-capability-summary"><span>{capabilities.planValid?'✓':'✕'} Plan</span><span>{capabilities.approvalAllowed?'✓':'✕'} Approval</span><span>{capabilities.provisioningAllowed?'✓':'✕'} Provisioning</span></div>}
    {canReassign&&<div className="reassign-approver"><h3>Reassign approver</h3><select aria-label="Eligible approver" value={selectedApprover} onChange={event=>setSelectedApprover(event.target.value)}><option value="">Select an eligible approver</option>{approvers.data?.map((item:any)=><option key={item.id} value={item.id}>{item.name} — {item.roles.join(', ')}</option>)}</select><Button variant="secondary" disabled={!selectedApprover||busy} onClick={()=>reassign.mutate()}>Reassign approver</Button></div>}
    {canReview&&pending&&<label className="field"><span>Reviewer comment</span><textarea value={comment} onChange={event=>{setComment(event.target.value);setCommentError(undefined)}} placeholder="Optional for approval; required for reject or information requests."/><small>Required for Reject and Request information.</small>{commentError&&<span className="field-error" role="alert">{commentError}</span>}</label>}
    {canReview&&<div className="approval-actions">
     {pending&&canApprove&&<Button onClick={()=>submitReview('APPROVE')} disabled={busy||!approvalAllowed}>Approve request</Button>}
     {pending&&localMode&&<Button variant="secondary" className="strong-secondary" title={capabilities?.reason} aria-busy={review.isPending} onClick={()=>submitReview('APPROVE_AND_PROVISION')} disabled={reviewProvisionButtonDisabled(mode,busy,pending,provisionReviewAllowed)}>{approvalProvisionLabel(mode)}</Button>}
     {pending&&!localMode&&canApprove&&effectiveCanProvision&&mode!=='disabled'&&<Button variant="secondary" className="strong-secondary" title={capabilities?.reason} onClick={()=>submitReview('APPROVE_AND_PROVISION')} disabled={reviewProvisionButtonDisabled(mode,busy,pending,provisionReviewAllowed)}>{approvalProvisionLabel(mode)}</Button>}
     {pending&&canApprove&&<Button variant="ghost" onClick={()=>submitReview('REQUEST_INFORMATION')} disabled={busy||!approvalAllowed}>Request information</Button>}
     {pending&&canReject&&<Button variant="danger" onClick={()=>submitReview('REJECT')} disabled={busy||!approvalAllowed}>Reject</Button>}
     {readyForProvisioning&&canProvision&&mode==='live'&&<Button title={capabilities?.reason} onClick={()=>provision.mutate()} disabled={busy||!capabilities?.planValid||!data.reviewContext?.provisionRoleConfigured}>Provision access</Button>}
     {readyForProvisioning&&canReview&&<Button variant="secondary" onClick={()=>simulate.mutate()} disabled={busy||(!localMode&&!canApprove)}>Run simulation</Button>}
     {failed&&canProvision&&<Button onClick={()=>provision.mutate()} disabled={busy}>Retry provisioning</Button>}
     {failed&&<a className="btn btn-secondary" href="#technical-details">View failure details</a>}
     {activeGrant&&<a className="btn btn-secondary" href={`https://console.aws.amazon.com/iam/home#/${data.targetType==='USER'?'users':'roles'}/details/${encodeURIComponent(data.targetName)}`} target="_blank" rel="noreferrer">View AWS access</a>}
     {activeGrant&&canRevoke&&<Button variant="danger" onClick={()=>revoke.mutate()} disabled={busy}>Revoke access</Button>}
    </div>}
    {busy&&<p className="muted" aria-live="polite">Updating request lifecycle…</p>}
    {issue&&<IssuePanel issue={issue}/>}
   </aside>
  </section>
  <details className="panel activity-accordion"><summary>Activity</summary><ol className="timeline">{data.timeline.map((event,index)=><li key={`${event.label}${index}`}><i/><div><strong>{event.label}</strong><span>{fmt(event.timestamp)}{event.result?` · ${event.result}`:''}</span></div></li>)}</ol></details>
  <Modal open={liveConfirmOpen} onClose={()=>setLiveConfirmOpen(false)} title={mode==='local'?'Confirm local development IAM change':'Confirm live IAM change'} wide><div className="live-provision-confirmation"><p className="warning">{mode==='local'?'DEVELOPMENT-ONLY local provisioning will use the currently connected backend AWS credentials and change IAM permissions.':'LIVE provisioning will change IAM permissions in AWS.'}</p><dl><div><dt>Account</dt><dd>{data.reviewContext?.accountName} · {data.reviewContext?.awsAccountNumber}</dd></div><div><dt>Environment</dt><dd>{data.reviewContext?.accountType}</dd></div><div><dt>Target</dt><dd>{data.targetType} · {data.targetArn}</dd></div><div><dt>Scope</dt><dd>{data.scope.type==='ALL'?'All applicable resources':data.scope.resources.join(', ')||data.scope.arn}</dd></div><div><dt>Duration / expiry</dt><dd>{data.duration} · {data.expiryDate?fmt(data.expiryDate):'Permanent'}</dd></div><div><dt>Provisioning mode</dt><dd>{mode==='local'?'LOCAL DEVELOPMENT':'LIVE'}</dd></div></dl><h3>Intended AWS operations</h3><pre>{JSON.stringify(capabilities?.plannedOperations??[],null,2)}</pre><label className="field"><span>Type PROVISION {data.id}</span><input value={confirmationPhrase} onChange={event=>setConfirmationPhrase(event.target.value)}/></label><label className="ack"><input type="checkbox" checked={safeTargetConfirmed} onChange={event=>setSafeTargetConfirmed(event.target.checked)}/><span>I confirm this target is safe for testing.</span></label><label className="ack"><input type="checkbox" checked={awsMutationConfirmed} onChange={event=>setAwsMutationConfirmed(event.target.checked)}/><span>I understand this will change IAM permissions in AWS.</span></label><div className="button-row"><Button variant="secondary" onClick={()=>setLiveConfirmOpen(false)}>Cancel</Button><Button disabled={confirmationPhrase!==`PROVISION ${data.id}`||!safeTargetConfirmed||!awsMutationConfirmed||review.isPending} onClick={()=>review.mutate({action:'APPROVE_AND_PROVISION',key:operationId(),confirmation:{phrase:confirmationPhrase,safeTargetConfirmed:true,awsMutationConfirmed:true}})}>Confirm and provision</Button></div></div></Modal>
 </div>;
}

function IssuePanel({issue}:{issue:ApiIssue}){return <div className="review-error" role="alert"><strong>{issue.message}</strong>{issue.awsError&&<p>AWS response: {issue.awsError}</p>}{issue.recommendedAction&&<p>{issue.recommendedAction}</p>}{issue.blockingFields?.map(item=><p key={item.field}><code>{item.field}</code>: {item.message}</p>)}<details><summary>Technical details</summary><p>Error code: <code>{issue.code}</code></p><p>Correlation ID: <code>{issue.correlationId??'not supplied'}</code></p>{issue.plannedOperations&&<pre>{JSON.stringify(issue.plannedOperations,null,2)}</pre>}</details></div>}
export function CapabilityChecklist({capabilities}:{capabilities:ReviewCapabilities}){return <div className="capability-checklist"><h3>Provisioning capability</h3>{capabilities.checklist.map(item=><div key={item.key} className={item.passed?'capability-pass':'capability-fail'}><strong>{item.passed?'✓':'✕'} {item.label}</strong>{item.reason&&<small>{item.reason}</small>}</div>)}{capabilities.blockingReasons.length>0&&<details><summary>Blocking reasons</summary><ul>{capabilities.blockingReasons.map(reason=><li key={reason}><code>{reason}</code></li>)}</ul></details>}<p className="muted">Required roles: {capabilities.requiredApproverRoles.join(', ')||'None'}<br/>Your roles: {capabilities.currentUserRoles.join(', ')||'None'}</p></div>}
export function isLiveConfirmationReady(requestId:string,phrase:string,safeTargetConfirmed:boolean,awsMutationConfirmed:boolean){return phrase===`PROVISION ${requestId}`&&safeTargetConfirmed&&awsMutationConfirmed}
function SummaryBlock({label,value,detail}:{label:string;value:string;detail?:string}){return <div className="summary-block"><span>{label}</span><strong>{value||'Unavailable'}</strong>{detail&&<small>{detail}</small>}</div>}
function ClampText({text}:{text:string}){const [open,setOpen]=useState(false),long=text.length>360;return <div className="clamped-text"><p className={!open&&long?'clamped':''}>{text}</p>{long&&<button type="button" onClick={()=>setOpen(value=>!value)}>{open?'Show less':'Show more'}</button>}</div>}
function fmt(value?:string){return value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Not submitted'}
function readIssue(error:unknown):ApiIssue{const value=(error as any)?.response?.data?.error;return value??{code:'REQUEST_ACTION_FAILED',message:(error as Error)?.message??'Request action failed.'}}
function operationId(){return globalThis.crypto?.randomUUID?.()??`review-${Date.now()}-${Math.random().toString(36).slice(2)}`}
