export type TargetType='USER'|'ROLE'|'GROUP';
export type RequestStatus='Draft'|'Pending approval'|'More information required'|'Approved'|'Rejected'|'Provisioning'|'Provisioned'|'Provisioning failed'|'Expired'|'Revoked';
export type PolicyType='AWS_MANAGED'|'CUSTOMER_MANAGED';
export type RiskLevel='Low'|'Moderate'|'High'|'Critical';
export type AppRole='REQUESTER'|'ACCOUNT_APPROVER'|'OU_ADMIN'|'SECURITY_REVIEWER'|'PROVISIONER'|'ORGANISATION_ADMIN'|'PLATFORM_ADMIN';
export interface AdminScope{scopeType:'TENANT'|'AWS_ORGANISATION'|'ORGANISATIONAL_UNIT'|'AWS_ACCOUNT';scopeId:string;includeDescendants:boolean;canView:boolean;canRequest:boolean;canApprove:boolean;canProvision:boolean;canRevoke:boolean;canManageConfiguration:boolean}
export interface TenantMembership{id:string;tenantId:string;tenantName:string;tenantSlug:string;role:AppRole;status:string;scopes:AdminScope[]}
export interface SessionUser{id:string;email:string;displayName:string;provider:string;providerSubject:string;activeTenantId?:string;activeAwsAccountRecordId?:string;activeAccountId?:string;permissions:string[];memberships:TenantMembership[];roleAssignments?:{id:string;tenantId:string;awsAccountId:string;role:AppRole}[]}
export interface AuthSession{authenticated:boolean;user?:SessionUser;csrfToken:string;authProvider:string;devAuthAvailable:boolean;developmentAuthenticationActive?:boolean;awsConnectionMode?:string;demoDataEnabled?:boolean}
export interface AwsAccountContext{id:string;accountRecordId:string;tenantId:string;organisationId?:string;ouId?:string;ouPath?:string;accountId:string;awsAccountNumber:string;accountName:string;accountType:string;environment:string;riskTier:string;region:string;connectionType:string;connectionStatus:string;sourceType?:string;connectionSource?:string;isDemo?:boolean;hasConnection?:boolean;availableActions?:string[];readRoleArn?:string;provisionRoleArn?:string;provisionRoleConfigured?:boolean;externalIdConfigured?:boolean;credentialConfigured?:boolean;accessKeyIdMasked?:string;provisioningStatus?:string;provisioningEnabled?:boolean;provisionRoleStatus?:string;provisionRoleLastValidatedAt?:string;provisionRoleLastError?:string;lastValidatedAt?:string;lastSuccessfulReadAt?:string;lastSuccessfulProvisionAt?:string;lastErrorCode?:string;lastErrorMessage?:string}
export interface AppContext{tenants:{id:string;name:string;slug:string;role:AppRole}[];organisations:{id:string;tenantId:string;organisationId:string;name:string;connectionStatus:string}[];organisationalUnits:{id:string;organisationId:string;ouId:string;parentOuId?:string;name:string;fullPath:string}[];accounts:AwsAccountContext[];activeTenantId?:string;activeAwsAccountRecordId?:string;activeAccountId?:string;awsConnectionMode?:string}

export interface Page<T>{data:T[];pagination:{page:number;pageSize:number;total:number;totalPages:number};nextCursor?:string;isComplete?:boolean;loadedCount?:number;cacheStatus?:string;timing?:Record<string,unknown>}
export interface ConnectionStatus{mode:'MOCK'|'LIVE';connected:boolean;accountId:string;principalArn:string;region:string;credentialSource:string;lastChecked:string;message?:string;errorCode?:string}
export interface AttachedPolicy{policyName:string;policyArn:string}
export interface IamIdentity{id:string;type:TargetType;name:string;arn:string;path:string;createdAt:string;description?:string;passwordEnabled?:boolean;maxSessionDuration?:number;attachedPolicies:AttachedPolicy[];inlinePolicies:string[];permissionBoundary?:string;tags?:Record<string,string>;trustPolicy?:unknown;serviceLinked?:boolean;users?:{userName:string;arn?:string}[];userCount?:number}
export interface RiskAnalysis{level:RiskLevel;flags:string[];services:string[];accessLevels:string[]}
export interface IamPolicySummary{policyName:string;arn:string;policyId?:string;path?:string;description?:string;type:PolicyType;currentVersion:string;createdAt:string;updatedAt:string;attachmentCount:number;permissionsBoundaryUsageCount?:number;isAttachable?:boolean;services:string[];accessLevels:string[];risk:RiskAnalysis;deprecated:boolean}
export interface IamPolicyDetail extends IamPolicySummary{document:Record<string,unknown>;statements:unknown[];actions:string[];resources:string[];conditions:unknown[];attachedUsers:string[];attachedRoles:string[];attachedGroups:string[];observations:string[]}
export interface AwsResource{id:string;name:string;service:'S3'|'RDS'|'Lambda';type:string;region:string;arn:string;status:string;tags:Record<string,string>}
export interface RequestItem{mode:'MANAGED_POLICY'|'SPECIFIC_ACTIONS';policyArn?:string;policyName?:string;generatedPolicyName?:string;requestedPolicyName?:string;actions?:string[];generatedPolicyDocument?:Record<string,unknown>}
export interface PlannedOperation{service:'iam';operation:'CreateUser'|'CreateRole'|'UpdateAssumeRolePolicy'|'CreatePolicy'|'AttachUserPolicy'|'AttachRolePolicy'|'DetachRolePolicy'|'CreateGroup'|'AttachGroupPolicy'|'AddUserToGroup';executed:false;policyArn?:string;policyName?:string;policyPath?:string;policyDocument?:Record<string,unknown>;targetName?:string;targetArn?:string;groupName?:string;userName?:string}
export interface ReviewCapabilities{requestId:string;canReview:boolean;canApprove:boolean;canProvision:boolean;approvalAllowed:boolean;provisioningAllowed:boolean;provisioningMode:'disabled'|'dry-run'|'live'|'local';localProvisioningEnabled?:boolean;reason:string;blockingReasons:string[];requiredApproverRoles:string[];currentUserRoles:AppRole[];checklist:{key:string;label:string;passed:boolean;reason?:string}[];planValid:boolean;plannedOperations:PlannedOperation[];blockingFields:{field:string;message:string}[];liveTestAllowedPrincipals:string[];provisionRoleStatus:string;expiryRevocationMode:string;selfApprovalAllowed:boolean}
export interface PermissionRequest{id:string;title:string;tenantId?:string;awsOrganisationId?:string;ouId?:string;awsAccountId?:string;accountType?:string;requesterUserId?:string;requester:string;approver:string;approverUserId?:string;targetType:TargetType;targetName:string;targetArn:string;group?:{mode:'CREATE'|'EXISTING';name:string;path?:string;createdByPermissionHub?:boolean};members?:{userName:string;userArn?:string;operation?:'ADD'|'REMOVE';alreadyMember?:boolean;createUser?:boolean}[];approvalPolicyId?:string;requiredApprovalStages?:string[];completedApprovalStages?:string[];items:RequestItem[];scope:{type:'ALL'|'RESOURCE'|'ARN';resources:string[];arn?:string};duration:string;startDate:string;expiryDate?:string;priority:'Low'|'Medium'|'High'|'Critical'|'Normal'|'Urgent';justification:string;notes?:string;status:RequestStatus;submittedAt?:string;createdAt:string;approvalComment?:string;provisioningResult?:unknown;simulationResult?:unknown;timeline:{label:string;timestamp:string;result?:string}[];preview?:PermissionPreview;reviewCapabilities?:ReviewCapabilities;reviewContext?:{accountName:string;awsAccountNumber:string;accountType:string;region:string;connectionStatus:string;provisionRoleConfigured:boolean;provisionRoleArn?:string;provisionRoleStatus?:string;provisionRoleLastValidatedAt?:string;provisionRoleLastError?:string}}
export interface PermissionPreview{estimate:boolean;before:{managedPolicies:AttachedPolicy[];inlinePolicies:string[];effectiveActions:string};change:{policiesToAttach:{policyName?:string;policyArn?:string;actions?:string[]}[];policiesToDetach:unknown[];resourceScope:PermissionRequest['scope'];expiration?:string};after:{managedPolicies:AttachedPolicy[];newlyAllowedActions:string[];riskFlags:string[]};awsOperation:string;awsOperations?:string[]}
export interface AuditEvent{id:string;timestamp:string;actor:string;requestId?:string;awsAccountId?:string;targetArn?:string;policyArn?:string;action:string;previousState?:unknown;newState?:unknown;result:'SUCCESS'|'FAILED'|'INFO';errorCode?:string;awsRequestId?:string}
export interface Approver{id:string;name:string;email:string;role:string}
