import {ExternalLink,X} from 'lucide-react';
import {useEffect,useId,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {ConnectionGuideStep,SecurityNotice} from './ConnectionGuideStep';
import {CopyButton,PolicyCodeBlock} from './PolicyCodeBlock';
import {awsDocumentation,exampleRoleArn,policyText,readPolicy,recommendedRoleName,verifyIdentityCommand} from './guide-content';

export type ConnectionMethod='ASSUME_ROLE'|'ACCESS_KEYS'|'LOCAL_DEFAULT_CREDENTIALS';
type Props={open:boolean;onClose:()=>void;returnFocusRef:React.RefObject<HTMLButtonElement|null>;onUseMethod:(method:ConnectionMethod)=>void};

export function AwsConnectionGuideDialog({open,onClose,returnFocusRef,onUseMethod}:Props){
 const [tab,setTab]=useState<ConnectionMethod>('LOCAL_DEFAULT_CREDENTIALS'),dialogRef=useRef<HTMLDivElement>(null),titleId=useId();
 useEffect(()=>{if(open)setTab('LOCAL_DEFAULT_CREDENTIALS')},[open]);
 useEffect(()=>{if(!open)return;const scrollY=window.scrollY,previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';requestAnimationFrame(()=>dialogRef.current?.focus());function keydown(event:KeyboardEvent){if(event.key==='Escape'){event.preventDefault();onClose();return}if(event.key!=='Tab'||!dialogRef.current)return;const focusable=[...dialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])')];if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}document.addEventListener('keydown',keydown);return()=>{document.body.style.overflow=previousOverflow;document.removeEventListener('keydown',keydown);window.scrollTo?.({top:scrollY});returnFocusRef.current?.focus()}},[open,onClose,returnFocusRef]);
 if(!open)return null;
 return createPortal(<div className="connection-guide-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><div ref={dialogRef} className="connection-guide-dialog" role="dialog" aria-modal="true" aria-labelledby={titleId} tabIndex={-1}>
  <header className="connection-guide-header"><div><h2 id={titleId}>AWS connection setup</h2><p>Choose how PermissionHub connects to an AWS account.</p></div><button type="button" className="icon-btn" onClick={onClose} aria-label="Close AWS connection setup"><X size={19}/></button></header>
  <div className="connection-guide-tabs" role="tablist" aria-label="AWS connection method"><button role="tab" aria-selected={tab==='LOCAL_DEFAULT_CREDENTIALS'} aria-controls="default-guide" id="default-tab" onClick={()=>setTab('LOCAL_DEFAULT_CREDENTIALS')}>Default credentials</button><button role="tab" aria-selected={tab==='ACCESS_KEYS'} aria-controls="access-key-guide" id="access-key-tab" onClick={()=>setTab('ACCESS_KEYS')}>Access keys</button><button role="tab" aria-selected={tab==='ASSUME_ROLE'} aria-controls="role-guide" id="role-tab" onClick={()=>setTab('ASSUME_ROLE')}>Assume role <b>Recommended</b></button></div>
  <div className="connection-guide-content">
   <section className="connection-guide-overview"><h3>Choose a connection method</h3><p>PermissionHub needs read access to discover IAM identities and policies. A separate provisioning role can be added later for approved access changes.</p><div><article><strong>Default credentials</strong><span>Uses the backend AWS SDK provider chain such as AWS_PROFILE, environment variables or workload identity.</span></article><article><strong>Access keys</strong><span>Stores encrypted credentials server-side for local or legacy testing. Secrets are never returned to the browser.</span></article><article><strong>Assume role · Recommended</strong><span>Temporary credentials for cross-account and production use.</span></article></div><SecurityNotice>Start with read-only connectivity. Enable provisioning only after account validation is working.</SecurityNotice></section>
   {tab==='ASSUME_ROLE'?<RoleGuide onUseMethod={onUseMethod}/>:tab==='ACCESS_KEYS'?<AccessKeyGuide onUseMethod={onUseMethod}/>:<DefaultCredentialGuide onUseMethod={onUseMethod}/>}<DecisionCard/><OfficialDocumentationLinks/>
  </div>
  <footer className="connection-guide-footer"><a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html" target="_blank" rel="noopener noreferrer" aria-label="Open official AWS IAM security best practices in a new tab">Official AWS documentation <ExternalLink size={14}/></a><button type="button" className="primary-action" onClick={onClose}>Done</button></footer>
 </div></div>,document.body);
}

function RoleGuide({onUseMethod}:{onUseMethod:(method:ConnectionMethod)=>void}){return <div id="role-guide" role="tabpanel" aria-labelledby="role-tab" className="guide-method"><div><h2>Connect using an IAM Role</h2><p>Recommended for production and cross-account connections.</p></div>
 <ConnectionGuideStep number={1} title="Open IAM"><p>In the AWS account you want to connect, open IAM and choose Roles → Create role.</p><DocLink href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-custom.html" label="Open AWS role documentation"/></ConnectionGuideStep>
 <ConnectionGuideStep number={2} title="Choose Custom trust policy"><p>Select Custom trust policy. It identifies the PermissionHub backend principal that may assume this role.</p><PolicyCodeBlock label="Example trust policy — replace the placeholders" value={policyText.trust}/><ul><li>Replace the principal ARN with the IAM role used by the PermissionHub backend.</li><li>Use the External ID generated during onboarding; never use <code>*</code> as the trusted principal.</li><li>Remove TagSession or SetSourceIdentity only when PermissionHub is not configured to use them.</li><li>The External ID condition is especially important for external or customer-owned accounts.</li></ul></ConnectionGuideStep>
 <ConnectionGuideStep number={3} title="Add read permissions"><p>Create or attach a customer-managed read policy for validation and IAM discovery.</p><details><summary>View suggested read permissions</summary><PolicyCodeBlock label="Suggested read policy" value={policyText.read}/><p>This is a starting policy for PermissionHub’s current discovery features. Review and reduce it to the actions your deployment actually uses. Resource-listing IAM actions commonly require <code>Resource: "*"</code>.</p></details></ConnectionGuideStep>
 <ConnectionGuideStep number={4} title="Name the role"><p>Use <strong>{recommendedRoleName}</strong>, review the trust and permission policies, then create the role. Copy the role ARN, AWS account ID and default region.</p><div className="guide-inline-copy"><CopyButton value={recommendedRoleName} label="Copy role name"/><CopyButton value={exampleRoleArn} label="Copy example ARN"/></div><code>{exampleRoleArn}</code></ConnectionGuideStep>
 <ConnectionGuideStep number={5} title="Add it to PermissionHub"><p>Choose Add AWS account, select ASSUME_ROLE, and enter the account name, 12-digit account ID, account type, default region, read role ARN and configured External ID secret reference.</p><SecurityNotice>Do not paste the External ID value into ordinary notes or logs. Use the configured secret-management workflow.</SecurityNotice><button className="btn strong-secondary" onClick={()=>onUseMethod('ASSUME_ROLE')}>Use role connection</button></ConnectionGuideStep>
 <ConnectionGuideStep number={6} title="Validate"><p>Save the account and select Validate connection. PermissionHub assumes the read role, calls STS GetCallerIdentity, confirms the account number, then tests IAM users, roles and policies.</p><ConnectionChecklist/></ConnectionGuideStep>
 <details className="provisioning-guide"><summary>Optional: enable approved changes</summary><p>This is not required for read-only testing. Use a separate <strong>PermissionHubProvisionRole</strong> only after all required approvals.</p><PolicyCodeBlock label="Suggested starting provisioning permissions" value={policyText.provisioning}/><ul><li>Do not attach AdministratorAccess.</li><li>Narrow resources to permitted paths, roles and users and use permission boundaries where required.</li><li>Leave cross-account provisioning disabled until read validation succeeds.</li><li>Test provisioning in a non-production account first.</li></ul></details>
 </div>}

function DefaultCredentialGuide({onUseMethod}:{onUseMethod:(method:ConnectionMethod)=>void}){return <div id="default-guide" role="tabpanel" aria-labelledby="default-tab" className="guide-method"><div><h2>Connect using default credentials</h2><p>For local development with AWS_PROFILE, shared credentials, environment variables or temporary AWS credentials already configured on the backend machine.</p></div>
 <ConnectionGuideStep number={1} title="Configure credentials outside the repository"><p>Configure the machine running the backend. Do not paste keys into frontend code or commit them to Git.</p><PolicyCodeBlock label="Recommended local environment" value={'AWS_PROFILE=permissionhub-dev\nAWS_REGION=af-south-1'}/></ConnectionGuideStep>
 <ConnectionGuideStep number={2} title="Verify the identity"><PolicyCodeBlock label="AWS CLI verification command" value={verifyIdentityCommand}/><p>The returned account must match the AWS account you add in PermissionHub.</p></ConnectionGuideStep>
 <ConnectionGuideStep number={3} title="Connect in PermissionHub"><p>Choose Add AWS account, select Default credentials, enter the account details and validate. PermissionHub calls STS GetCallerIdentity and limited IAM list operations from the backend.</p><button className="btn strong-secondary" onClick={()=>onUseMethod('LOCAL_DEFAULT_CREDENTIALS')}>Use default credentials</button></ConnectionGuideStep>
 </div>}

function AccessKeyGuide({onUseMethod}:{onUseMethod:(method:ConnectionMethod)=>void}){return <div id="access-key-guide" role="tabpanel" aria-labelledby="access-key-tab" className="guide-method"><div><h2>Connect using access keys</h2><p>For local testing or systems that cannot yet use default credentials or role assumption.</p></div><SecurityNotice>Access keys are sensitive long-term credentials. PermissionHub encrypts them server-side and never returns the secret to the browser, but Assume role remains preferred for production.</SecurityNotice>
 <ConnectionGuideStep number={1} title="Create the user"><p>In IAM choose Users → Create user. Use <strong>PermissionHubLocal</strong>. Do not enable console access or create a password; this identity is for backend programmatic access only.</p><DocLink href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html" label="Open IAM user documentation"/></ConnectionGuideStep>
 <ConnectionGuideStep number={2} title="Add read permissions"><p>Attach the PermissionHub read policy. Start with discovery access only; do not give this user AdministratorAccess.</p><details><summary>View suggested read permissions</summary><PolicyCodeBlock label="Suggested read policy" value={JSON.stringify(readPolicy,null,2)}/></details></ConnectionGuideStep>
 <ConnectionGuideStep number={3} title="Create an access key"><p>Create an access key only when this method is required.</p><DocLink href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html" label="Open access-key documentation"/><ul><li>Securely record the secret once; never put it in source code, Git, or the PermissionHub browser.</li><li>Rotate or delete it when no longer needed.</li><li>Grant only permissions PermissionHub requires.</li></ul></ConnectionGuideStep>
 <ConnectionGuideStep number={4} title="Connect in PermissionHub"><p>Choose Add AWS account and select Access keys. Enter the key values in the secure backend-backed form, validate, then save the account.</p><SecurityNotice>Do not store these values in screenshots, logs, documentation examples, localStorage or source files.</SecurityNotice><button className="btn strong-secondary" onClick={()=>onUseMethod('ACCESS_KEYS')}>Use access keys</button></ConnectionGuideStep>
 </div>}

function ConnectionChecklist(){return <ul className="connection-guide-checklist" aria-label="Connection success checklist"><li>Account ID matches</li><li>IAM users readable</li><li>IAM roles readable</li><li>IAM policies readable</li></ul>}
function DecisionCard(){return <section className="guide-decision"><h3>Which option should I use?</h3><div><p><strong>Use Default credentials</strong> for local development when the backend already has AWS_PROFILE or temporary credentials.</p><p><strong>Use Access keys</strong> for local or legacy testing where you need to save a credential source in PermissionHub.</p><p><strong>Use Assume role</strong> for production, cross-account, AWS-hosted, temporary-credential, and multi-account deployments.</p></div><strong>Use Assume role for production. Treat access keys as temporary.</strong></section>}
function DocLink({href,label}:{href:string;label:string}){return <a className="guide-doc-link" href={href} target="_blank" rel="noopener noreferrer" aria-label={`${label} (opens in a new tab)`}>{label}<ExternalLink size={14}/></a>}
function OfficialDocumentationLinks(){return <section className="guide-docs"><h3>Official AWS documentation</h3><div>{awsDocumentation.map(([label,href])=><DocLink key={href} label={label} href={href}/>)}</div></section>}
