import { describe,expect,it } from 'vitest';
import { applyGuideMethod,authenticationRows,connectionMethodLabel,discoveryLabel,provisioningLabel,conflictFrom,issueFrom } from '../pages/Connection';

describe('AWS account onboarding conflicts',()=>{it('extracts a recoverable structured conflict',()=>{const conflict=conflictFrom({response:{data:{error:{code:'LEGACY_ACCOUNT_CONFLICT',message:'Conversion required.',existingAccountRecordId:'account-1',connectionStatus:'REPAIR_REQUIRED',sourceType:'LEGACY',canConvert:true,canRemove:true,correlationId:'correlation-1'}}}});expect(conflict).toMatchObject({existingAccountRecordId:'account-1',connectionStatus:'REPAIR_REQUIRED',canConvert:true,correlationId:'correlation-1'})});it('ignores unrelated API failures',()=>expect(conflictFrom({response:{data:{error:{code:'FORBIDDEN'}}}})).toBeUndefined())});
describe('AWS account onboarding errors',()=>{it('preserves backend code, status, message, and correlation ID for inline display',()=>expect(issueFrom({response:{status:409,data:{error:{code:'TENANT_ACCOUNT_UNIQUE_CONFLICT',message:'Conflict could not be recovered.',correlationId:'correlation-2'}}}})).toEqual({status:409,code:'TENANT_ACCOUNT_UNIQUE_CONFLICT',message:'Conflict could not be recovered.',correlationId:'correlation-2'}))});
describe('AWS connection guide form action',()=>{it('selects a connection method without resetting current onboarding values',()=>{const current={accountName:'Payments',accountId:'123456789012',accountType:'SANDBOX',defaultRegion:'af-south-1',connectionType:'LOCAL_DEFAULT_CREDENTIALS',readRoleArn:'draft-role',provisionRoleArn:'',externalIdSecretReference:'',accessKeyId:'',secretAccessKey:'',sessionToken:'',useSessionToken:false,replaceCredentials:false,validateLater:true};expect(applyGuideMethod(current,'ASSUME_ROLE')).toEqual({...current,connectionType:'ASSUME_ROLE'});expect(applyGuideMethod(current,'ACCESS_KEYS')).toEqual({...current,connectionType:'ACCESS_KEYS'})})});
describe('AWS connection summary labels',()=>{
 const base:any={hasConnection:true,connectionStatus:'CONNECTED',connectionType:'LOCAL_DEFAULT_CREDENTIALS',provisionRoleArn:undefined,provisionRoleStatus:'NOT_VALIDATED',provisioningStatus:'DISABLED'};
 it('maps connection enums to user-facing method labels',()=>{expect(connectionMethodLabel('LOCAL_DEFAULT_CREDENTIALS')).toBe('Default credentials');expect(connectionMethodLabel('ACCESS_KEYS')).toBe('Access keys');expect(connectionMethodLabel('ASSUME_ROLE')).toBe('Assume role')});
 it('summarises discovery and provisioning without raw enum labels',()=>{expect(discoveryLabel(base)).toBe('Discovery valid');expect(provisioningLabel(base)).toBe('Provisioning not configured');expect(provisioningLabel({...base,provisionRoleArn:'arn:aws:iam::123456789012:role/PH',provisionRoleStatus:'VALIDATED'})).toBe('Provisioning valid')});
 it('shows only masked access-key metadata in authentication details',()=>{expect(authenticationRows({...base,connectionType:'ACCESS_KEYS',credentialConfigured:true,accessKeyIdMasked:'AKIA••••ABCD'})).toEqual([['Method','Access keys'],['Credentials','Configured'],['Access Key ID','AKIA••••ABCD']])});
});
